
class CarbineLaserDecal : LaserBeamDecal
{
	Default
	{
		Translation "0:255=@64[8,128,8]";
	}
}


class LSR_CarbineTrail : LaserBeam
{
	Default
	{
		Alpha 2.0;
		Scale 2.0;
		LaserBeam.LaserColor "Green"; 
		LaserBeam.TrackWeapon true, PSP_WEAPON;
		LaserBeam.AimFromWeapon false;
		LaserBeam.LaserDecal "CarbineLaserDecal";
	}
	
	override void BeamTick()
	{
		alpha -= 0.5;
		if(alpha <= 0) Destroy();
	}
}