mixin class WorldAmmoBehavior
{
	// If true, ammo can only be picked up if the player owns this weapon.
	bool restrictedAmmo; 
	Property RestrictedAmmoType : restrictedAmmo;

	// Man, Mixins are really a god send for Ammo-based actors.
	override bool SpecialDropAction (Actor dropper)
	{
		if(dropper is "PlayerPawn") return false;
		
		// Only keep dropped ammo 50% of the time.
		if(random[WorldDroppedAmmo](0,100) > 50)
		{
			GoAwayAndDie();
		}
		return false;
	}
	
	bool ActorHasWeapon(Actor toucher)
	{
		bool hasWeapon = false;
		for(Inventory inv = toucher.inv; inv; inv = Inv.Inv)
		{
			let weap = Weapon(inv);
			if(!weap) continue;
			
			if(weap.ammoType1 == getClass() || weap.ammotype2 == getClass())
				hasWeapon = true;
		}
		return hasWeapon;
	}
	
	bool AllowPickup(Actor toucher)
	{
		return restrictedAmmo ? ActorHasWeapon(toucher) : true;
	}
	
	override bool CanPickup(Actor toucher)
	{
		bIGNORESKILL = true;
		bool res = super.CanPickup(toucher);
		if(!res) return res;
		
		return AllowPickup(toucher);
	}
}