struct LastDamageInfo
{
	bool processing; // If true, needs to be set to false before updated again.
	class<Actor> damager;
	bool headshot;
	bool killed;
	double dmgTaken;
	State prevState;
}

class HaloDoom_EnemyBase : Actor abstract
{
	transient LastDamageInfo damageInfo;
	double moveFriction, curChaseAngle, curDesiredAngle;
	vector3 targetLastPos, curTrackingPos;
	bool trackLastPos;
	int wanderTime;
	bool keepChaseAngle;
	
	Property HDE_MoveFriction : moveFriction;
	
	Default
	{
		HaloDoom_EnemyBase.HDE_MoveFriction 0.7;
	}
	
	override void Tick()
	{
		super.Tick();
		if(damageInfo.processing && InStateSequence(CurState, ResolveState("See")))
			damageInfo.processing = false;
			
		vel.xy *= moveFriction;			
		
		// Only use this when Chase3D is being used.
		if(!keepChaseAngle) 
			curDesiredAngle = angle;
	}
	
	States
	{
		Info.DamageTaken:
			"####" "#" 0 A_ResumePrevious();
	}	

	override int DamageMobJ(Actor inflictor, Actor source, int dmg, Name mod, int flags, double angle)
	{
		int dmg = super.DamageMobJ(inflictor, source, dmg, mod, flags, angle);
		if(dmg <= 0 || damageInfo.processing) return dmg;
		
		Actor damageSource = inflictor ? inflictor : source;
		if(!damageSource) return dmg; // Skip if we cannot find a damager.
		
		double headsize = 8;
		double dmgz = damageSource.pos.z;
        double headz    = (pos.z + default.height);
		
		bool isHeadshot = (dmgz <= headz) && (dmgz >= headz-headsize);
		damageInfo.damager = damageSource.getClass();
		damageInfo.headshot = isHeadshot;
		damageInfo.prevState = CurState;
		damageInfo.dmgTaken = dmg;
		damageInfo.killed = (health <= 0 || bCORPSE);
		damageInfo.processing = true;
		SetState(ResolveState("Info.DamageTaken"));
		return dmg;
	}

	State A_ResumePrevious()
	{
		damageInfo.processing = false;
		if(damageInfo.prevState)
		{
			State st = damageInfo.prevState;
			damageInfo.prevState = NULL;
			return st;
		}
			
		// Go back to doing whatever if there is nothing to resume to.
		return ResolveState(null);
	}
	
	bool A_CheckDamageInfo(class<Actor> damager, bool isHeadshot)
	{
		return (damageInfo.damager is damager) && (damageInfo.headshot == isHeadshot);
	}
	int A_GetDamageTaken(bool killed = false)
	{
		if(killed)
			return damageInfo.killed;
		else
			return ceil(damageInfo.dmgTaken);
	}

	void A_AimToTarget(double heightAimScale, Actor victim = NULL)
	{
		if(!target) return;
		
		if(!victim) victim = target;
		vector3 aimFrom = (pos.xy, pos.z + (height * 0.5));
		vector3 aimTo = (victim.pos.xy, victim.pos.z + (height * heightAimScale));
		vector2 aimDir = (angle, pitch);
		
		let diff = level.vec3diff(aimFrom, aimTo);
		if(diff.Length() > 1) diff = diff.Unit();
		aimDir = (atan2(diff.y, diff.x), -asin(diff.z));
		
		A_SetAngle(aimDir.x, SPF_INTERPOLATE);
		A_SetPitch(aimDir.y, SPF_INTERPOLATE);
	}

	Actor A_Fire3DProjectile(class<Actor> proj, double forward = 0, double leftright = 0, double updown = 0, double angleOffset = 0, double pitchOffset = 0)
	{
		let projActor = HaloMath.Fire3DProjectile(self, proj, forward, leftright, updown, false, angleOffset, pitchOffset);
		if(projActor) projActor.target = self;
		
		return projActor;
	}
	
	void A_Fire3DProjectiles(class<Actor> proj, double count, double angleSpread = 0, double pitchSpread = 0, double forward = 0, double leftright = 0, double updown = 0, out Array<Actor> projectiles = NULL)
	{
		for(int i = 0; i < count; i++)
		{
			vector2 spread = (
				frandom(-angleSpread, angleSpread),
				frandom(-pitchSpread, pitchSpread)
			);
			let proj = A_Fire3DProjectile(proj, forward, leftright, updown, spread.x, spread.y);
			if(projectiles) projectiles.Push(proj);
		}
	}
	
	BulletCasing A_SpawnWeaponDebris(class<BulletCasing> debris, double fw, double lr, double ud, double vel_fw, double vel_lr, double vel_ud)
	{
		CVar doSpawnFX = CVar.GetCVar("halodoom_fx_casings", players[consoleplayer]);
		if(!doSpawnFX || !doSpawnFX.GetBool()) return NULL;
		
		vector3 spawnDir = Quat.FromAngles(angle, pitch, roll) * (fw, lr, ud);
		vector3 spawnPos = level.vec3offset( (pos.xy, pos.z + (height * 0.5)), spawnDir );
		
		let proj = BulletCasing(Spawn(debris, spawnPos));
		if(proj)
		{
			proj.vel = Quat.FromAngles(angle, pitch, roll) * (vel_fw, vel_lr, vel_ud);
			proj.target = self;
		}
		return proj;
	}
	
	ShieldProcessor A_SetupShield(double maxShields, double regenDelay, double regenSpeed, Sound snd_ShieldBreak = "Shield/Explode", Sound snd_ShieldLow = "Shield/Low", Sound snd_ShieldRecover = "Shield/Regenerate", class<ShieldProcessor> type = "ShieldProcessor")
	{	
		let shields = ShieldProcessor.Attach(self);
		shields.maxShields = maxShields;
		shields.regenDelay = regenDelay;
		shields.regenSpeed = regenSpeed;
		shields.snd_ShieldBreak = snd_ShieldBreak;
		shields.snd_ShieldRecover = snd_ShieldRecover;	
		
		return shields;
	}
	
	// Smooth directional chase
	virtual void A_Chase3D(StateLabel meleeState = "Melee", StateLabel missileState = "Missile", int flags = 0)
	{
		double prevAngle = angle;
		bool noMove = flags & CHF_DONTMOVE;

		// Not going to be a rewrite or a fully custom chase, as there is a LOT going on, on that front.
		// So, we'll handle direction turning and movement instead.
		State prevState = CurState;
		A_Chase(meleeState, missileState, flags | CHF_DONTMOVE | CHF_DONTTURN);
	
		// Jump occured, leave control to missile or see
		bool changedStates = (prevState != CurState);
		keepChaseAngle = !changedStates;
		if(changedStates) return;

		// Wander if no target
		if(!target) 
		{
			A_Wander3D();
			return;
		}
		
		// Find real move direction
		LookExParams look;
		look.FOV = 360;
		bool canSee = IsVisible(target, true, look);
		
		FLineTraceData lt;
		LineTrace(angle, 64, pitch, data:lt);
		bool canMoveTo = lt.HitType == TRACE_HitNone;
		
		look.FOV = 90;
		bool inView = IsVisible(target, false, look);
		
		if(canSee && canMoveTo)
		{
			// Can see and move towards
			UpdateDesiredAngle(target.pos);
			if(!noMove) MoveTowardsFacing();
			
			targetLastPos = target.pos;
			trackLastPos = true;
		}
		else if(canMoveTo)
		{	
			// Cannot see, but can move.
			if(trackLastPos)
			{
				vector3 diff = level.Vec3Diff(pos, targetLastPos);
				curDesiredAngle = atan2(diff.y, diff.x);
				if(!noMove) MoveTowardsFacing(0.8);
				
				if( diff.Length() <= radius*2.0 ) 
				{
					// If we're still looking at this point, we've got no idea where 
					// they went.
					trackLastPos = false;
				}
			}
			else 
			{
				// Wander about
				A_Wander3D();
			}
		}
		else if(!canMoveTo) 
		{
			NewChaseDir();
			curDesiredAngle = HaloMath.LerpDegrees(curDesiredAngle, movedir*45, 0.25);
			
			if(!noMove) MoveTowardsFacing(0.9);
		}
	}
	
	virtual void A_Wander3D()
	{
		wanderTime++;
			
		vector3 posDiff = level.Vec3Diff(pos, curTrackingPos);
		bool atChasePos = (posDiff.Length() <= radius*2.0);
		
		FLineTraceData lt;
		LineTrace(angle, radius+128, pitch, data:lt);
		bool canMoveTo = lt.HitType == TRACE_HitNone;
		
		if(atChasePos || wanderTime >= (35*10) || !canMoveTo)
		{
			vector3 wanderPos = (
				frandom[HDEWanderRNG](-1,1),
				frandom[HDEWanderRNG](-1,1),
				frandom[HDEWanderRNG](-1,1)
			) * frandom[HDEWanderRNG](-1024, 1024);
			
			wanderPos = level.vec3offset(pos, Quat.FromAngles(angle,0,0) * wanderPos);
			curTrackingPos = wanderPos;
			wanderTime = 0;
		}
		
		// Move
		UpdateDesiredAngle(curTrackingPos);
		MoveTowardsFacing(0.9);
	}
	
	void MoveTowardsFacing(double precision = 0)
	{
		// Turn towards direction.
		curChaseAngle = HaloMath.LerpDegrees(curChaseAngle, curDesiredAngle, 0.1);
		A_SetAngle(curChaseAngle, SPF_INTERPOLATE);
	
		// Get angular difference
		double deltaAngle = HaloMath.AngleDiff(angle, curDesiredAngle);
		double diff = clamp(1.0 - (atan2(sin(deltaAngle), cos(deltaAngle)) / 180.), 0, 1.0);
		
		if(diff > precision)
			vel += Quat.FromAngles(angle, 0, 0) * (Speed * diff, 0, 0);
			
		// console.printf("C: %f, D:%f, Diff %f", angle, curDesiredAngle, diff);
	}
	
	void UpdateDesiredAngle(vector3 toPos)
	{
		vector3 diff = level.Vec3Diff(pos, toPos);
		double toAngle = atan2(diff.y, diff.x);
		curDesiredAngle = toAngle;
	}
}

/* Example
class TestImp : HaloDoom_EnemyBase
{
	Default
	{
		Health 60;
		Radius 20;
		Height 56;
		Mass 100;
		Speed 8;
		PainChance 200;
		Monster;
		+FLOORCLIP
		SeeSound "imp/sight";
		PainSound "imp/pain";
		DeathSound "imp/death";
		ActiveSound "imp/active";
		HitObituary "$OB_IMPHIT";
		Obituary "$OB_IMP";
		Tag "$FN_IMP";
	}
	States
	{
		Info.DamageTaken:
			TNT1 A 0 A_JumpIf(A_CheckDamageInfo("HaloShotgun_Bullet", false) && A_GetDamageTaken(killed:true), "Death.Shotgun");
 			TNT1 A 0 A_ResumePrevious();
		goto See;
	
		Spawn:
			TROO AB 10 A_Look;
		Loop;
		See:
			TROO AABBCCDD 3 A_Chase;
		Loop;
		Melee:
		Missile:
			TROO EF 8 A_FaceTarget;
			TROO G 6 A_TroopAttack ;
		Goto See;
		Pain:
			TROO H 2;
			TROO H 2 A_Pain;
		Goto See;
		Death:
			TROO I 8;
			TROO J 8 A_Scream;
			TROO K 6;
			TROO L 6 A_NoBlocking;
			TROO M -1;
		Stop;
		
		Death.Shotgun:
			TNT1 A 0 { console.printf("Shotgun death"); }
		XDeath:
			TROO N 5;
			TROO O 5 A_XScream;
			TROO P 5;
			TROO Q 5 A_NoBlocking;
			TROO RST 5;
			TROO U -1;
		Stop;
		Raise:
			TROO ML 8;
			TROO KJI 6;
		Goto See;
	}
}
*/