class HaloDoom_IntroSeq : HaloMenuBase
{
	// ANImageQueue intros;
	ScreenJobRunner intros;
	double fadeout;
	bool debug;
	
	void AddVideo(String video)
	{
		string vidPath = String.Format("Videos/%s.ivf", video);
		Sound sndPath = String.Format("Videos/%s.ogg", video);
		intros.Append(
			MoviePlayerJob.CreateWithSound(vidPath, sndPath, 0)
		);
	}

	override void Init(Menu parent, ListMenuDescriptor desc)
	{
		Super.Init(parent, desc);
		
		intros = new("ScreenJobRunner");
		intros.Init(true, false);
		
		AddVideo("XSplash");
		AddVideo("BSplash");
		AddVideo("343Splash");
		AddVideo("HDESplash");
		DontDim = true;
		debug = false;
		btn_selected = 0;
	}
	
	override bool OnInputEvent(InputEvent ev)
	{
		if(intros) intros.OnEvent(ev);
		return super.OnInputEvent(ev);
	}
	
	bool IntrosDone()
	{
		return !intros.Validate() || intros.index >= intros.Jobs.Size();
	}
	
	override bool MenuEvent(int mkey, bool fromcontroller)
	{
		switch (mkey)
		{
		case MKEY_Enter:
		case MKEY_Back:
			if(intros) intros.advance = true;
			return true;
		}
		return false;
	}
	
	override void Drawer()
	{
		super.Drawer();
	
		HLSBS.Dim(0xFF000000, 1.0);
		if(fadeout >= 1.0)
		{
			Close();
			SetMenu("MainMenu");
			return;
		}
	
		if(intros) 
		{
			intros.RunFrame(1.0);
			if(IntrosDone()) intros.Destroy();
		}
		else fadeout += 0.1 * deltatime;
		
		if(debug)
		{
			string infostr = String.Format("Fadout: %.2f", fadeout);
			if(intros) infostr = String.Format("Index: %d / %d", intros.index, intros.Jobs.Size());
			HLSBS.DrawString("SmallFont", infostr, (100,100));
			console.printf("%f", fadeout);
		}
	}
	
	override void Ticker()
	{
		if(intros) intros.OnTick();
	}
}

// Animated intros
class Intro_Disclaimer : AnimatedImage
{
	double fade;
	int fadedir;
	
	override void Setup()
	{
		super.Setup();
		fade = 0;
		fadedir = 1.0;
	}
	
	override void Animate(double dt)
	{	
		HLSBS.Dim(Color(255,0,0,0), 1.0);
		if(fadedir > 0)
		{
			fade += 0.02 * dt;
			if(fade >= 3.0) 
			{
				fadedir = -1;
				fade = 1.0;
			}
			HLSBS.DrawImage("Graphics/UI/Title/Splash1.jpg", center, alpha:fade);
		}
		else
		{
			fade -= 0.04 * dt;
			if(fade <= 0) active = false;
			HLSBS.DrawImage("Graphics/UI/Title/Splash1.jpg", center, alpha:fade);
			HLSBS.DrawImage("Graphics/UI/Title/Splash6.jpg", center, alpha:1.0-fade);
		}
	}
}
class Intro_Xbox : AnimatedImage
{
	double fade;
	double whitefade;
	
	override void Setup()
	{
		super.Setup();
		fade = 4.0;
		whitefade = 1.0;
	}
	
	override void Animate(double dt)
	{	
		HLSBS.Dim(Color(255,0,0,0), 1.0);
		
		whitefade -= 0.02 * dt;
		if(whitefade <= 0) fade -= 0.02 * dt;
		if(fade <= -0.5) active = false;
		HLSBS.DrawImage("Graphics/UI/Title/Splash2.jpg", center, alpha:fade);
		HLSBS.DrawImage("Graphics/UI/Title/Splash6.jpg", center, alpha:whitefade);
	}
}
class Intro_Bungie : AnimatedImage
{
	double fade;
	bool fadeout;
	
	override void Setup()
	{
		super.Setup();
		fade = 0;
	}
	
	override void Animate(double dt)
	{	
		HLSBS.Dim(Color(255,0,0,0), 1.0);
		
		if(!fadeout)
			fade += 0.02 * dt;
		else
			fade -= 0.02 * dt;
			
		if(fade >= 5.0) 
		{
			fadeout = true;
			fade = 1.0;
		}
		if(fade <= -0.5 && fadeout) active = false;
		
		HLSBS.DrawImage("Graphics/UI/Title/Splash3.jpg", center, alpha:fade);
		if(fade > 2.0) 
			HLSBS.DrawImage("Graphics/UI/Title/Splash4.jpg", center, alpha:fade-2.0);
		else if(fadeout)
			HLSBS.DrawImage("Graphics/UI/Title/Splash4.jpg", center, alpha:fade);
	}
}
class Intro_HaloDoom : AnimatedImage
{
	double fade;
	bool fadeout;

	override void Setup()
	{
		super.Setup();
		fade = 0;
	}
	
	override void Animate(double dt)
	{	
		HLSBS.Dim(Color(255,0,0,0), 1.0);
		
		if(!fadeout)
			fade += 0.02 * dt;
		else
		{
			fade -= 0.01 * dt;
		}
			
		if(fade >= 4.5) 
		{
			fadeout = true;
			fade = 1.0;
		}
		if(fade <= -0.35) active = false;
		
		HLSBS.DrawImage("Graphics/UI/Title/Splash5.jpg", center, alpha:fade);
	}
}