class Halo_BeamRifle_Battery : Ammo 
{
	Default 
	{
		Inventory.MaxAmount 100;
	}
}

class BeamRifleLaserDecal : LaserBeamDecal
{
	Default
	{
		Translation "0:255=@64[128,8,128]";
	}
}

class LSR_BeamRifle : LaserBeam
{
	int ontime;
	bool turnOff;
	double laserDmg;
	Property LaserDamage : laserDmg;
	Actor prevVictim;

	Default
	{
		Alpha 2.0;
		Scale 1.5;
		LSR_BeamRifle.LaserDamage BEAMRIFLE_DMG;
		LaserBeam.LaserColor "Purple"; 
		LaserBeam.TrackWeapon true, PSP_WEAPON;
		LaserBeam.AimFromWeapon false;
		LaserBeam.LaserDecal "BeamRifleLaserDecal";
		DamageType "Fire";
		+BRIGHT;
	}
	
	override void BeamTick()
	{
		aimAtCrosshair();
		
		if(hitData.results.hitType != TRACE_HitNone) 
			OnImpact(hitData.results.HitPos, hitData.results.hitActor);
	
		if(turnOff)
		{
			alpha -= 0.25;
			A_SetScale(Scale.X * 1.02, Scale.Y);
	
			if(alpha <= 0.1 || Scale.X <= 0.05) Destroy();
		}
	}
	
	override void OnImpact(vector3 hitPos, Actor hitActor)
	{
		super.OnImpact(hitPos, hitActor);
		if(!hitActor) prevVictim = NULL;
		
		if(hitActor && hitActor != source) 
		{	
			if(prevVictim == hitActor) 
				laserDmg = HaloMath.Lerp(laserDmg, default.laserDmg * 5.0, 1.0 / ceil(TICRATE * 0.5));
			else
				laserDmg = default.laserDmg;
				
			hitActor.DamageMobj(self, source, laserDmg, DamageType);
			prevVictim = hitActor;
			
			// Spawn Blood
			if( hitActor.bISMONSTER && !hitActor.bNOBLOOD ) 
				hitActor.SpawnBlood( hitPos, angle, ceil(laserDmg) );
		}

		for(int i = 0; i < floor(3 * halodoom_effectintensity); i++)
		{
			let smoke = Spawn("RisingSmoke", hitData.results.hitPos);
			if(smoke) smoke.A_SetScale(0.25);
		}
	}
}

class LSR_BeamRifleCore : LSR_BeamRifle
{
	Default
	{
		Alpha 2.0;
		Scale 0.75;
		LaserBeam.LaserColor "Pink"; 
	}
	
	override void OnImpact(vector3 hitPos, Actor hitActor) {}
}

class Halo_BeamRifle : HaloGun
{
	double lsrTics;
	LSR_BeamRifle lsrbeam, lsrbeamCore;
	
	Default
	{
		//$Category "HaloDoom/Weapons"
		Weapon.SlotNumber 6;
		Obituary "%o was melted by %k's Beam Rifle.";
		Inventory.PickupMessage	"Picked up the Type-50 Particle Beam Rifle.";
		Tag "Particle Beam Rifle";
		Weapon.BobSpeed 2.45;
		Weapon.BobRangeX 0.45;
		Weapon.AmmoType1 "Halo_BeamRifle_Battery";
		Weapon.AmmoType2 "Halo_BeamRifle_Battery";
		Weapon.AmmoGive 100;
		HaloGun.HasBattery true, 1;
		HaloGun.Faction "Covenant";
		
		HaloGun.PowerTier P_POWER | P_ENERGY;
				
		// Recoil
		HaloGun.Bloom 0.16;
		HaloGun.BloomSpeed 0.30;
		HaloGun.BaseRecoil 1;
		HaloGun.Inaccuracy 1;
		HaloGun.Crosshair "BeamRet", 0.75;
		HaloGun.UIGraphic "WI_BEAM", 0.6, 0.6;
		
		HaloGun.UISight "SI_PBX4", 0.85, 0.5;
		HaloGun.SetupScope 2.0, 1.0;
		
		RecoilWeapon.YOffsetRange 0, 40;
	}
	
	override int GetPowerTier()
	{	
		if(HaloPlayer.IsGameType("SpartanOverkill")) return P_STRONG | P_ENERGY;
		return super.GetPowerTier();
	}
		
	action void A_BeginLaser()
	{
		A_StartSound("Halo/Weapons/BeamRifle/Laser/Fire", CHAN_WEAPON, CHANF_OVERLAP);
		A_Light(2);
		if(!invoker.lsrbeam)
		{
			invoker.lsrbeam = LSR_BeamRifle(LaserBeam.Create(self, 2, 1.5, -1.25, maxDist:BEAMRIFLE_RANGE, type:"LSR_BeamRifle"));
			invoker.lsrbeam.setEnabled(true);
			
			invoker.lsrbeamCore = LSR_BeamRifle(LaserBeam.Create(self, 2, 1.5, -1.25, maxDist:BEAMRIFLE_RANGE, type:"LSR_BeamRifleCore")); 
			invoker.lsrbeamCore.setEnabled(true);
		}
		else
		{
			invoker.lsrbeam.setEnabled(true);
			invoker.lsrbeamCore.setEnabled(true);
		}
		SetupPlasmaLightning(16, -4, 8, scale:0.65, density:3.0, shading:"#d20afa");
	}
	
	action void A_EndLaser(bool dosound = false)
	{
		A_StopSound(CHAN_VOICE);
		if(dosound) A_WeapSound("Halo/Weapons/BeamRifle/Laser/LoopEnd", CHAN_AUTO, CHANF_OVERLAP);
		A_Light(0);
		if(invoker.lsrbeam)
		{
			invoker.lsrbeam.turnOff = true;
			if(invoker.lsrbeamCore) invoker.lsrbeamCore.turnOff = true;
		}
		A_StopPlasmaLightning();
	}
	
	override void OverlayUIFX(RenderEvent ev, double deltaTime)
	{
		vector2 mid = (1920/2.0, 1080/2.0);
		if(zoomed) DrawScopeZoom( mid + (-480, 0), (128,128), 1.25, 1.0);
	}
	
	override void DoEffect()
	{
		super.DoEffect();
		
		heat = clamp(heat, 0, 1.5);
	}
		
	States
	{
		DoSmoke:	
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 3 
			{
				let psp = player.FindPSprite(OverlayID());
				if(psp) psp.frame = random[WeapFX](3,8);
				A_SetSFXPos(25,-8,-10);
				double amt = (invoker.heat * 5) * halodoom_effectintensity;
				
				for(int i = 0; i < floor(amt); i++)
					A_SpawnSFX("MuzzleSmoke", 0,0);
				
				if( invoker.heat >= 0.9 && !(level.maptime%8) ) 	
				{
					let pl = SetupPlasmaLightning(8, -5+random[BRifleRNG](-2,2), 9+random[BRifleRNG](-1,2), scale:0.3, density:2.0, shading:"#fc1717", onlySpawn:true);
					if(pl) pl.lifetime = 35;
				}
			}
		stop;
	
		Ready:
			TNT1 A 0 
			{	
				A_WeapSound("Halo/Weapons/BeamRifle/Draw");
				return A_JumpIf(A_DoFullSelectAnimation(), "Ready.Pickup");
			}
			WLS1 EDCBA 1 A_DoSelectAnim();
		goto Ready.Active;
		Ready.Pickup:
			WLD1 ABCEFGHIJKLMNOPQRSTUVWXYZ 1 A_DoSelectAnim(0, true);
		Ready.Active:
			WLI1 A 1 
			{
				invoker.heat *= 0.96;
				A_HaloWeaponReady(0);
				A_Overlay(69, "DoSmoke");
			}
		loop;
		
		Ready.Dryfire:
			WLI1 A 12 A_WeapSound("Halo/Weapons/DryFire", CHANF_OVERLAP);
		goto Ready.Active;

		Select:
			TNT1 A 0 A_GunRaise();
		wait;

		Deselect:
			TNT1 A 0 A_EndLaser();
			WLS1 ABCDE 1;
			WLS1 E 1 A_GunLower();
		wait;
		
		Fire:
			TNT1 A 0 A_JumpIf(invoker.heat >= 1.0, "Overheat");
			TNT1 A 0 A_JumpIf(!CountLoadedAmmo(), "Ready.Dryfire");
			TNT1 A 0 A_StartSound("Halo/Weapons/BeamRifle/Laser/Begin", CHAN_WEAPON, CHANF_OVERLAP);
			WLF1 ABCD 1 Bright;
			TNT1 A 0 
			{
				A_BeginLaser(); 
				if(!A_CheckInScope())A_SetZoom(0.97, 3);
			}
		Fire.Loop:
			WLF1 CDEFGHICDEFGHICDEFGHICDEFGHICDEFGHICDEFGHIJ 1 Bright // 30 tics
			{
				if(invoker.lsrTics++ >= 4) 
				{
					A_TakeAmmo(1);
					invoker.lsrTics = 0;
					A_StartSound("Halo/Weapons/BeamRifle/Laser/Loop", CHAN_VOICE, CHANF_LOOPING, volume:0.65);
				}
				
				A_AddRecoil(0.008, 0, 2);
				A_RecoilOffset(frandom[WeapFX](-4,4), frandom[WeapFX](-8,8), 2);
				//A_RollQuake(1,10,1);
				A_Light( (!(GetAge()%4)) * 2 );
				invoker.heat += 0.017;
				// A_SetZoom(0.97 + frandom[BMR_RECOIL](-0.02,0.02), 2);
				
				let res = ResolveState(null);
				if(invoker.heat >= 1.0) res = ResolveState("Overheat");
				if(!CountLoadedAmmo()) 
				{
					A_EndLaser();
					res = ResolveState("Ready.DryFire");
				} 
				else if( !invoker.lsrbeam || (A_ButtonStatus(BT_ATTACK, BTS_UP) && invoker.lsrbeam.GetAge() > 8) ) 
				{
					res = ResolveState("Fire.Done");
				}
				
				return res;
			}
			TNT1 A 0 
			{
				A_Light(0);
				if(!A_CheckInScope())A_SetZoom(1.0, 3);
			}
		Fire.Done:
			TNT1 A 0 A_EndLaser();
			WLF1 DEFG 1 A_RecoilOffset(0,0,6);
			TNT1 A 0 
			{
				A_StopSound(CHAN_WEAPON);
				A_StartSound("Halo/Weapons/BeamRifle/Laser/End", CHAN_WEAPON, CHANF_OVERLAP);
			}
			WLF1 HCCDDEEFFGGHHIJ 1 A_RecoilOffset(0,0,6);
			WLI1 A 4;
		goto Ready.Active;
		
		Reload:
		Overheat:
			TNT1 A 0 
			{
				invoker.handsbusy = true; // Disable hand actions while overheating
				A_EndLaser();
				A_RecoilOffset(0,0,6);
				A_SetZoom(1.0, 3);
				return A_JumpIf(invoker.heat < 0.5, "Ready.Dryfire");
			}
			TNT1 A 0 A_WeapSound("Halo/Weapons/BeamRifle/Overheat/Start", CHANF_OVERLAP);
			WLO1 ABCD 1 Bright;
			TNT1 A 0 A_RollQuake(2,35,1);
			TNT1 A 0 A_StartSound("Halo/Weapons/BeamRifle/Overheat/Loop", CHAN_VOICE, CHANF_LOOPING);
			WLO1 DEFGHIJKLMNOPQRRR 2 Bright // 18 frames, or 36 tics.
			{
				for(int i = 0; i < floor(4 * halodoom_effectintensity); i++) 
				{
					A_SetSFXPos(25, -20 + frandom[WeapFX](-8,8), -10 + frandom[WeapFX](-10,10));
					A_SpawnSFX("MuzzleSmoke", 0,0);
				}
				invoker.heat -= 0.1;
			}
			TNT1 A 0 
			{
				A_WeapSound("Halo/Weapons/BeamRifle/Overheat/End", CHANF_OVERLAP);
				A_StopSound(CHAN_VOICE);
			}
			WLO1 ST 4 Bright;
			WLI1 A 2;
			TNT1 A 0 
			{
				invoker.heat = 0;
				invoker.handsbusy = false; // Enable hand actions.
			}
		goto Ready.Active;
					
		Scope.ON:
			TNT1 A 1 
			{
				A_ScopeON();
				A_ResetSightGraphic();
			}
			TNT1 A 5 A_SetZoom(invoker.scopezoom, 3, true);
			TNT1 A 0 
			{
				bool holding = A_ButtonStatus(BT_ALTATTACK, BTS_HELD) && !A_ButtonStatus(BT_ALTATTACK, BTS_PRESSED);
				invoker.zoom_btnstate = holding ? 0 : BTS_PRESSED;
				if(holding) return ResolveState("Scope.Ready");
				return ResolveState("Scope.Wait");
			}
		goto Scope.Wait;
		
		Scope.Two:
			TNT1 A 1 A_ScopeON();
			TNT1 A 5 A_SetZoom(invoker.scopezoom * 1.5, 3, true);
		goto Scope.Ready;
		
		Scope.Wait:
			TNT1 A 1 
			{
				State ret = ResolveState(null);
				if(!invoker.enablezoom) ret = ResolveState("Scope.OFF");
				if(A_ButtonStatus(BT_ALTATTACK, BTS_PRESSED)) ret = ResolveState("Scope.Two");
				return ret;
			}
		loop;
	
		Spawn:
			WLP1 A -1;
		stop;
	}
}
