
class Halo_BinaryRifleMag : Ammo 
{
	Default 
	{
		Inventory.MaxAmount 2;
	}
}
class Halo_BinaryRifle_Reserves : Ammo
{
	mixin WorldAmmoBehavior;
	Default 
	{
		Radius 0;
		Height 0;
		Scale 0.65;

		Inventory.Amount 12;
		Inventory.MaxAmount 12;
		Inventory.Icon "";
		Inventory.PickupSound "";
		Inventory.PickupMessage "";
		Ammo.BackpackMaxAmount 16;
	}
	
	States
	{
		Spawn:
			TNT1 A -1;
		stop;
	}
}

class Halo_BinaryRifleBattery : Ammo 
{
	Default
	{
		Inventory.MaxAmount 100;
	}
}

class LSR_BinaryRifle : LSR_UnmakerBeam
{
	double fadeAmt;
	double hitDmg;
	Property LaserDamage : hitDmg;
	Property LaserFade : fadeAmt;

	Default
	{
		Alpha 2.0;
		Scale 8.0;
		LaserBeam.LaserColor "#00FF94"; 
		LaserBeam.TrackWeapon true, PSP_WEAPON;
		LaserBeam.AimFromWeapon false;
		LSR_BinaryRifle.LaserDamage BINARYRIFLE_DMG;
		LSR_BinaryRifle.LaserFade 0.10;
		LSR_UnmakerBeam.LaserPuff "BinaryRiflePuff";
		Translation "0:255=@64[0,255,148]";
		+BRIGHT;
	}
	
	override void BeamTick()
	{	
		if(GetAge() < 2) 
			aimAtCrosshair();

		alpha -= fadeAmt;
		A_SetScale(Scale.X * 0.87, Scale.Y);
	
		if(alpha <= 0.1 || Scale.X <= 0.05) Destroy();
	}
	
	override void OnImpact(vector3 hitPos, Actor hitActor)
	{	
		super.OnImpact(hitPos, hitActor);
		let puff = UnmakerLaserPuff(Spawn(puffType, hitPos));
		if(puff) 
		{
			startTracking(hitPos);
			if(lowEffects) puff.laserAmt = 0;
			puff.translation = translation;
			puff.angle = angle + 180;
			puff.pitch = -(pitch-90);
		}
		
		Spawn("LargeSplashSpawner", hitPos);
		if(hitActor) hitActor.DamageMobJ(self, source, hitDmg, "Fire");
	}
}
class LSR_BinaryRifleCore : LSR_BinaryRifle
{
	Default
	{
		Alpha 2.0;
		Scale 4.0;
		LaserBeam.LaserColor "White"; 
		LaserBeam.TrackWeapon true, PSP_WEAPON;
		LaserBeam.AimFromWeapon false;
		+BRIGHT;
	}
	
	override void OnImpact(vector3 hitPos, Actor hitActor) 
	{
		startTracking(hitPos);
	}
}
class BinaryRiflePuff : UnmakerLaserPuff
{
	Default
	{
		UnmakerLaserPuff.laserPuffs 6, 100, 0.25;
		Translation "0:255=@64[0,255,148]";
		UnmakerLaserPuff.LightningType "BinaryRifle_Lightning";
	}
}
class BinaryRifle_Lightning : LightningBiri
{
	Default
	{
		Translation "0:255=@64[0,255,148]";	
	}
}

class Halo_BinaryRifle : HaloGun
{
	Default
	{
		//$Category "HaloDoom/Weapons"
		Weapon.SlotNumber 5;
		Obituary "%o was disintegrated by %k's Binary Rifle.";
		Inventory.PickupMessage	"Picked up the Binary Rifle.";
		Tag "Binary Rifle";
		Weapon.BobSpeed 2.45;
		Weapon.BobRangeX 0.63;
		Weapon.AmmoType1 "Halo_BinaryRifle_Reserves";
		Weapon.AmmoType2 "Halo_BinaryRifleMag";
		Weapon.AmmoGive 21;
		HaloGun.Faction "Forerunner";
		
		HaloGun.PowerTier P_POWER;
		HaloGun.Rarity 10;
				
		// Recoil
		RecoilWeapon.RecoilSpeed 20;
		HaloGun.Bloom 1.25;
		HaloGun.BloomSpeed 0.08;
		HaloGun.BaseRecoil 1;
		HaloGun.Inaccuracy 1;
		HaloGun.Crosshair "BiRet", 1.0;
		HaloGun.UIGraphic "MISSNG", 0.8, 0.7;
		
		HaloGun.UISight "BINADS00", 1.25, 1.0;
		HaloGun.SetupScope 2.0, 0.5;
		+HaloGun.SI_Fullscreen;
		+HaloGun.SI_Rotate;
		+HaloGun.SI_AlwaysHide;
		
		HaloGun.ZoomSounds "Halo/Weapons/BinaryRifle/Zoom/IN", "Halo/Weapons/BinaryRifle/Zoom/OUT";
		//hudAmmo_graphic, hudAmmo_xSpacing, hudAmmo_ySpacing, hudAmmo_XMax, hudAmmo_YMax;
		HaloGun.SetupUIAmmo "WI_AMM6", 48, 16, 2, 0;
		HaloGun.UIAmmo_Scale_Offset 1.5, 100, 0;
		
		RecoilWeapon.YOffsetRange 0, 40;
		Scale 0.5;
	}
	
	override int GetPowerTier()
	{	
		if(HaloPlayer.IsGameType("SpartanOverkill")) return P_MID;
		return super.GetPowerTier();
	}
	
	action void A_FireBinaryRifle(double ud = 0)
	{
		A_Light(4);
		A_WeapSound("Halo/Weapons/BinaryRifle/Fire", CHANF_OVERLAP, true);
		A_WeapSound("Halo/Weapons/BinaryRifle/Fire/Bass", CHANF_OVERLAP, true);
		
		double lr = A_CheckInScope() ? 0 : 2;
		let beam = LaserBeam.Create(self, 7, lr, -2 + ud, type:"LSR_BinaryRifle");
		let beamCore = LaserBeam.Create(self, 7, lr, -2 + ud, type:"LSR_BinaryRifleCore");
		
		beam.setEnabled(true);
		beamCore.setEnabled(true);
		
		let pl = SetupPlasmaLightning(16, A_CheckInScope() ? 0 : -4, 9, scale:1.0, density:3.0, shading:"#00ff94", replace:true);
		if(pl) pl.lifetime = 16;
		
		A_TakeAmmo(1);
		A_UpdateSpread();
	}

	States
	{
		
		Ready:
			TNT1 A 0 
			{
				A_WeapSound("Halo/Weapons/BinaryRifle/Draw");
				return A_JumpIf(A_DoFullSelectAnimation(), "Ready.Chamber");
			}
			WOS1 ABCDEFG 1 A_DoSelectAnim();
		goto Ready.Active;
		Ready.Chamber:
			WOD1 ZYXWVUTSRQPONMLKJIHGFEDCBA 1 A_DoSelectAnim(0, true);
		Ready.Active:
			WOI1 A 1 
			{
				A_HaloWeaponReady(WRF_ALLOWRELOAD, usescope:true);
				if(A_CheckInScope()) A_ResetSightGraphic();
				A_StopPlasmaLightning();
			}
		loop;
		
		Ready.Dryfire:
			WOI1 A 4 A_WeapSound("Halo/Weapons/DryFire", CHANF_OVERLAP);
		goto Ready.Active;

		Select:
			TNT1 A 1 A_GunRaise();
		wait;

		Deselect:
			WOS1 GFEDCBA 1;
			WOS1 A 1 A_GunLower();
		wait;
		
		Fire:
			TNT1 A 0 A_GunCheckReload();
			WOF1 A 1 Bright;
			WOF1 B 1 Bright
			{
				A_SetZoom(0.90, 2);
				if(A_CheckInScope()) 
				{
					A_SetSightGraphic("BINADS01");
					A_FireBinaryRifle(-2);
					if(CountLoadedAmmo()) 
						A_FireBinaryRifle(2);
				}
				else
				{
					A_FireBinaryRifle();
				}
				A_RecoilOffset(random[WeapFX](-12,12),12,3);
				A_RollQuake(4, 10, 2);
			}
			TNT1 A 0 A_SetRecoil(4.20, 2.40, 2);
			WOF1 CD 1 Bright;
			WOF1 E 1 Bright 
			{
				A_SetZoom(1.0, 8);
				A_Light(0);
			}
			WOF1 EFG 1 A_SetZoom(1.0, 8);
			WOF1 HIJKLM 2;
			WOI1 A 20;
		goto Ready.Active;
		
		Reload:
			TNT1 A 0 A_ValidateReload("Ready.Dryfire");
			TNT1 A 0 
			{
				A_StartSound("Halo/Weapons/BinaryRifle/Reload/Background", CHAN_RELOADING, CHANF_OVERLAP);
				A_StartSound("Halo/Weapons/BinaryRifle/Reload/Start", CHAN_RELOADING, CHANF_OVERLAP);
			}
			WOR1 ABCDDDEFF 2;
		Reload.Loop:
			TNT1 A 0 A_StartSound("Halo/Weapons/BinaryRifle/Reload/Single", CHAN_RELOADING, CHANF_OVERLAP);
			WOR1 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 2 
			{
				// 122 tics...
				A_RecoilOffset(frandom[ScShake](-3,3), frandom[ScShake](-3,3), 2, add:true);
				
				bool doAbortReload = (CountLoadedAmmo() && A_ButtonStatus(BT_ATTACK, BTS_DOWN));
				if(doAbortReload) A_StopSound(CHAN_RELOADING);
				return A_JumpIf(doAbortReload, "Ready.Active");
			}
			TNT1 A 0 A_ReloadAmount(1);
			TNT1 A 0 A_ValidateReload("Reload.Finish");
			TNT1 A 0 A_GotoState("Reload.Loop");
		Reload.Finish:
			TNT1 A 0 
			{
				A_StopSound(CHAN_RELOADING);
				A_StartSound("Halo/Weapons/BinaryRifle/Reload/End", CHAN_RELOADING);
			}
			WOR1 FEDCBA 2 A_RecoilOffset(0,0,12);
		goto Ready.Active;
		
		Spawn:
			WOP1 A -1;
		stop;
	}
}
