
class Halo_BoltshotBattery : Ammo 
{
	Default
	{
		Inventory.MaxAmount 100;
	}
}

class HaloBoltShot_Proj : HaloProjectile 
{
	double trackTics;
	vector3 trackingPos;
	Actor trackingVictim;

	Default
	{
		HaloProjectile.SetRanges 0, 0;
		HaloProjectile.MinRangeDamage 0; 
		HaloProjectile.BaseDamage BOLTSHOT_DMG; 
		HaloProjectile.Speed_MPS  BOLTSHOT_BMPS;
		HaloProjectile.HeadshotDMGFactor BOLTSHOT_HEDMOD;
		
		Radius 4;
		Height 4;
		RenderStyle "Add";
		Translation "0:255=@75[5,44,240]";
		Alpha 1.0;
		Scale 0.01;
		DamageType "Plasma";
		+ROLLSPRITE;
		+INTERPOLATEANGLES;
	}
	
	override void Tick()
	{
		super.Tick();
		if(level.isFrozen()) return;
		
		A_SetRoll(roll+5, SPF_INTERPOLATE);
		
		Spawn("HaloBoltShot_Trail", pos);
		
		if(trackTics)
		{
			vel *= 0;
			SetOrigin(trackingPos, false);
			SpecialMissileHit(trackingVictim);
			ExplodeMissile(target:trackingVictim);
			bMISSILE = false;
		}
	}
	
	States
	{
		Spawn:
			ELBL AB 2 Bright A_JumpIf(!bMISSILE || vel.length() == 0, "Death");
		loop;
		
		Death:
		XDeath:
		Crash:
			TNT1 A 1 
			{	
				HaloMath.ParticlesFX(self, "Blue", 30, 3, 10);
			}
		stop;
	}
}

class HaloBoltShot_Trail : CheapActor
{
	Default
	{
		RenderStyle "Add";
		Translation "0:255=@75[5,44,240]";
		Alpha 1.0;
		Scale 0.02;
		+ROLLSPRITE;
		+INTERPOLATEANGLES;
		+NOGRAVITY;
	}
	
	override void Tick()
	{
		super.Tick();
		A_SetRoll(roll+5, SPF_INTERPOLATE);
		A_SetScale(Scale.X * 0.93);
		alpha *= 0.93;
		if(alpha <= 0.05) Destroy(); 
	}
	
	States
	{
		Spawn:
			ELBL AB 2 Bright;
		loop;
	}
}

class BoltShotBeamSpawner : MBeamSpawner
{
	double lockPerc;
	
	override void Setup()
	{
		jitterAngle = 0;
		jitterPitch = 0;
		beamAlpha = 0;
		bobWithWeapon = true;
		doTrackPos = true;
		DontSpawnParticles = true;
		SegClass = "BoltShotBeamSegment";
		SetupVisuals("274cf2", "4769ff", 0.45, 0.17);
	}
	
	override void BeamTick()
	{
		beamAlpha = clamp(beamAlpha, 0, 1.0);
		if(!beamTarget) 
		{
			if(beamAlpha > 0) beamAlpha -= 0.1;
			return;
		}
		
		// trackingPos = src.pos + Quat.FromAngles(src.angle, src.pitch, src.roll) * (100,0, src.player.viewz-src.pos.z);
		trackingPos = (beamTarget.pos.xy, beamTarget.pos.z + (beamTarget.height * 0.9));
		beamAlpha = lockPerc;
	}
	
	override bool DoMBeamDecal(class<LaserBeamDecal> decalType, bool puffOnActors)
	{
		return false;
	}
}

class BoltShotBeamSegment : MBeamSegment
{
	Default
	{
		MBeamSegment.Core "";
	}
}

class Halo_BoltShot : HaloGun
{
	int burstCounter, beamCounter;
	double targetLockPerc[3];
	Actor targetList[3];
	
	Array<BoltShotBeamSpawner> beams;

	Default
	{
		//$Category "HaloDoom/Weapons"
		Weapon.SlotNumber 3;
		Obituary "%o's was sublimated by %k's Bolt Shot.";
		Inventory.PickupMessage	"Picked up the Bolt Shot.";
		Tag "Bolt Shot (Feature Demo)";
		Weapon.BobSpeed 0.8;
		Weapon.BobRangeX 0.50;
		Weapon.BobSpeed 2.45;
		Weapon.AmmoType1 "Halo_BoltshotBattery";
		Weapon.AmmoType2 "Halo_BoltshotBattery";
		Weapon.AmmoGive 100;
		HaloGun.HasBattery true, 1;
		HaloGun.Faction "Forerunner";
		
		HaloGun.PowerTier P_MID;
		HaloGun.Rarity 0; // Debug - Will not spawn until completed.
				
		// Recoil
		HaloGun.Bloom 0.8;
		HaloGun.BloomSpeed 0.35;
		HaloGun.BaseRecoil 1;
		HaloGun.Inaccuracy 1;
		HaloGun.Crosshair "BoltRet1", 0.7;
		HaloGun.UIGraphic "MISSNG", 0.8, 0.7;
		
		/*
		HaloGun.UISight "SCSGADS", 1.5, 1.0;
		HaloGun.SetupScope 1.25, 0.5;
		+HaloGun.SI_Fullscreen;
		+HaloGun.SI_Rotate;
		+HaloGun.SI_AlwaysHide;
		
		HaloGun.ZoomSounds "Halo/Weapons/ScatterShot/Zoom/IN", "Halo/Weapons/ScatterShot/Zoom/OUT";
		*/

		RecoilWeapon.YOffsetRange 0, 40;
	}
		
	override int GetPowerTier()
	{	
		if(HaloPlayer.IsGameType("SpartanOverkill")) return P_NORM;
		return super.GetPowerTier();
	}
	
	override void OverlayUIFX(RenderEvent e, double dT)
	{
		bool hasTarget = targetList[0] || targetList[1] || targetList[2];
		if(!hasTarget) return;
		
		HLViewProjection viewproj = HLSBS.GetEventViewerProj(e);
		
		for(int i = 0; i < 3; i++)
		{
			Actor pTarget = targetList[i];
			if(!pTarget) continue;
		
			bool infront, edgefront;
			vector2 apos_mid, apos_HDL, apos_HDR;
			[infront, apos_mid] = HLSBS.GetActorHUDPos (
				viewproj, pTarget, 0, 0, pTarget.height*0.5
			);
			
			double converge = targetLockPerc[i];			
			double toHeight_Top = pTarget.height - 5;
			double conOffs = ((1.0 - converge) / 1.0) * 15;
			double conAlpha = converge / 1.0;
			
			[edgefront, apos_HDR] = HLSBS.GetActorHUDPos (
				viewproj, pTarget, -conOffs, 0, toHeight_Top
			);
			[edgefront, apos_HDL] = HLSBS.GetActorHUDPos (
				viewproj, pTarget, conOffs, 0, toHeight_Top
			);
			
			// Draw locked-on graphic.
			if(infront) 
			{	
				Color shade = converge >= 0.9 ? 0xFFA00000 : 0;
				HLSBS.DrawImage("Graphics/UI/Reticles/BoltRet2_Left.png", apos_HDL, alpha:conAlpha, scale:(0.6, 0.6), tint:shade, absolute:true);
				HLSBS.DrawImage("Graphics/UI/Reticles/BoltRet2_Right.png", apos_HDR, alpha:conAlpha, scale:(0.6, 0.6), tint:shade, absolute:true);
			}
		}
	}
	
	action void A_FireBoltShot()
	{
		A_Light(4);
		A_WeapSound("Halo/Weapons/BoltShot/Fire", CHANF_OVERLAP);
		A_WeapSound("Halo/Weapons/BoltShot/Fire/Bass", CHANF_OVERLAP);
		
		let pl = SetupPlasmaLightning(16, -6, 8, scale:0.67, density:2.0, shading:"#2c72f5");
		if(pl) pl.lifetime = 16;
		
		let [vec, proj] = A_ShootProjectile("HaloBoltShot_Proj", 7, -2);
			
		// Fire at locked target.
		int useTarget = -1;
		bool hasTarget = A_CheckHasTarget();
		
		if(hasTarget)
		{
			while(useTarget < 0)
			{
				for(int i = invoker.beamCounter; i < 3; i++)
				{
					if(invoker.targetLockPerc[i] >= 0.90) 
					{
						useTarget = i;
						invoker.beamCounter = i;
						break;
					}
				}
				if(useTarget < 0) invoker.beamCounter = 0;
			}
		}
		
		if(useTarget >= 0 && invoker.targetList[useTarget])
		{
			let boltProj = HaloBoltShot_Proj(proj);
			boltProj.vel *= 0;
			boltProj.ricochetChance = 0;
			boltProj.trackingPos = invoker.beams[useTarget].trackingPos;
			boltProj.trackTics = 1; //max(1, HaloMath.Distance3D(proj.pos, boltProj.trackingPos) / boltProj.getSpeed());
			boltProj.trackingVictim = invoker.targetList[useTarget];
			invoker.beamCounter = (invoker.beamCounter+1) % 3;
		}
		
		A_TakeAmmo(1);
		A_UpdateSpread();
	}
	
	void UpdateBeams()
	{
		// Find targets for beams, process target lock, etc.
		for(int i = 0; i < 3; i++)
		{
			let beam = beams[i];
			if(!beam)
			{
				beams.Clear();
				return;
			}
	
			beam.beamTarget = targetList[i];
			beam.lockPerc = targetLockPerc[i];
		}
	}
	
	bool CheckValidTarget(int index, Actor pTarget, double maxRange = 1024)
	{
		// Failsafe
		if(!pTarget || pTarget == Owner) return false;
		
		// Dead?
		if(pTarget.health <= 0 || pTarget.bCORPSE || !pTarget.bSHOOTABLE) return false;
	
		// Can't see?
		if(!Owner.CheckSight(pTarget, SF_SEEPASTBLOCKEVERYTHING)) return false;
		
		// Janky-ass code to check if the target is behind the camera, or close to.
		vector3 targetDir = level.vec3diff(Owner.pos, pTarget.pos).Unit();
		double angleDiff = abs(HaloMath.AngleDiff(Owner.angle, atan2(targetDir.y, targetDir.x)));
		if(angleDiff >= 40) return false;
		
		// Too far?
		double dist = pTarget.Distance3DSquared(Owner);
		if(dist > maxRange*maxRange) return false;
	
		// Already targetted?
		for(int i = 0; i < 3; i++)
		{
			if(i == index) continue;
			if(targetList[i] == pTarget) return false;
		}
		
		// Passed all checks!
		return true;
	}
	
	void GetTargets()
	{
		let haloplr = HaloPlayer(Owner);
		
		for(int i = 0; i < 3; i++)
		{
			let curTarget = targetList[i];
			if(curTarget && !CheckValidTarget(i, curTarget)) 
				curTarget = targetList[i] = NULL;
			
			if(curTarget)
				targetLockPerc[i] = HaloMath.Lerp(targetLockPerc[i], 1.0, 0.1);
			else
			{
				// Look for closest target, taking into account closest aim position.
				targetLockPerc[i] = 0;
				double closest = double.infinity;
				let it = BlockThingsIterator.Create(Owner, 2048);
				while(it.Next())
				{	
					let act = it.Thing; 
					if(!CheckValidTarget(i, act)) continue;
					
					vector3 toPos = (act.pos.xy, act.pos.z + (act.height*0.5));
					vector3 toAngles = level.SphericalCoords((Owner.pos.xy, Owner.player.viewz), toPos, (Owner.angle,Owner.pitch));

					double angTo = toAngles.x;
					double pitTo = toAngles.y;				
					
					double aimTo = abs(angTo) + abs(pitTo);
					double distTo = toAngles.z;
					double dist = aimTo + (distTo * 0.25);  
					if(dist <= closest)
					{
						closest = dist;
						targetList[i] = act;
					}
				}
			}
		}
	}
	
	override void DoEffect()
	{
		super.DoEffect();
		let haloplr = HaloPlayer(Owner);
		if(!haloplr || !Owner.player) return;
		
		bool isCurrentWeapon = (Owner.player.ReadyWeapon == self);
		
		if(!isCurrentWeapon) 
		{
			if(beams.Size() > 0)
			{
				for(int i = beams.Size()-1; i >= 0; i--)
					beams[i].Destroy();
				beams.Clear();
			}
			
			return;
		} 
		
		if(!beams.Size())
		{
			// Populate beams
			vector3 beamOffs = (7, -3.75, -4);
			for(int i = 0; i < 3; i++)
			{
				let beam = BoltShotBeamSpawner(
					MBeamSpawner.Create(Owner, 
						beamOffs.x, beamOffs.y, beamOffs.z, 0, 
						spawnerType:"BoltShotBeamSpawner"
					)
				);
				beam.Enable(null);
				beams.Push(beam);
			}
			return;
		}
		else
		{
			UpdateBeams();
			GetTargets();
		}
	}
	
	action bool A_CheckHasTarget()
	{
		return invoker.targetLockPerc[0] >= 0.9 || invoker.targetLockPerc[1] >= 0.9 || invoker.targetLockPerc[2] >= 0.9;
	}
	
	action bool CheckCanFire()
	{
		return A_CheckHasTarget() && CountLoadedAmmo();
	}

	action void A_ResetFire()
	{
		invoker.burstCounter = invoker.beamCounter = 0;
	}

	States
	{
		
		Ready:
			TNT1 A 0 A_WeapSound("Halo/Weapons/BoltShot/Draw");
			G2S1 EDCBA 1 A_DoSelectAnim();
		Ready.Active:
			G2G1 A 1 
			{
				A_HaloWeaponReady();
				A_StopPlasmaLightning();
			}
		loop;
		
		Ready.Dryfire:
			G2G1 A 4 
			{
				A_ResetFire();
				A_WeapSound("Halo/Weapons/DryFire", CHANF_OVERLAP);
			}
		goto Ready.Active;

		Select:
			TNT1 A 1 A_GunRaise();
		wait;

		Deselect:
			G2S1 ABCD 1;
			G2S1 E 1 A_GunLower();
		wait;
		
		Fire:
			G2F1 A 1 A_ResetFire();
		Fire.Burst:
			TNT1 A 0 A_JumpIf(!CheckCanFire(), "Ready.Dryfire");
			G2F1 B 1 Bright;
			G2F1 C 1 Bright
			{
				A_SetZoom(0.98, 2);
				A_SetRecoil(0.7, 0, 2);
				A_FireBoltShot();
				//A_RollQuake(3,6,2);
				A_RecoilOffset(frandom[BLFX](3,7), frandom[BLFX](3,7), 2);
			}
			G2F1 DE 1
			{
				A_Light(0);
				A_SetZoom(1.0, 2);
				A_RecoilOffset(0,0,2);	
			}
			G2F1 F 1 A_JumpIf(++invoker.burstCounter < 3, "Fire.Burst");
		Fire.Cooldown:
			G2G1 A 8;
		goto Ready.Active;
		
		Spawn:
			WQP1 A -1;
		stop;
	}
}

/*
if(trackTics > 0)
{
	vector3 trackAngles = level.sphericalCoords(pos, trackingPos, (angle, pitch));
	vector3 targetDir = level.vec3diff(pos, trackingPos);
	double perc = clamp(GetAge() / trackTics, 0, 1.0);

	if(trackTics <= 3)
	{
		vel *= 0;
		SetOrigin(trackingPos, false);
		SpecialMissileHit(trackingVictim);
		bMISSILE = false;
	}
	
	angle -= trackAngles.x * perc;
	pitch -= trackAngles.y * perc;
	
	if(getAge() > trackTics) 
	{
		vel *= 0;
		bMISSILE = false;
	}
	
	vel = Quat.FromAngles(angle, pitch, 0) * (getSpeed(), 0, 0);
}
*/
