class Halo_CarbineClip : Ammo 
{
	Default 
	{
		Inventory.MaxAmount 18;
	}
}
class Halo_CarbineReserves : Ammo
{
	mixin WorldAmmoBehavior;
	Default 
	{
		Radius 8;
		Height 6;
		Scale 0.65;

		Inventory.Amount 18;
		Inventory.MaxAmount 72;
		Inventory.Icon "HLAME0";
		Inventory.PickupSound "Halo/Pickup/Ammo";
		Inventory.PickupMessage "Picked up 18 Rounds for the Carbine";
		
		Ammo.BackpackMaxAmount 144;
	}
	
	States
	{
		Spawn:
			HLAM E -1 Bright;
		stop;
	}
}

class HaloCarbine_Bullet : HaloBullet 
{
	Default
	{
		HaloProjectile.SetRanges CARBINE_RANGE1, CARBINE_RANGE2;
		HaloProjectile.MinRangeDamage CARBINE_MINDMG; 
		HaloProjectile.BaseDamage CARBINE_DMG;
		HaloProjectile.Speed_MPS CARBINE_BMPS;
		HaloProjectile.HeadshotDMGFactor CARBINE_HEDMOD;
		HaloProjectile.ShieldDamageFactors 0.75, 0.75;
		HaloProjectile.RicochetChance 0;
		
		DamageType "Fire";
	}
	
	States
	{
		Death:
			TNT1 A 1
			{
				for(int i = 0; i < 10; i++)
				{
					double sAngle = frandom[WeapFX](-30,30);
					double sPitch = frandom[WeapFX](-30,30);
					vector3 offs = (
						frandom[WeapFX](-15,15),
						frandom[WeapFX](-15,15),
						frandom[WeapFX](-15,15)
					);
					
					vector3 pvel = (
						cos(angle+sAngle),
						sin(angle+sAngle),
						sin(pitch+sPitch)
					) * -frandom[WeapFX](4,10);
					A_SpawnParticle(0x11f220, SPF_FULLBRIGHT|SPF_RELPOS, 10, 5, sAngle, offs.x, offs.y, offs.z, pvel.x, pvel.y, pvel.z);
				}
			}
		stop;
	}
}


class Halo_Carbine : HaloGun
{
	const LCD = 22;
	vector2 lcd_offs;
	ui double sightAmmo;

	Default
	{
		//$Category "HaloDoom/Weapons"
		Weapon.SlotNumber 4;
		Obituary "%o was took down by %k's Carbine.";
		Inventory.PickupMessage	"Picked up the Type-51 Carbine.";
		Tag "Carbine";
		Weapon.BobSpeed 2.45;
		Weapon.BobRangeX 0.30;
		Weapon.AmmoType1 "Halo_CarbineReserves";
		Weapon.AmmoType2 "Halo_CarbineClip";
		Weapon.AmmoGive 36;
		HaloGun.Faction "Covenant";
		
		HaloGun.PowerTier P_ENERGY | P_STRONG;
		HaloGun.Rarity 60;

		// Recoil
		HaloGun.Bloom 0.32;
		HaloGun.BloomSpeed 0.18;
		HaloGun.BaseRecoil CARBINE_RECOIL;
		HaloGun.Inaccuracy CARBINE_ACCMOD;
		HaloGun.Crosshair "CarbRet", 0.8;
		HaloGun.UISight "SI_CARB", 1.1, 1.0;
		HaloGun.SetupScope 2.0, 0.5;
		HaloGun.UIGraphic "WI_CARB", 0.4, 0.4;
		HaloGun.ZoomSounds "Halo/Weapons/Zoom/IN", "Halo/Weapons/Zoom/OUT";
		+HaloGun.SI_Fullscreen;
		+HaloGun.SI_Rotate;
		+HaloGun.SI_AlwaysHide;
		
		RecoilWeapon.YOffsetRange 0, 40;
	}
	
	// For sight effects 
	override void OverlayUIFX(RenderEvent e, double dT)
	{
		if(!zoomed) return; // Do not draw if not in sight.
		
		int drawFlags = HLSBS.SS_SCREEN_CENTER | HLSBS.SS_NOASPECTCORRECTION;
		double sightScale = 0.50;
		vector2 drawPos = (130,525);
		double rotation = 0;
		
		if(bSI_Rotate && Owner.player)
		{
			let weapPSP = Owner.player.GetPSprite(PSP_WEAPON);
			if(weapPSP) rotation = weapPSP.rotation * 0.5;
		}
		drawPos.x += sin(rotation * 2.0) * 128;
		
		let curAmmo = GetDefaultByType(AmmoType2);
		double ammoPerc = Owner.countinv(AmmoType2) / double(curAmmo.maxamount);
		sightAmmo = HaloMath.lerp(sightAmmo, ammoPerc, 0.25 * dT);
		
		double fullColorHue = 0.3333333; // One third
		Color sightColor = HLStatusColor.HSLtoRGB(ammoPerc > 0 ? fullColorHue : 0, 1.0, 0.5);
		
		string dir = "Graphics/UI/Sights/Carbine_LCD";
		string circleGraphic = String.Format("%s/SI_CARB_Main.png", dir); 
		string chargeMeterGraphic = String.Format("%s/SI_CARB_AC.png", dir);
		string chargeMeterOuter = String.Format("%s/SI_CARB_ACO.png", dir);
		
		HLSBS.DrawImage(circleGraphic, drawPos, flags:drawFlags, scale:(sightScale,sightScale), rotation:rotation, tint:sightColor);
		
		// Meter - Inner
		HLSBS.DrawImage(chargeMeterGraphic, drawPos, flags:drawFlags, alpha:0.75, scale:(sightScale,sightScale), rotation:rotation, tint:0xFFFF0000);
		
		Screen.EnableStencil(true);
		Screen.SetStencil(0, SOP_Increment, SF_AllOn);

		vector2 clipPos = ((1920.0, 1080.0) * 0.5) + drawPos + ((-250, -250 + 32) * sightScale);
		double radius = 232 * sightScale;
		HLSBS.DrawPartialCircle(
			clipPos, radius, 0xFF00FF00,
			fillpercent:sightAmmo * 0.5, alpha:0,
			rotation: rotation,
			flipx:true
		);
		Screen.SetStencil(1, SOP_Keep, SF_AllOn);
		
		HLSBS.DrawImage(chargeMeterGraphic, drawPos, flags:drawFlags, alpha:0.75, scale:(sightScale,sightScale), rotation:rotation, tint:sightColor);
		Screen.EnableStencil(false);
		Screen.ClearStencil();
		
		// Meter - Outer
		HLSBS.DrawImage(chargeMeterOuter, drawPos, flags:drawFlags, scale:(sightScale,sightScale), rotation:rotation, tint:0xFF545454);
	}
	
	override void MarkPrecacheSounds()
	{
		// Prevent stutters by precaching weapon sounds.
	}
	
	action void FireLaser(vector3 hitpos)
	{
		vector3 localOffs = (10, A_CheckInScope() ? -1.0 : 2.0, -3.0);
		A_SetSFXPos(localOffs.x, localOffs.y, localOffs.z);
		
		double yoffs = A_GetWeapYOffs() * 0.25;

		let beam = LaserBeam.Create(self, localOffs.x,localOffs.y,localOffs.z, type:"LSR_CarbineTrail");
		beam.SetEnabled(true);
	}
	
	action state A_CheckRapidFire()
	{
		return A_JumpIf(A_FirePressed(), "Fire");
	}
	
	action void A_FireCarbine()
	{
		A_LCDOffset(10,-2);
		A_WeapSound("Halo/Weapons/Carbine/Fire", CHANF_OVERLAP);
		A_WeapSound("Halo/Weapons/Carbine/Fire/Bass", CHANF_OVERLAP);
		vector3 shootpos = A_ShootProjectile("HaloCarbine_Bullet", 1, 0);
		A_SetSFXPos(25,-5, -5);
		
		FireLaser(shootpos);

		/*
		let trail = A_TrailSFX(shootpos, 1.25, 0x11f220);
		if(trail) 
		{
			trail.A_SetScale(2.0);
			trail.fadespd = 0.30;
		}
		*/
					
		A_TakeAmmo(1);
		A_UpdateSpread();
	}
	
	action void A_DisableLCD()
	{
		A_Overlay(LCD, "LCD_Off");
	}
	
	action void A_ReloadSound()
	{
		Sound reload_snd = "Halo/Weapons/Rifle/Reload/Full";
		if(!CountLoadedAmmo()) reload_snd = "Halo/Weapons/Rifle/Reload/Empty";
		A_StartSound(reload_snd, CHAN_RELOADING, CHANF_OVERLAP);
	}
	
	action void A_LCDOffset(double x, double y)
	{
		invoker.lcd_offs = (x,y);
	}
	
	States
	{
		// W6 namespace
		DoSmoke:	
			TNT1 AAAA 3 
			{
				let psp = player.GetPSprite(OverlayID());
				if(psp) psp.frame = random[WeapFX](3,8);
				A_SetSFXPos(25,-5,-7);
				for(int i = 0; i < random[WeapFX](1,5); i++)
				{
					let smk = PlasmaSmoke_Green(A_SpawnSFX("PlasmaSmoke_Green", 0,0));
					if(smk) 
					{
						smk.vel = (frandom[WeapFX](-1,1),frandom[WeapFX](-1,1),frandom[WeapFX](-1,1)) * 0.2;
						smk.scaleMod = 0.5;
					}
				}
			}
 		stop;
	
		Ready:
			TNT1 A 0 
			{
				A_WeapSound("Halo/Weapons/Carbine/Select");
				return A_JumpIf(A_DoFullSelectAnimation(), "Ready.Load");
			}
			// Quicker select animation
			W6S1 FEDCBA 1 A_DoSelectAnim();
		goto Ready.Active;
		
		Ready.Load:
			W6D1 ABCDEFGHIJKLMNOPQRSTUVWXYZ 1 A_DoSelectAnim(0, true);
			W6D2 ABCDEFGHIJKLMNOPQRSTUVWXY 1 A_DoSelectAnim(0, true);
		Ready.Active:
			W6I1 A 1 
			{
				A_HaloWeaponReady(WRF_ALLOWRELOAD, true);
				A_Overlay(LCD, "LCD_Ammo");
				A_OverlayFlags(LCD, PSPF_ADDWEAPON|PSPF_ADDBOB, true);
			}
		loop;
		
		Ready.Dryfire:
			W6I1 A 12 A_WeapSound("Halo/Weapons/DryFire", CHANF_OVERLAP);
		goto Ready.Active;

		Select:
			TNT1 A 0 A_GunRaise();
		wait;

		Deselect:
			TNT1 A 0 
			{
				A_DisableLCD();
			}
			W6S1 ABCDEF 1;
			W6S1 D 1 A_GunLower();
		wait;
		
		Fire:
			TNT1 A 0 A_GunCheckReload();
			W6I1 A 1 
			{
				if(CountLoadedAmmo() == 1) return ResolveState("Fire.Final");
				return A_Jump(255, "Fire.One", "Fire.Two");
			}
		Hold:
			W6I1 A 6 A_CheckRapidFire();
		goto Ready.Active;
		
		Fire.One:
			W6F1 A 1 bright;
			TNT1 A 0 
			{
				A_ModifyRecoil(A_CheckInScope() ? 0.5 : 1.0);
				A_FireCarbine();
				A_SetRecoil(1.0, 0, 2);
				A_RQuakeEx(4,2,0,4,0,20,"",QF_RELATIVE|QF_WAVE);
				A_Overlay(10, "DoSmoke");
			}
			W6F1 B 1 bright;
			W6F1 C 1 
			{
				A_Light(0);
				A_SetRecoil(-0.18, 0, 4);
			}
			TNT1 A 0 A_WeapSound("Halo/Weapons/Carbine/Mech", CHANF_OVERLAP);
			W6F1 DEF 1 
			{
				A_LCDOffset(0,0);
				A_RecoilOffset(0,0,4);
			}
			W6F1 GHI 1 A_CheckRapidFire();
		goto Ready.Active;
		
		Fire.Two:
			W6F1 U 1 bright;
			TNT1 A 0 
			{
				A_ModifyRecoil(A_CheckInScope() ? 0.5 : 1.0);
				A_FireCarbine();
				A_SetRecoil(1.0, 0, 2);
				A_RQuakeEx(4,2,0,4,0,20,"",QF_RELATIVE|QF_WAVE);
				A_Overlay(10, "DoSmoke");
			}
			W6F1 V 1 bright;
			W6F1 W 1 
			{
				A_Light(0);
				A_SetRecoil(-0.18, 0, 4);
			}
			TNT1 A 0 A_WeapSound("Halo/Weapons/Carbine/Mech", CHANF_OVERLAP);
			W6F1 XYZ 1 
			{
				A_LCDOffset(0,0);
				A_RecoilOffset(0,0,4);
			}
			W6F2 ABCDEFGHIJKLMN 1 A_CheckRapidFire();
		goto Ready.Active;
		
		Fire.Final:
			W6F2 O 1 bright;
			TNT1 A 0 
			{
				A_ModifyRecoil(A_CheckInScope() ? 0.5 : 1.0);
				A_FireCarbine();
				A_SetRecoil(1.0, 0, 2);
				A_RQuakeEx(4,2,0,4,0,20,"",QF_RELATIVE|QF_WAVE);
				A_Overlay(10, "DoSmoke");
			}
			W6F2 P 1 bright;
			W6F2 Q 1 
			{
				A_Light(0);
				A_SetRecoil(-0.18, 0, 4);
			}
			TNT1 A 0 A_WeapSound("Halo/Weapons/Carbine/Mech", CHANF_OVERLAP);
			W6F2 RSTUVWXYZ 1 
			{
				A_LCDOffset(0,0);
				A_RecoilOffset(0,0,4);
			}
			W6F3 ABCDEFGH 1;
		goto Reload;
			
		Reload:
			TNT1 A 0 A_ValidateReload("Ready.Dryfire");
			TNT1 A 0 A_ScopeDisable();
			TNT1 A 0 A_DisableLCD();
			TNT1 A 0 A_JumpIf(CountLoadedAmmo() <= 0, "Reload.Empty");
			TNT1 A 0 A_StartSound("Halo/Weapons/Carbine/Reload", CHAN_RELOADING, CHANF_OVERLAP);	
			W6R5 JKLMNOPQRSTUVWXYZ 1;
			W6R6 ABCDEFGHIJ 1;
			W6R6 K 1; // Unload
			W6R6 LMNOPQRSTUVWXYZ 1; 
			W6R7 ABCDEF 1;
			W6R7 G 1 A_ReloadClip(); // Reload
			W6R7 HIJKLMNOPQRSTUVWX 1;
			W6R7 Y 1 A_SetRecoil(-0.5, 0, 2); // Down
			W6R7 Z 1;
			W6R8 ABCDEFGHIJKLMNOPQRSTUVWXYZ 1;
			W6R9 ABC 1;
		goto Ready.Active;
		
		Reload.Empty:
			TNT1 A 0 A_StartSound("Halo/Weapons/Carbine/Reload/Empty", CHAN_RELOADING, CHANF_OVERLAP);
			W6R1 ABCDEFGHIJKLMNOPQR 1;
			W6R1 S 1
			{
				A_SetRecoil(-2.0, 0, 2);
				A_SetSFXPos(10,-25,-10);
				A_SpawnSFX("Debris_CarbineMagazine", -110, -30, 4);
			}
			W6R1 TUVWXYZ 1;
			W6R2 ABCDEFGHIJKLMNOP 1;
			W6R2 QR 1
			{
				A_SetRecoil(1.0, 0, 2);
				A_ReloadClip();
			}
			W6R2 STUVWXYZ 1;
			W6R3 ABCDEF 1; 
			W6R3 G 1 A_SetRecoil(-0.5, 0, 2);
			W6R3 HIJKLMNOPQRSTUVWXYZ 1;
			W6R4 ABCDEFGHIJKLMNOPQRSTUVWXYZ 1;
			W6R5 ABCDEFGHI 1;
		goto Ready.Active;

		// Weapon Status 
		LCD_Ammo:
			W6L1 "#" 1 Bright
			{
				A_FollowRotatedPos(OverlayID(), PSP_WEAPON, (0,0), addOffs:false);
				A_FollowRotation(OverlayID(), PSP_WEAPON);
				A_OverlayOffset(OverlayID(), invoker.lcd_offs.x, invoker.lcd_offs.y);
				A_SetFrame(18 - CountLoadedAmmo(), OverlayID()); 
			}
		loop;
		
		LCD_Off:
			TNT1 A 1;
		stop;
		
		Spawn:
			CARF A -1;
		stop;
	}
}
