class Halo_CMDO_Clip : Ammo 
{
	Default 
	{
		Inventory.MaxAmount 30;
	}
}
class Halo_CMDO_Reserves : Ammo
{
	mixin WorldAmmoBehavior;
	Default 
	{
		Radius 8;
		Height 6;
		Scale 0.65;

		Inventory.Amount 30;
		Inventory.MaxAmount 140;
		Inventory.Icon "HLAMT0"; // TODO: Unique ammo drop sprite
		Inventory.PickupSound "Halo/Pickup/Ammo";
		Inventory.PickupMessage "Picked up 20 Rounds for the Tactical Rifle";
		
		Ammo.BackpackMaxAmount 140;
	}
	
	States
	{
		Spawn:
			HLAM T -1 Bright;
		stop;
	}
}

class HaloCommando_Bullet : HaloBullet 
{
	Default
	{
		HaloProjectile.SetRanges COMMANDO_RANGE1, COMMANDO_RANGE2;
		HaloProjectile.MinRangeDamage COMMANDO_MINDMG; 
		HaloProjectile.BaseDamage COMMANDO_DMG;
		HaloProjectile.Speed_MPS COMMANDO_BMPS;
		HaloProjectile.HeadshotDMGFactor COMMANDO_HEDMOD;
		
		// Do normal damage to body (1.0), 25% headshot bonus
		HaloProjectile.ShieldDamageFactors 1.0, 1.25;
		Scale 0.35;
	}
}

class Halo_Commando : HaloGun
{	
	Default
	{
		//$Category "HaloDoom/Weapons"
		Weapon.SlotNumber 1;
		Obituary "%o was filled with holes by %k's Tactical Rifle.";
		Inventory.PickupMessage	"Picked up the VK78 Tactical Rifle.";
		Tag "Tactical Rifle";
		Weapon.BobSpeed 2.45;
		Weapon.BobRangeX 0.48;
		Weapon.AmmoType1 "Halo_CMDO_Reserves";
		Weapon.AmmoType2 "Halo_CMDO_Clip";
		Weapon.AmmoGive 60;
		HaloGun.Faction "Human";
				
		// Recoil	
		HaloGun.Bloom 0.6;
		HaloGun.BloomSpeed 0.6;
		HaloGun.BaseRecoil COMMANDO_RECOIL;
		HaloGun.Inaccuracy COMMANDO_ACCMOD;
		
		HaloGun.Crosshair "CMDORet", 1.0;
		HaloGun.UIGraphic "WI_CMDO", 1.0, 1.0;
		HaloGun.SetupUIAmmo "WI_AMM7", 12, 14, 0, 8;
		
		HaloGun.UISight "SI_CMDO", 1.0, 1.0;
		HaloGun.SetupScope 1.5, 0.15;
		+HaloGun.SI_Fullscreen;
		+HaloGun.SI_Rotate;
		+HaloGun.SI_AlwaysHide;
		
		HaloGun.PowerTier P_NORM;
		
		RecoilWeapon.YOffsetRange -5, 40;
	}
	
	override void GetStatsLore(out Array<String> stats, out string lore)
	{
		stats.Push("VK78 Tactical Rifle");
		stats.Push("Ammo Type: 7.62mm");
		// stats.Push("Frame: Front Loader");.
		stats.Push("Feed System: 20 Round Detachable Box Magazine");	
		stats.Push(String.Format("Base Damage: %d", COMMANDO_DMG));
	
		lore = (
			"Manufactured by Vakara GesmbH, the VK78 Tactical Rifle is an automatic rifle "
			"that has been in service since at least the late 25th century. It fires "
			"7.62mm rounds and is fed by a detachable box magazine that typically holds "
			"20 rounds. Along its top, it features a mounting rail for optics, with "
			"one common configuration including a sight akin to a recon sight. The "
			"model employed by forces attached to the UNSC Infinity in the aftermath "
			"of the emergence of the Created had an olive drab and matte black finish, "
			"with a vertical white stripe running across its front end, from the "
			"foregrip up to the rail."
			"\n"
			"The VK78 had entered production as early as the late 25th century, "
			"when it was in service with the Colonial Military Authority (CMA). "
			"In 2495, it was chosen as a replacement for the older HMG-38 heavy "
			"machine gun among CMA frontier forces. It remained in service "
			"for at least a further six decades, seeing use within the UNSC Armed" 
			"Forces at the Battle for Installation 07 in December, 2559, and in "
			"ensuing conflicts the following year. "
		);
	}
	
	override void MarkPrecacheSounds()
	{
		// Prevent stutters by precaching weapon sounds.
		MarkSound("Halo/Weapons/Commando/Fire");
		MarkSound("Halo/Weapons/Commando/Fire/Bass");
		MarkSound("Halo/Weapons/Commando/Mech");
		MarkSound("Halo/Weapons/Commando/Reload/Full");
		MarkSound("Halo/Weapons/Commando/Reload/Empty");
		MarkSound("Halo/Weapons/Commando/Select");
	}
	
	action void A_FireCommando()
	{
		A_Light(2);
		A_WeapSound("Halo/Weapons/Commando/Fire", 0);
		A_WeapSound("Halo/Weapons/Commando/Fire/Bass", CHANF_OVERLAP);
		A_ShootProjectile("HaloCommando_Bullet", A_CheckInScope() ? 0 : 10);	
		
		A_SetSFXPos(20,-15,-7);
		A_SpawnSFX("RifleCasing", -90,-20);
		A_SetSFXPos(25,-8,-6);
		
		for(int i = 0; i < 3; i++)
			A_SpawnSFX("MuzzleSmoke", 0,0);
			
		A_TakeAmmo();
		A_UpdateSpread();
	}
	
	action void A_ReloadSound()
	{
		Sound reload_snd = "Halo/Weapons/Commando/Reload";
		if(!CountLoadedAmmo()) reload_snd = "Halo/Weapons/Commando/Reload/Empty";
		A_StartSound(reload_snd, CHAN_RELOADING, CHANF_OVERLAP);
	}
	
	States
	{
		
		Ready:
			TNT1 A 0 
			{
				A_WeapSound("Halo/Weapons/Commando/Select");
				return A_JumpIf(A_DoFullSelectAnimation(), "Ready.Chamber");
			}
			// TODO: Fast select animation
			WUI1 A 1 A_DoSelectAnim();
		goto Ready.Active;
		Ready.Chamber:
			TNT1 A 0 A_DoSelectAnim(0, true);
			WUD1 ABCDEFGHIJKLMNOPQRSTUVWXY 1;
			WUD2 ABCDEFGHIJKLMNOPQRST 1;
		Ready.Active:
			WUI1 A 1 A_HaloWeaponReady(WRF_ALLOWRELOAD, true);
		loop;
		
		Ready.Dryfire:
			WUI1 A 4 A_WeapSound("Halo/Weapons/DryFire", CHANF_OVERLAP);
		goto Ready.Active;

		Select:
			TNT1 A 1 A_GunRaise();
		wait;

		Deselect:
			WUI1 A 1; // TODO: Fast select in reverse
			WUI1 A 1 A_GunLower();
		wait;
		
		// 700 RPM
		// 3 frames per shot
		Fire:
			TNT1 A 0 A_GunCheckReload();
			TNT1 A 0 A_JumpIf(CountLoadedAmmo() <= 1, "FireE");
			TNT1 A 0 A_Jump(128, "Fire1", "Fire2", "Fire3");
		Fire1:
			WUF1 A 1 Bright
			{
				A_FireCommando();
				A_SetRecoil(0.2, 0, 2);
				A_RQuakeEx(2,3,2,4,0,20,"",QF_RELATIVE|QF_WAVE|QF_SCALEDOWN);
			}
			WUF1 B 1 Bright
			{
				A_Light(0);
				A_MechanismSound("Halo/Weapons/Commando/Mech");
			}
			WUF1 C 1 A_SetRecoil(-0.1, 0, 3);
			TNT1 A 0 A_RefireState("Fire");
			WUF1 DE 1 A_RecoilOffset(0,0,2);
			WUF1 FGHIJKLMNOP 1 A_RefireState("Fire");
		goto Ready.Active;
		Fire2:
			WUF1 Q 1 Bright
			{
				A_FireCommando();
				A_SetRecoil(-0.15, 0.05, 2);
				A_RQuakeEx(2,2,2,4,0,20,"",QF_RELATIVE|QF_WAVE|QF_SCALEDOWN);
				A_RollQuake(1,2,4);
			}
			WUF1 R 1 Bright
			{
				A_Light(0);
				A_MechanismSound("Halo/Weapons/Commando/Mech");
			}
			WUF1 S 1 A_SetRecoil(-0.07, 0, 2);
			TNT1 A 0 A_RefireState("Fire");
			WUF1 TUVWXYZ 1 A_RecoilOffset(0,0,2);
			WUF2 ABCDEFGHIJK 1 A_RefireState("Fire");
		goto Ready.Active;
		Fire3:
			WUF2 L 1 Bright
			{
				A_FireCommando();
				A_SetRecoil(0.15, 0, 1);
				A_RQuakeEx(2,3,2,3,0,20,"",QF_RELATIVE|QF_WAVE|QF_SCALEDOWN);
			}
			WUF2 M 1 Bright
			{
				A_Light(0);
				A_MechanismSound("Halo/Weapons/Commando/Mech");
			}
			WUF2 N 1 A_SetRecoil(-0.15, 0, 3);
			TNT1 A 0 A_RefireState("Fire");
			WUF2 QRSTUVWXYZ 1 
			{
				A_RecoilOffset(0,0,2);
				return A_RefireState("Fire");
			}
			WUF3 A 1;
		goto Ready.Active;
		FireE:
			WUL1 A 1 Bright
			{
				A_FireCommando();
				A_SetRecoil(0.25, 0, 2);
				A_RQuakeEx(2,2,2,4,0,20,"",QF_RELATIVE|QF_WAVE|QF_SCALEDOWN);
				A_RollQuake(1,2,4);
			}
			WUL1 B 1 Bright
			{
				A_Light(0);
				A_MechanismSound("Halo/Weapons/Commando/Mech");
			}
			WUL1 C 1 A_SetRecoil(-0.1, 0, 5);
			WUL1 DE 1 A_RecoilOffset(0,0,2);
			WUL1 FGHIJKLMNOP 1;
		goto Reload;
		
		Reload:
			TNT1 A 0 A_ValidateReload("Ready.Dryfire");
			TNT1 A 0 A_ScopeDisable();
			TNT1 A 0 A_ReloadSound();
			TNT1 A 0 A_JumpIf(!CountReloadAmmo(), "Reload.Empty");
			WUR1 ABCDEFGHIJKLMNOPQRSTUV 1;
			WUR1 W 1 A_SetRecoil(0.4, -0.2, 3);
			WUR1 XYZ 1;
			WUR2 ABCDEFGHIJKLMNOPQ 1;
			WUR2 R 1 
			{
				A_ReloadClip();
				A_SetRecoil(-0.4, 0.2, 3);
			}
			WUR2 STUVWXYZ 1;
			WUR3 A 1 A_SetRecoil(-0.4, 0, 2);
			WUR3 ABCDEFGHIJKLMNOPQRSTUVWXYZ 1;
			WUR4 ABCDEFGHIJ 1;
			TNT1 A 0 A_GotoState("Ready.Active");
		
		Reload.Empty:
			WUE1 ABCDEFGHIJKLMNOPQR 1;
			WUE1 ST 1 A_SetRecoil(0, -0.2, 8);
			WUE1 U 1
			{
				A_SetSFXPos(10,-5,-30);
				A_SpawnSFX("Debris_CommandoMagazine", 0, 60);
			}
			WUE1 VWXYZ 1;
			WUE2 ABCDEFGHIJKLMNOPQRST 1;
			WUE2 U 1
			{
				A_ReloadClip();
				A_SetRecoil(-0.4, 0.2, 3);
			}
			WUE2 VWXYZ 1;
			WUE3 ABCDEFGHIJKLMNOPQRS 1;
			WUE3 T 1 A_SetRecoil(-0.4, 0.4, 2);
			WUE3 UVWXYZ 1;
			WUE4 ABCDEFGHIJKLMNOPQRSTUVWXYZ 1;
			WUE5 ABC 1;
		goto Ready.Active;
		
		Spawn:
			WUG1 A -1;
		stop;
	}
}
