class Halo_CMDO_Clip : Ammo 
{
	Default 
	{
		Inventory.MaxAmount 25;
	}
}
class Halo_CMDO_Reserves : Ammo
{
	mixin WorldAmmoBehavior;
	Default 
	{
		Radius 8;
		Height 6;
		Scale 0.65;

		Inventory.Amount 25;
		Inventory.MaxAmount 175;
		Inventory.Icon "HLAMT0"; // TODO: Unique ammo drop sprite
		Inventory.PickupSound "Halo/Pickup/Ammo";
		Inventory.PickupMessage "Picked up 25 Rounds for the Tactical Rifle";
		
		Ammo.BackpackMaxAmount 140;
	}
	
	States
	{
		Spawn:
			HLAM T -1 Bright;
		stop;
	}
}

class HaloCommando_Bullet : HaloBullet 
{
	Default
	{
		HaloProjectile.SetRanges COMMANDO_RANGE1, COMMANDO_RANGE2;
		HaloProjectile.MinRangeDamage COMMANDO_MINDMG; 
		HaloProjectile.BaseDamage COMMANDO_DMG;
		HaloProjectile.Speed_MPS COMMANDO_BMPS;
		HaloProjectile.HeadshotDMGFactor COMMANDO_HEDMOD;
		
		// Do normal damage to body (1.0), 25% headshot bonus
		HaloProjectile.ShieldDamageFactors 1.0, 1.25;
		Scale 0.35;
	}
}

class Halo_Commando : HaloGun
{	
	Default
	{
		//$Category "HaloDoom/Weapons"
		Weapon.SlotNumber 1;
		Obituary "%o was filled with holes by %k's Tactical Rifle.";
		Inventory.PickupMessage	"Picked up the MA7C Tactical Rifle.";
		Tag "Tactical Rifle";
		Weapon.BobSpeed 2.45;
		Weapon.BobRangeX 0.48;
		Weapon.AmmoType1 "Halo_CMDO_Reserves";
		Weapon.AmmoType2 "Halo_CMDO_Clip";
		Weapon.AmmoGive 50;
		HaloGun.Faction "Human";
				
		// Recoil	
		HaloGun.Bloom 0.9;
		HaloGun.BloomSpeed 0.4;
		HaloGun.BaseRecoil COMMANDO_RECOIL;
		HaloGun.Inaccuracy COMMANDO_ACCMOD;
		
		HaloGun.Crosshair "CMDORet", 1.0;
		HaloGun.UIGraphic "WI_CMDO", 1.0, 1.0;
		HaloGun.SetupUIAmmo "WI_AMM7", 12, 14, 0, 8;
		
		HaloGun.UISight "SI_CMDO", 1.0, 1.0;
		HaloGun.SetupScope 1.5, 0.15;
		+HaloGun.SI_Fullscreen;
		+HaloGun.SI_Rotate;
		+HaloGun.SI_AlwaysHide;
		
		HaloGun.PowerTier P_NORM;
		
		RecoilWeapon.YOffsetRange -5, 40;
	}
	
	override void GetStatsLore(out Array<String> stats, out string lore)
	{
		stats.Push("VK78 Tactical Rifle");
		stats.Push("Ammo Type: 7.62mm");
		// stats.Push("Frame: Front Loader");.
		stats.Push("Feed System: 20 Round Detachable Box Magazine");	
		stats.Push(String.Format("Base Damage: %d", COMMANDO_DMG));
	
		lore = (
			"The MA7C is a Medium Magnum Tactical Rifle. The rifle was created "
			"in joint collaboration between Vakara GesmbH, and Misriah to meet "
			"the needs of the UNSC and the CMA for a battle rifle that served as an "
			"intermediate between DMRs like the M392, and Standard service rifles "
			"like the MA37, and BR45 It’s 8x51mm SL4MMR rounds has armor defeating "
			"capabilities comparable to the BR series of rifles but at the cost of a "
			"slower fire rate of 400 rpm to make recoil under continuous fire managable "
			"The MA7C was employed in 2495, where it began trials for the  "
			"Colonial Military Authority to replace aging stocks of HMG-38s in "
			"then-current service where it saw light adoption by certain UNSC branches. "
			"\n"
			"By 2560, the MA7C was employed by wider UNSC Armed Forces where it saw "
			"heavy use during the Created Occupation, and the Installation 07 conflict. "
			"It is a favorite among some spartans, and marines alike due to its "
			"fire rate and accuracy which is comparable to its bullpup contemporaries.  "
		);
	}
	
	override void MarkPrecacheSounds()
	{
		// Prevent stutters by precaching weapon sounds.
		MarkSound("Halo/Weapons/Commando/Fire");
		MarkSound("Halo/Weapons/Commando/Fire/Bass");
		MarkSound("Halo/Weapons/Commando/Mech");
		MarkSound("Halo/Weapons/Commando/Reload/Full");
		MarkSound("Halo/Weapons/Commando/Reload/Empty");
		MarkSound("Halo/Weapons/Commando/Select");
	}
	
	action void A_FireCommando()
	{
		A_Light(2);
		A_WeapSound("Halo/Weapons/Commando/Fire", 0);
		A_WeapSound("Halo/Weapons/Commando/Fire/Bass", CHANF_OVERLAP);
		A_ShootProjectile("HaloCommando_Bullet", A_CheckInScope() ? 0 : 10);	
		
		A_SetSFXPos(20,-15,-7);
		A_SpawnSFX("RifleCasing", -90,-20);
		A_SetSFXPos(25,-8,-6);
		
		for(int i = 0; i < 3; i++)
			A_SpawnSFX("MuzzleSmoke", 0,0);
			
		A_TakeAmmo();
		A_UpdateSpread();
	}
	
	action void A_ReloadSound()
	{
		Sound reload_snd = "Halo/Weapons/Commando/Reload";
		if(!CountLoadedAmmo()) reload_snd = "Halo/Weapons/Commando/Reload/Empty";
		A_StartSound(reload_snd, CHAN_RELOADING, CHANF_OVERLAP);
	}
	
	States
	{
		
		Ready:
			TNT1 A 0 
			{
				A_WeapSound("Halo/Weapons/Commando/Select");
				return A_JumpIf(A_DoFullSelectAnimation(), "Ready.Chamber");
			}
			WUS1 DCBA 1 A_DoSelectAnim();
		goto Ready.Active;
		Ready.Chamber:
			TNT1 A 0 A_DoSelectAnim(0, true);
			WUD1 ABCDEFGHIJKLMNOPQRSTUVWXY 1;
			WUD2 ABCDEFGHIJKLMNOPQRST 1;
		Ready.Active:
			WUI1 A 1 A_HaloWeaponReady(WRF_ALLOWRELOAD, true);
		loop;
		
		Ready.Dryfire:
			WUI1 A 4 A_WeapSound("Halo/Weapons/DryFire", CHANF_OVERLAP);
		goto Ready.Active;

		Select:
			TNT1 A 1 A_GunRaise();
		wait;

		Deselect:
			WUS1 ABCD 1;
			WUS1 D 1 A_GunLower();
		wait;
		
		// 550 RPM
		// 4 frames per shot
		Fire:
			TNT1 A 0 A_GunCheckReload();
			TNT1 A 0 A_JumpIf(CountLoadedAmmo() <= 1, "FireE");
			TNT1 A 0 A_Jump(128, "Fire1", "Fire2", "Fire3");
		Fire1:
			WUF1 A 1 Bright
			{
				A_FireCommando();
				A_SetRecoil(0.2, 0, 2);
				A_RQuakeEx(2,3,2,4,0,20,"",QF_RELATIVE|QF_WAVE|QF_SCALEDOWN);
			}
			WUF1 B 1 Bright
			{
				A_Light(0);
				A_MechanismSound("Halo/Weapons/Commando/Mech");
			}
			WUF1 CD 1 A_SetRecoil(-0.1, 0, 3);
			TNT1 A 0 A_RefireState("Fire");
			WUF1 E 1 A_RecoilOffset(0,0,2);
			WUF1 FGHIJKLMNOP 1 A_RefireState("Fire");
		goto Ready.Active;
		Fire2:
			WUF1 Q 1 Bright
			{
				A_FireCommando();
				A_SetRecoil(-0.15, 0.05, 2);
				A_RQuakeEx(2,2,2,4,0,20,"",QF_RELATIVE|QF_WAVE|QF_SCALEDOWN);
				A_RollQuake(1,2,4);
			}
			WUF1 R 1 Bright
			{
				A_Light(0);
				A_MechanismSound("Halo/Weapons/Commando/Mech");
			}
			WUF1 ST 1 A_SetRecoil(-0.07, 0, 2);
			TNT1 A 0 A_RefireState("Fire");
			WUF1 UVWXYZ 1 A_RecoilOffset(0,0,2);
			WUF2 ABCDEFGHIJK 1 A_RefireState("Fire");
		goto Ready.Active;
		Fire3:
			WUF2 L 1 Bright
			{
				A_FireCommando();
				A_SetRecoil(0.15, 0, 1);
				A_RQuakeEx(2,3,2,3,0,20,"",QF_RELATIVE|QF_WAVE|QF_SCALEDOWN);
			}
			WUF2 M 1 Bright
			{
				A_Light(0);
				A_MechanismSound("Halo/Weapons/Commando/Mech");
			}
			WUF2 NO 1 A_SetRecoil(-0.15, 0, 3);
			TNT1 A 0 A_RefireState("Fire");
			WUF2 PQRSTUVWXYZ 1 
			{
				A_RecoilOffset(0,0,2);
				return A_RefireState("Fire");
			}
			WUF3 A 1;
		goto Ready.Active;
		FireE:
			WUL1 A 1 Bright
			{
				A_FireCommando();
				A_SetRecoil(0.25, 0, 2);
				A_RQuakeEx(2,2,2,4,0,20,"",QF_RELATIVE|QF_WAVE|QF_SCALEDOWN);
				A_RollQuake(1,2,4);
			}
			WUL1 B 1 Bright
			{
				A_Light(0);
				A_MechanismSound("Halo/Weapons/Commando/Mech");
			}
			WUL1 C 1 A_SetRecoil(-0.1, 0, 5);
			WUL1 DE 1 A_RecoilOffset(0,0,2);
			WUL1 FGHIJKLMNOP 1;
		goto Reload;
		
		Reload:
			TNT1 A 0 A_ValidateReload("Ready.Dryfire");
			TNT1 A 0 A_ScopeDisable();
			TNT1 A 0 A_ReloadSound();
			TNT1 A 0 A_JumpIf(!CountReloadAmmo(), "Reload.Empty");
			WUR1 ABCDEFGHIJKLMNOPQRSTUV 1;
			WUR1 W 1 A_SetRecoil(0.4, -0.2, 3);
			WUR1 XYZ 1;
			WUR2 ABCDEFGHIJKLMNOPQ 1;
			WUR2 R 1 
			{
				A_ReloadClip();
				A_SetRecoil(-0.4, 0.2, 3);
			}
			WUR2 STUVWXYZ 1;
			WUR3 A 1 A_SetRecoil(-0.4, 0, 2);
			WUR3 ABCDEFGHIJKLMNOPQRSTUVWXYZ 1;
			WUR4 ABCDEFGHIJ 1;
			TNT1 A 0 A_GotoState("Ready.Active");
		
		Reload.Empty:
			WUE1 ABCDEFGHIJKLMNOPQR 1;
			WUE1 ST 1 A_SetRecoil(0, -0.2, 8);
			WUE1 U 1
			{
				A_SetSFXPos(10,-5,-30);
				A_SpawnSFX("Debris_CommandoMagazine", 0, 60);
			}
			WUE1 VWXYZ 1;
			WUE2 ABCDEFGHIJKLMNOPQRST 1;
			WUE2 U 1
			{
				A_ReloadClip();
				A_SetRecoil(-0.4, 0.2, 3);
			}
			WUE2 VWXYZ 1;
			WUE3 ABCDEFGHIJKLMNOPQRS 1;
			WUE3 T 1 A_SetRecoil(-0.4, 0.4, 2);
			WUE3 UVWXYZ 1;
			WUE4 ABCDEFGHIJKLMNOPQRSTUVWXYZ 1;
			WUE5 ABC 1;
		goto Ready.Active;
		
		Spawn:
			WUG1 A -1;
		stop;
	}
}
