class Halo_EnergySword_Clip : Ammo 
{
	Default 
	{
		Inventory.MaxAmount 100;
	}
}

class Halo_DiscardedSword : FastActor
{
	States
	{
		Spawn:
			WNP1 B -1;
		stop;
	}
}

class Halo_EnergySword : HaloGun
{
	Actor curHit;
	int meleeCombo;
	int parryCooldown;

	Default
	{
		//$Category "HaloDoom/Weapons"
		Weapon.SlotNumber 1;
		Obituary "%o was \"Omae wa mou shindeiru'd\" by %k's Energy Sword.";
		Inventory.PickupMessage	"Picked up the Energy Sword.";
		Tag "Energy Sword";
		Weapon.BobSpeed 2.45;
		Weapon.BobRangeX 0.15;
		Weapon.AmmoType1 "Halo_EnergySword_Clip";
		Weapon.AmmoType2 "Halo_EnergySword_Clip";
		Weapon.AmmoGive 100;
		HaloGun.HasBattery true, 1;
		HaloGun.DisableKicking true;
		HaloGun.Faction "Covenant";
		
		HaloGun.PowerTier P_MELEE;
				
		// Recoil
		HaloGun.Bloom 0.15;
		HaloGun.BloomSpeed 0.35;
		HaloGun.BaseRecoil 1;
		HaloGun.Inaccuracy 1;
		HaloGun.Crosshair "RetESwd", 1.0;
		HaloGun.UIGraphic "WI_ESWD", 1.25, 1.25;
		
		RecoilWeapon.YOffsetRange 0, 40;
	}
	
	action void MuzzleLightning()
	{
		vector2 localPos = (frandom[WeapFX](-10,10), frandom[WeapFX](-20,0));
		vector2 overlayPos = (260,110);
		vector3 muzzlepos = HaloMath.RelativeV3Offset(self, 0,0,0, 25, localPos.x, localPos.y, 1.);
		vector2 view = (angle + frandom[WeapFX](-40,40), pitch);
		int adjustedAmt = max(5 * halodoom_effectintensity, 0);
		for(int i = 0; i < adjustedAmt; i++)
		{
			view.x = angle + frandom[WeapFX](-45,45);
			DoSpriteLightning(3, -90 + frandom[WeapFX](-60,70), localPos + overlayPos, xy_spread:(10,10), boltLen:50, stepsize:4.0, size:2.0);
		}
	}
	
	action void A_FireSword(bool recoil = true, bool doThrust = true, bool stun = false)
	{
		let hitActor = A_HaloMelee(ENERGYSWORD_DMG * 0.25, 64, (20,8), "Halo/Weapons/EnergySword/Hit", "Halo/Weapons/EnergySword/Miss", "Saw", doHitThrust:false);

		if(hitActor)
		{
			invoker.meleeCombo++;
			if(!invoker.curHit) 
			{
				A_TakeAmmo(5, false);
				if(recoil) A_AddRecoil(frandom[SwordRecoil](-1,1), frandom[SwordRecoil](-1,1), 2);
			}
			invoker.curHit = hitActor;
			
			A_QuakeEx(2,3,2,10,0,120,"");
			// vel *= 0;
			if(hitActor.health <= 0) hitActor.bSOLID = false;
			if(doThrust) A_Recoil3D(-10);
			A_SetZoom(0.94, 2);
			A_SetRecoil(2.67,0,2);
				
			// Stun victim.
			if(stun) invoker.curHit.GiveInventory("EMP_DeBuff", 1);
				
			vector2 view;
			double amt = 12;
			for(int i = 0; i < floor(amt * halodoom_effectintensity); i++)
			{
				view.x = angle + frandom[WeapFX](-60,60) + 180;
				view.y = -(pitch + frandom[WeapFX](-35,35));
				BiriBiri.DoLightning(HaloPlayer(self).aimPos, view, dist:75, 0.5, 20.0, 10.0, 30, 0);
			}	
		}
		
		A_UpdateSpread();
	}
	
	action void A_DoSwing()
	{
		invoker.curHit = NULL;
		A_WeapSound("Halo/Weapons/EnergySword/Swing", CHANF_OVERLAP);
	}
	
	action double A_MeleeLunge(double dist = 64, double thrust = 20)
	{
		double mDist = A_CheckMeleeRange();
		let hplr = HaloPlayer(self);
		if(hplr && !hplr.aimActor) thrust *= 0.25;
		if(mDist > dist) 
			vel += HaloMath.VecFromAngles(angle, pitch, thrust);
			
		return mDist;
	}
	
	action bool A_CheckMeleeRefire()
	{
		return A_ButtonStatus(BT_USER2, BTS_DOWN);
	}
	
	override bool CanPickupWeapon(WeaponPickupProxy proxy)
	{
		return proxy.getLoadedAmmo() > 0;
	}
	
	override void OnDropSwap()
	{
		meleeCombo = 0;
	}
	
	action state A_PickMeleeState()
	{
		if(A_CheckMeleeRefire())
			return ResolveState("PickMelee");
		if(A_ButtonStatus(BT_ALTATTACK, BTS_DOWN) && invoker.parryCooldown <= 0)
			return ResolveState("AltFire.Parry");
			
		return A_RefireState("Fire.Combos");
	}
		
	action void A_DoParry()
	{
		let plr = HaloPlayer(self);
		if(!plr) return;

		bool doHitSound = (invoker.parryCooldown <= 0);
		let hitActor = A_HaloMelee(0, 64, (0,0), doHitSound ? "Halo/Weapons/EnergySword/Hit" : "", doHitSound ? "Halo/Weapons/EnergySword/Miss" : "", "", doHitThrust:false);
		let victim = hitActor;
		if(victim)
		{
			bool inMissile = victim.InStateSequence(victim.CurState, victim.FindState("Missile"));
			bool inMelee = victim.InStateSequence(victim.CurState, victim.FindState("Melee"));
			if( inMissile || inMelee || victim.bINCOMBAT )
			{
				victim.TriggerPainChance("Parry", true);				
				plr.OnMeleeHit(victim);
			}
		}
		plr.invulnTics = 8;
		invoker.parryCooldown = TICRATE;
	}
	
	override void DoEffect()
	{
		super.DoEffect();
		if(parryCooldown > 0) --parryCooldown;
		
		// Drop weapon if no energy.
		if(Owner.player.ReadyWeapon != self)
		{
			meleeCombo = 0;
			if(Owner.countinv(AmmoType2) <= 0)
			{
				// Drop Energy Sword.
				DiscardWeapon("Halo_DiscardedSword");
			}
		}
	}
	
	States
	{
		Ready:
			TNT1 A 0 
			{
				A_WeapSound("Halo/Weapons/EnergySword/Draw");
				return A_JumpIf(A_DoFullSelectAnimation(), "Ready.OnPickup");
			}
			WNH2 JIHFEDCBA 1 A_DoSelectAnim(-5);
			WNH1 ZYXWVUTSRQPONMLKJIHGFEDCBA 1 A_DoSelectAnim(-5);
		goto Ready.Active;
		Ready.OnPickup:
			WND3 KLMNOPQRSTUVWXYZ 1 A_DoSelectAnim(-5, true);
			WND4 ABCDEFGHIJKLMNOPQRSTUVWXYZ 1 A_DoSelectAnim(-5);
			WND5 ABCDEFGHIJKLMNOPQRST 1 A_DoSelectAnim(-5);
		goto Ready.Active;
				
		Ready.Active:
			WNI1 A 1 
			{
				if(A_CheckState("ThrowFrag", MELEE_OVERLAY)) A_SetFrame(1);
				if(CountLoadedAmmo()) 
					A_StartSound("Halo/Weapons/EnergySword/Idle", CHAN_VOICE, CHANF_LOOPING);
				else
					A_StopSound(CHAN_VOICE);
				
				if(random[SwordLightning](0,5) == 5 && CountLoadedAmmo())
					MuzzleLightning();
				
				A_HaloWeaponReady(0, usescope:false);
				
				return A_JumpIf(!CountLoadedAmmo(), "Deselect"); 
			}
		loop;
		
		Ready.Dryfire:
			WNI1 A 1;
		goto Deselect;

		Select:
			TNT1 A 0 A_GunRaise();
		wait;

		Deselect:
			TNT1 A 0 A_StopSound(CHAN_VOICE);
			TNT1 A 0 A_WeapSound("Halo/Weapons/EnergySword/NoBattery", CHANF_OVERLAP);
			TNT1 A 0 { invoker.handsbusy = true; }
			WNH1 ABCDEFGHIJKLMNOPQRSTUVWXYZ 1;
			WNH2 ABCDEFGHIJ 1;
			TNT1 A 0 { invoker.handsbusy = false; }
		Deselect.Loop:
			TNT1 A 1 
			{
				if(health > 0)
				{
					player.ReadyWeapon = NULL;
					player.PendingWeapon = invoker.FindNextWeapon();
				}
				A_GunLower();
			}
		loop;
		
		Fire:
			TNT1 A 0 A_JumpIf(!CountLoadedAmmo(), "Ready.Dryfire");
			TNT1 A 0 
			{ 
				invoker.handsbusy = true; 
				A_WeapSound("Halo/Weapons/EnergySword/Swing", CHANF_OVERLAP);
			}
			// Combo starter
			TNT1 A 0 A_DoSwing();
			WNM1 ABC 1 A_MeleeLunge();
			WNM1 DE 1 A_FireSword();
			WNM1 FG 1 
			{
				if(!invoker.curHit) 
					A_FireSword();
			}
			WNM1 HIJKMNO 1;
			WNM1 PQRSTUVWXYZ 1 A_PickMeleeState();
			WNM2 ABCDEFHIJKLMNOPQ 1 A_PickMeleeState();
			WNI1 A 1 A_JumpIf(!A_ButtonStatus(BT_ATTACK, BTS_DOWN), "Ready.Active");
		Fire.Combos:
			TNT1 A 0 A_JumpIf(!CountLoadedAmmo(), "Ready.Dryfire");
			TNT1 A 0 A_DoSwing();
			TNT1 A 0 
			{
				if(invoker.meleeCombo >= 7)
				{
					invoker.meleeCombo = 0;
					return ResolveState("Combo.Jab");
				}
				
				switch(invoker.meleeCombo)
				{
					case 0: return A_Jump(255, "Combo.One","Combo.Two","Combo.Three","Combo.Four","Combo.Five","Combo.Six","Combo.Seven","Combo.Eight");
					case 1: return ResolveState("Combo.Two");
					case 2: return ResolveState("Combo.Three");
					case 3: return ResolveState("Combo.Four");
					case 4: return ResolveState("Combo.Five");
					case 5: return ResolveState("Combo.Six");
					case 6: return ResolveState("Combo.Seven");
					case 7: return ResolveState("Combo.Eight");
				}
				return ResolveState("Combo.One");
			}
		Combo.One:
			WNC1 ABC 1 A_MeleeLunge();
			WNC1 DE 1 A_FireSword(doThrust:false);
			WNC1 FG 1 
			{
				if(!invoker.curHit) 
					A_FireSword(doThrust:false);
			}
			WNC1 H 1;
		goto Combo.Finish;
		Combo.Two:
			WNC1 IJK 1 A_MeleeLunge();
			WNC1 LM 1 A_FireSword(doThrust:false);
			WNC1 NO 1 
			{
				if(!invoker.curHit) 
					A_FireSword(doThrust:false);
			}
			WNC1 P 1;
			WNC1 QRSTUVWXYZ 1;
		goto Combo.Finish;
		Combo.Three:
			WNC2 ABC 1 A_MeleeLunge();
			WNC2 DE 1 A_FireSword(doThrust:false);
			WNC2 FG 1 
			{
				if(!invoker.curHit) 
					A_FireSword(doThrust:false);
			}
			WNC2 H 1;
		goto Combo.Finish;
		Combo.Four:
			WNC2 IJK 1 A_MeleeLunge();
			WNC2 LM 1 A_FireSword(doThrust:false);
			WNC2 NO 1 
			{
				if(!invoker.curHit) 
					A_FireSword(doThrust:false);
			}
			WNC2 PQ 1;
		goto Combo.Finish;
		Combo.Five:
			WNC2 RST 1 A_MeleeLunge();
			WNC2 UV 1 A_FireSword(doThrust:false);
			WNC2 WX 1 
			{
				if(!invoker.curHit) 
					A_FireSword(doThrust:false);
			}
			WNC2 YZ 1;
			WNC3 ABCDEFGHI 1; 
		goto Combo.Finish;
		Combo.Six:
			WNC3 JKL 1 A_MeleeLunge();
			WNC3 LM 1 A_FireSword(doThrust:false);
			WNC3 NO 1 
			{
				if(!invoker.curHit) 
					A_FireSword(doThrust:false);
			}
			WNC3 PQRSTUVWXYZ 1;
			WNC4 ABC 1; 
		goto Combo.Finish;
		Combo.Seven:
			WNC4 DEF 1 A_MeleeLunge();
			WNC4 GH 1 A_FireSword(doThrust:false);
			WNC4 IJ 1 
			{
				if(!invoker.curHit) 
					A_FireSword(doThrust:false);
			} 
		goto Combo.Finish;
		Combo.Eight:
			WNC4 KLM 1 A_MeleeLunge();
			WNC4 NO 1 A_FireSword(doThrust:false);
			WNC4 PQ 1 
			{
				if(!invoker.curHit) 
					A_FireSword(doThrust:false);
			} 
		goto Combo.Finish;
		Combo.Jab:
			WNF1 ABCDE 1;
			WNF1 FG 1 A_FireSword(stun:true);
			WNF1 HI 1 
			{
				if(!invoker.curHit) 
					A_FireSword(stun:true);
				invoker.meleeCombo = 0;
			} 
			WNF1 JKLMNOPQRSTUVWXYZ 1 A_PickMeleeState();
			WNF2 ABCDEFGHIJKLMNOPQRSTUVWXYZ 1 A_PickMeleeState();
			WNF3 ABCDEFGHIJKLM 1;
			TNT1 A 0 
			{ 	
				invoker.handsbusy = false; 
			}
		goto Ready.Active;
		
		Combo.Finish: // Return
			WNR1 ABCD 1;
			WNR1 EFGHIJKLMNOPQRSTU 1 A_PickMeleeState();
			TNT1 A 0 
			{ 
				invoker.meleeCombo = 0;
				invoker.handsbusy = false; 
			}
		goto Ready.Active;
		
		DoMelee:
			TNT1 A 1 
			{
				let psp = player.GetPSprite(PSP_WEAPON);
				player.SetPSprite(MELEE_OVERLAY, NULL);
				if(psp && !invoker.handsbusy) psp.SetState(ResolveState("SwordMelee"));
			}
		stop;
		
		SwordMelee:
			"####" "#" 1; // This is needed to ensure this state is actually completely set.
			TNT1 A 0 A_JumpIf(!CountLoadedAmmo(), "Ready.Dryfire");
			TNT1 A 0 
			{
				A_BeginMelee(false);
			}
			TNT1 A 0
			{
				HaloGun.CallTryMelee(self); // Makes Parrying attacks more responsive.
			}
		PickMelee:
			TNT1 A 0 A_JumpIf(!CountLoadedAmmo(), "Ready.Dryfire");
			TNT1 A 0 A_DoSwing();
			TNT1 A 0 
			{
				if(invoker.meleeCombo > 5)
				{
					invoker.meleeCombo = 0;
					return ResolveState("SwordMelee.Jab");
				}
				
				switch(invoker.meleeCombo)
				{
					case 0: return A_Jump(255, "SwordMelee.One","SwordMelee.Two","SwordMelee.Three","SwordMelee.Four","SwordMelee.Five","SwordMelee.Six");
					case 1: return ResolveState("SwordMelee.Two");
					case 2: return ResolveState("SwordMelee.Three");
					case 3: return ResolveState("SwordMelee.Four");
					case 4: return ResolveState("SwordMelee.Five");
					case 5: return ResolveState("SwordMelee.Six");
				}
				return ResolveState("SwordMelee.One");
			}
			
		SwordMelee.One:
			WNM2 QRS 1;
			WNM2 TU 1 A_FireSword(doThrust:false);
			WNM2 VW 1 
			{
				if(!invoker.curHit) 
					A_FireSword(doThrust:false);
			}
			WNM2 X 1;
			WNM2 YZ 1;
		goto MeleeCombo.Finish;
		
		SwordMelee.Two:
			WNM3 ABC 1;
			WNM3 DE 1 A_FireSword(doThrust:false);
			WNM3 FG 1 
			{
				if(!invoker.curHit) 
					A_FireSword(doThrust:false);
			}
			WNM3 H 1;
			WNM3 I 1;
		goto MeleeCombo.Finish;
		
		SwordMelee.Three:
			WNM3 JKL 1;
			WNM3 MN 1 A_FireSword(doThrust:false);
			WNM3 OP 1 
			{
				if(!invoker.curHit) 
					A_FireSword(doThrust:false);
			}
			WNM3 Q 1;
			WNM3 R 1;
		goto MeleeCombo.Finish;
		
		SwordMelee.Four:
			WNM3 STU 1;
			WNM3 VW 1 A_FireSword(doThrust:false);
			WNM3 XY 1 
			{
				if(!invoker.curHit) 
					A_FireSword(doThrust:false);
			}
			WNM3 Z 1;
			WNM4 AB 1;
		goto MeleeCombo.Finish;
		
		SwordMelee.Five:
			WNM4 CDE 1;
			WNM4 FG 1 A_FireSword(doThrust:false);
			WNM4 HI 1 
			{
				if(!invoker.curHit) 
					A_FireSword(doThrust:false);
			}
			WNM4 JK 1;
			WNM4 LM 1;
		goto MeleeCombo.Finish;
		
		SwordMelee.Six:
			WNM4 NOP 1;
			WNM4 QR 1 A_FireSword(doThrust:false);
			WNM4 ST 1 
			{
				if(!invoker.curHit) 
					A_FireSword(doThrust:false);
			}
			WNM4 UV 1;
			WNM4 WX 1;
		goto MeleeCombo.Finish;
		
		SwordMelee.Jab:
			WNM4 YZ 1;
			WNM5 ABC 1 A_FireSword(stun:true);
			WNM5 DE 1 
			{
				if(!invoker.curHit) 
					A_FireSword(stun:true);
				invoker.meleeCombo = 0;
			}
			WNM5 FGHIJKLMNOPQRSTUVWXYZ 1 A_PickMeleeState();
			WNM5 ABCDEFGHIJKLMNOPQR 1 A_PickMeleeState();
			TNT1 A 0 
			{ 
				invoker.handsbusy = false; 
			}
		goto Ready.Active;
		
		MeleeCombo.Finish: // Return
			WNR1 ABCD 1;
			WNR1 EFGHIJKLMNOPQRSTU 1 A_PickMeleeState();
			TNT1 A 0 
			{ 
				invoker.meleeCombo = 0;
				invoker.handsbusy = false; 
				A_FinishMelee(false);
			}
		goto Ready.Active;
				
		// Parry (not the platypus, unless...)
		AltFire:
			"####" "#" 1 A_JumpIf(invoker.parryCooldown > 0, "Ready.Active");
		AltFire.Parry:
			WNB1 ABCDE 1;
			WNB1 FGHIJKL 1 A_DoParry();
			WNB1 LMNOPQRSTUVWXYZ 1;
			WNB2 ABCDEFGHIJKLMNOP 1; 
		goto Ready.Active;
		
		
		Spawn:
			WNP1 A -1;
		stop;
	}
}
