class Halo_GPMG_Clip : Ammo 
{
	Default 
	{
		Inventory.MaxAmount 200;
	}
}

class HaloGPMG_Bullet : HaloBullet 
{
	bool explosiveAmmo;
	Property IsExplosive : explosiveAmmo;

	Default
	{
		HaloProjectile.SetRanges GPMG_RANGE1, GPMG_RANGE2;
		HaloProjectile.MinRangeDamage GPMG_MINDMG; 
		HaloProjectile.BaseDamage GPMG_DMG;
		HaloProjectile.Speed_MPS GPMG_BMPS;
		HaloProjectile.HeadshotDMGFactor GPMG_HEDMOD;
		HaloProjectile.RicochetChance 0;
		HaloGPMG_Bullet.IsExplosive true;
		Scale 1.3;
	}
	
	States
	{
		XDeath:
		Death:
			MODL A 2 
			{
				if(explosiveAmmo)
				{
					let expl = Spawn("GPMGBulletExplosion", pos);
					if(expl) expl.target = target;
				}
			}
		stop;
	}
}

class GPMGBulletExplosion : CheapActor
{	
	double selfDamage;
	double expThrust;
	double fragIntensity;
	double dmgScale;
	Property SelfDamageAmount : selfDamage;
	Property ExplosionThrust : expThrust;
	Property FlyingExplosionChance : fragIntensity;
	Property ExplosionDamageModifier : dmgScale;
	
	Default
	{
		Scale 0.5;
		Alpha 0.8;
		Damage 0;
		GPMGBulletExplosion.SelfDamageAmount 0.33;
		GPMGBulletExplosion.ExplosionThrust 1.0;
		GPMGBulletExplosion.FlyingExplosionChance 100;
		GPMGBulletExplosion.ExplosionDamageModifier 1.0;
		
		RenderStyle "Add";
	}
	
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 1 
			{
				double sm = 2.0 * scale.X;
				let splash = Spawn("LargeSplashSpawner", pos);
				if(splash) splash.A_SetScale(sm * splash.Scale.X * 2.0);
				
				let sparks = Spawn("ImpactSparks", pos);
				if(sparks) sparks.A_SetScale(sm * 0.35);
				
				let flare = Spawn("TankRocket_Flare", (pos.xy, pos.z+20));
				if(flare) 
				{
					flare.A_SetScale(sm * 0.35);
					flare.A_SetRenderStyle(0.8, STYLE_Add);
				}
				HaloMath.ExplodeEx(self, 32 * dmgScale, 128, thrustMod:expThrust, selfDamage:selfDamage, damageBosses:false, infiniteHeight:false);
			}
			SX04 ABCD 1 Bright;
			TNT1 A 0 
			{
				vector3 fxpos = (pos.xy, pos.z+40);
				if(random[FlyingExplosionRNG](0,100) <= fragIntensity) 
					HaloMath.SpawnFX("FragGrenade_FlyingExplosion", fxpos, angle, random[GPMGExplosionRNG](1,3), 10, 20, 180,45, 25);
			}
			SX04 EFGHIJKLMNOPQ 1 Bright;
		stop;
	}
}


class Halo_DiscardedGPMG : FastActor
{
	States
	{
		Spawn:
			WVP1 A -1;
		stop;
	}
}

class Halo_GPMG : HaloGun 
{	
	Default
	{
		//$Category "HaloDoom/Weapons"
		Weapon.SlotNumber 5;
		Obituary "%o was blown to bits by %k's GPAC.";
		Inventory.PickupMessage	"Picked up the M247 General Purpose Auto Cannon";
		Tag "M247 GPAC";
		Weapon.BobSpeed 2.45;
		Weapon.BobRangeX 0.80;
		Weapon.AmmoType "Halo_GPMG_Clip";
		Weapon.AmmoType2 "Halo_GPMG_Clip";
		Weapon.AmmoGive 300;
		HaloGun.Faction "Human";
				
		// Recoil
		HaloGun.Bloom 0.12;
		HaloGun.BloomSpeed 0.25;
		HaloGun.BaseRecoil GPMG_RECOIL;
		HaloGun.Inaccuracy GPMG_ACCMOD;
		HaloGun.Crosshair "TurRet", 0.7; // lmao look at me, I'm soo punny with names :P
		HaloGun.UIGraphic "WI_GPMG", 0.4, 0.4;
		HaloGun.SetupUIAmmo "WI_AMMO", 12.5, 12.5, 0, 9;
		HaloGun.UIAmmo_Scale_Offset 1.0, 0, -10;
		
		HaloGun.TwoHandedWeapon true;
		HaloGun.PowerTier P_POWER;
		HaloGun.Rarity 50;
		
		RecoilWeapon.YOffsetRange 0, 40;
	}
	
	override int GetPowerTier()
	{	
		if(HaloPlayer.IsGameType("HL2")) return P_STRONG;
		return super.GetPowerTier();
	}
	
	/*
	override void GetStatsLore(out Array<String> stats, out string lore)
	{
		stats.Push("M247 HE Heavy Machine Gun");
		stats.Push("Ammo Type: 20mm HE Rounds");
		stats.Push("Frame: Side Loading Heavy Machine Gun");
		stats.Push("Feed System: 50 Round Side Loading Box Magazine");	
		stats.Push(String.Format("Base Damage: %d", GMPG_DMG));
		
		lore = (
			"The M247 HE Heavy Machine Gun is an Anti-Vehicle Variant "
			"of the M247 GPMG which was a reliable weapon to the UNSC for years. "
			"It entered service in 2555 when the UNSC was in need of a portable "
			"anti-armor Machine Gun. It fires 20mm High Explosive Rounds "
			"designed for eliminating light armored vehicles, and heavy infantry. "
			"The explosive core contained in the 20mm rounds is more than enough "
			"fire power to put any ghost or hunter in their rightful place in this world. "
			"Due to it's ammunition type, the M247's fire rate and capacity is "
			"greatly reduced, both to reduce weight, and minimize explosive "
			"yeild in the event of a catastrophic ammunition cook off. "
			"The M247 is often seen as either a stationary gun, or weilded by Spartans. "
		);
	}
	*/

	override void MarkPrecacheSounds()
	{
		// Prevent stutters by precaching weapon sounds.
		MarkSound("Halo/Weapons/GPMG/Fire");
		MarkSound("Halo/Weapons/GPMG/Fire/Bass");
		MarkSound("Halo/Weapons/GPMG/Mech");
		MarkSound("Halo/Weapons/GPMG/Reload");
		MarkSound("Halo/Weapons/GPMG/Reload/Empty");
		MarkSound("Halo/Weapons/GPMG/Draw");
	}
	
	action void A_FireGPMG(bool centered = false)
	{
		Sound fireSound = "Halo/Weapons/GPMG/Fire";
	
		A_Light(2);
		A_WeapSound(fireSound, CHANF_OVERLAP, true);
		A_WeapSound("Halo/Weapons/GPMG/Fire/Bass", CHANF_OVERLAP, true);
		
		let [hitPos, proj] = A_ShootProjectile("HaloGPMG_Bullet", centered ? 4 : 11, spreadmod:(centered ? 0.5 : 1.0), useHitscanMP:false);
		let bullet = HaloGPMG_Bullet(proj);
		if(bullet) bullet.explosiveAmmo = true;
		
		A_SetSFXPos(20,-18,-12);
		A_SpawnSFX("HighCaliburCasing", -90,-20);
		A_SetSFXPos(25,-10,-8);
		A_SpawnSFX("MuzzleSmoke", 0,0);
		A_TakeAmmo();
		A_UpdateSpread();
	}
	
	action void A_ReloadSound()
	{
		Sound reload_snd = "Halo/Weapons/GPMG/Reload";
		if(!CountLoadedAmmo()) reload_snd = "Halo/Weapons/GPMG/Reload/Empty";
		A_StartSound(reload_snd, CHAN_RELOADING, CHANF_OVERLAP);
	}
	
	override void DoEffect()
	{
		super.DoEffect();
	
		// Drop weapon if no ammo.
		if(Owner.player.ReadyWeapon != self)
		{
			if(Owner.countinv(AmmoType2) <= 0)
			{
				// Drop Energy Sword.
				DiscardWeapon("Halo_DiscardedGPMG");
			}
		}
	}
	
	States
	{	
		Ready:
			TNT1 A 4 A_WeapSound("Halo/Weapons/GPMG/Draw");
			WVD1 HGFEDDDCBA 2 A_DoSelectAnim(-5, true);
		goto Ready.Active;
		
		Ready.Active:
			WVI1 "#" 1
			{
				A_SetFrame(A_CheckInScope() ? 1 : 0);
				A_HaloWeaponReady(WRF_ALLOWRELOAD, true);
				return A_JumpIf(!CountLoadedAmmo(), "Deselect");
			}
		loop;
			
		Ready.Dryfire:
			WVI1 A 12 A_WeapSound("Halo/Weapons/DryFire", CHANF_OVERLAP);
		goto Ready.Active;

		Select:
			TNT1 A 1 A_GunRaise();
		wait;

		Deselect:
			WVD1 ABCDDEFGH 2;
		Deselect.Loop:
			WVD1 H 1 
			{
				// Needed because weapon is removed from inventory during this process.
				if(health > 0)
				{
					player.ReadyWeapon = NULL;
					player.PendingWeapon = invoker.FindNextWeapon();
				}
				A_GunLower();
			}
		loop;
		
		Fire:
			TNT1 A 0 A_JumpIf(!CountLoadedAmmo(), "Ready.DryFire");
			TNT1 A 0 A_JumpIf(A_CheckInScope(), "FireCenter");
			TNT1 A 0 A_Jump(128, "Fire.Two");
		Fire.One:
			WVF1 A 1 A_SetZoom(0.95, 2);
			WVF1 B 1 Bright
			{
				A_RecoilOffset(5,5,1);
				A_SetRecoil(1.42, 0, 1);
				A_RQuakeEx(4,2,1,3,0,20,"",QF_RELATIVE|QF_WAVE|QF_SCALEDOWN);
				A_RollQuake(2,10,1);
				A_FireGPMG();
			}
			WVF1 C 1
			{
				A_Light(0);
				A_SetZoom(1.0, 5);
				A_MechanismSound("Halo/Weapons/GPMG/Mech");
			}
			WVF1 D 1 A_RecoilOffset(0,0,6);
			WVF1 CA 1;
		goto Ready.Active;
		
		Fire.Two:
			WVF1 I 1 A_SetZoom(0.95, 2);
			WVF1 J 1 Bright
			{
				A_RecoilOffset(5,5,1);
				A_SetRecoil(1.42, 0, 1);
				A_RQuakeEx(4,2,1,3,0,20,"",QF_RELATIVE|QF_WAVE|QF_SCALEDOWN);
				A_RollQuake(2,10,1);
				A_FireGPMG();
			}
			WVF1 K 1
			{
				A_Light(0);
				A_SetZoom(1.0, 5);
				A_MechanismSound("Halo/Weapons/GPMG/Mech");
			}
			WVF1 L 1 A_RecoilOffset(0,0,4);
			WVF1 KI 1;
		goto Ready.Active;
		
		FireCenter:
			TNT1 A 0 A_Jump(128, "FireCenter.Two");
		FireCenter.One:
			WVF1 E 1 A_SetZoom(0.92, 2);
			WVF1 F 1 Bright
			{
				A_RecoilOffset(0,10,1);
				A_SetRecoil(0.95, 0, 1);
				A_RQuakeEx(4,2,1,3,0,20,"",QF_RELATIVE|QF_WAVE|QF_SCALEDOWN);
				A_RollQuake(2,4,1);
				A_FireGPMG(true);
			}
			WVF1 G 1
			{
				A_Light(0);
				A_SetZoom(1.0, 5);
				A_MechanismSound("Halo/Weapons/GPMG/Mech");
			}
			WVF1 H 1 A_RecoilOffset(0,0,6);
			WVF1 GE 1;
		goto Ready.Active;
		FireCenter.Two:
			WVF1 M 1 A_SetZoom(0.92, 2);
			WVF1 N 1 Bright
			{
				A_RecoilOffset(0,10,1);
				A_SetRecoil(0.95, 0, 1);
				A_RQuakeEx(4,2,1,3,0,20,"",QF_RELATIVE|QF_WAVE|QF_SCALEDOWN);
				A_RollQuake(2,4,1);
				A_FireGPMG(true);
			}
			WVF1 O 1
			{
				A_Light(0);
				A_SetZoom(1.0, 5);
				A_MechanismSound("Halo/Weapons/GPMG/Mech");
			}
			WVF1 P 1 A_RecoilOffset(0,0,6);
			WVF1 QO 1;
		goto Ready.Active;
		
		Spawn:
			WVP1 A -1;
		stop;
	}
}
