class Halo_GrenadeLauncher_Mag : Ammo 
{
	Default 
	{
		Inventory.MaxAmount 4;
	}
}
class Halo_GrenadeLauncher_Reserves : Ammo
{
	mixin WorldAmmoBehavior;
	Default 
	{
		Radius 8;
		Height 6;

		Inventory.Amount 1;
		Inventory.MaxAmount 20;
		Inventory.Icon "HLAMC0";
		Inventory.PickupSound "Halo/Pickup/Ammo";
		Inventory.PickupMessage "Picked up 8 Shells for the Riot Shotgun";
		
		Ammo.BackpackMaxAmount 24;
	}
	
	States
	{
		Spawn:
			HLAM Z -1 Bright;
		stop;
	}
}


class Halo_GrenadeLauncher : HaloGun
{
	Default
	{	
		//$Category "HaloDoom/Weapons"
		Weapon.SlotNumber 4;
		Obituary "%o's was turned into red mist by %k's Grenade Launcher.";
		Inventory.PickupMessage	"Picked up the Grenade Launcher.";
		Tag "Grenade Launcher";
		Weapon.BobSpeed 1.68;
		Weapon.BobRangeX 0.10;
		Weapon.AmmoType1 "Halo_GrenadeLauncher_Reserves";
		Weapon.AmmoGive 4;
		Weapon.AmmoType2 "Halo_GrenadeLauncher_Mag";
		HaloGun.Faction "Human";
		
		HaloGun.PowerTier P_STRONG;
				
		// Recoil
		HaloGun.Bloom 1.2;
		HaloGun.BloomSpeed 0.10;
		HaloGun.BaseRecoil GLAUNCHER_RECOIL;
		HaloGun.Inaccuracy GLAUNCHER_ACCMOD;
		HaloGun.Crosshair "NadeRet", 0.8;
		HaloGun.UIGraphic "MISSNG", 0.65, 0.65;
		HaloGun.SetupUIAmmo "WI_AMM2", 16, 16, 0, 6;
		
		RecoilWeapon.YOffsetRange 0, 20;
	}
	
	override int GetPowerTier()
	{	
		if(HaloPlayer.IsGameType("SpartanOverkill")) return P_MID;
		return super.GetPowerTier();
	}
	
	/*
	override void MarkPrecacheSounds()
	{
		// Prevent stutters by precaching weapon sounds.
		MarkSound("Halo/Weapons/Bulldog/Fire");
		MarkSound("Halo/Weapons/Bulldog/Fire/Bass");
		MarkSound("Halo/Weapons/Bulldog/ReloadPump");
		MarkSound("Halo/Weapons/Bulldog/Reload");
		MarkSound("Halo/Weapons/Bulldog/Ready");
	}
	*/
	
	override void OverlayUIFX(RenderEvent e, double dT)
	{
		HLSBS.DrawString(
			"HaloFont", 
			"[WIP] UNFINISHED WEAPON", (0,-250), 
			HLSBS.SS_SCREEN_CENTER | HLSBS.SS_TEXT_CENTER, 
			Font.CR_RED, scale:(0.20,0.20)
		);
	}
	
	action void A_FireGrenade()
	{
		A_MuzzleSparks(15, 60, 8,8);
		A_TakeAmmo(1);
		A_UpdateSpread();
		return; // TODO: Make actually shoot.
	
		A_Light(2);
		A_WeapSound("Halo/Weapons/Bulldog/Fire", CHANF_OVERLAP);
		A_WeapSound("Halo/Weapons/Bulldog/Fire/Bass", CHANF_OVERLAP);
		A_SetSFXPos(25,-10,-10);
		for(int i = 0; i < 20; i++)
		{
			A_ShootProjectile("HaloBulldog_Bullet", 8);		
			if(!(i%2)) A_SpawnSFX("MuzzleSmoke", 0,0);
		}
		
		for(int i = 0; i < max(5, 30 * halodoom_effectintensity); i++)
		{
			vector3 hitPos; Actor tSpark;
			[hitPos, tSpark] = A_ShootProjectile("DragonSparkTracer", 8);
			if(tSpark)
			{
				tSpark.angle += frandom[DragonFX](-6,6);
				tSpark.pitch += frandom[DragonFX](-6,6);
				tSpark.target = self;
			}
		}
		
		
		A_TakeAmmo(1);
		A_UpdateSpread();
	}
	
	action void A_ReloadSound()
	{
		Sound reload_snd = "Halo/Weapons/Bulldog/Reload";
		if(!CountLoadedAmmo()) reload_snd = "Halo/Weapons/Bulldog/ReloadPump";
		A_StartSound(reload_snd, CHAN_RELOADING, CHANF_OVERLAP);
	}
	
	States
	{
		Ready:
			TNT1 A 4 A_WeapSound("Halo/Weapons/Bulldog/Ready");
			G1D1 ABCDEFGHIJKLMNOPQRSTUVWXYZ 1 A_DoSelectAnim(0, true);
			G1D2 ABCDEFGHIJKLMNOPQRSTUVWXYZ 1 A_DoSelectAnim(0, true);
			G1D3 ABCDEFGHI 1 A_DoSelectAnim(0, true);
		goto Ready.Active;
		
		Ready.Active:
			G1G1 A 1 A_HaloWeaponReady(WRF_ALLOWRELOAD, true);
		loop;	
		
		Ready.Dryfire:
			G1G1 A 1;
		goto Ready.Active;

		Select:
			TNT1 A 1 A_GunRaise();
		wait;

		Deselect:
			G1D3 IHGFEDCBA 1;
			G1D2 ZYXWVUTSRQPONMLKJIHGFEDCBA 1;
			G1D1 GFEDCBA 1;
			G1D1 A 1 A_GunLower(16);
		wait;
		
		Fire:
			TNT1 A 0 A_GunCheckReload();
			TNT1 A 0 A_Jump(128, "Fire1", "Fire2", "Fire3");
			
		Fire1:
			G1F1 A 1 Bright
			{
				A_SetZoom(0.98, 2);
				A_SetRecoil(7.50, 0, 2);
				A_FireGrenade();
				A_RQuakeEx(3,1,0,4,0,20,"",QF_RELATIVE|QF_WAVE);
				A_RollQuake(1,6,1);
			}
			G1F1 BCD 1 Bright;
			TNT1 A 0 A_Light(0);
			G1F1 EF 1 Bright
			{
				A_SetRecoil(-2.0, 0, 4);
				A_SetZoom(1.0, 2);
			}
			G1F1 GHIJKLMNOPQRSTUVWXY 1; 
			G1F1 Z 1; // Pump Start
			TNT1 A 0 A_SetRecoil(-1.0, 0, 4);
			G1F2 ABCDEFGHIJK 1;
			TNT1 A 0 A_SetRecoil(1.0, 0, 4);
			G1F2 L 1; // Pump End
			G1F2 MNOPQRSTUVWXYZ 1;
			G1F3 ABCDEFGHIJKLMNOPQR 1;
		goto Ready.Active;
		
		Fire2:
			G1F3 S 1 Bright
			{
				A_SetZoom(0.98, 2);
				A_SetRecoil(7.50, 0, 2);
				A_FireGrenade();
				A_RQuakeEx(3,1,0,4,0,20,"",QF_RELATIVE|QF_WAVE);
				A_RollQuake(1,6,1);
			}
			G1F3 TUV 1 Bright;
			TNT1 A 0 A_Light(0);
			G1F3 WX 1 Bright
			{
				A_SetZoom(1.0, 2);
			}
			G1F3 YZ 1;
			G1F4 ABCDEFGHIJKLMNOPQ 1; 
			G1F4 R 1; // Pump Start
			TNT1 A 0 A_SetRecoil(-1.0, 0, 4);
			G1F4 STUVWXYZ 1;
			TNT1 A 0 A_SetRecoil(1.0, 0, 4);
			G1F5 ABC 1;
			G1F5 D 1; // Pump End
			G1F5 EFGHIJKLMNOPQR 1;
			G1F5 STUVWXYZ 1;
			G1F6 ABCDEFGHIJ 1;
		goto Ready.Active;
		
		Fire3:
			G1F6 M 1 Bright
			{
				A_SetZoom(0.98, 2);
				A_SetRecoil(7.50, 0, 2);
				A_FireGrenade();
				A_RQuakeEx(3,1,0,4,0,20,"",QF_RELATIVE|QF_WAVE);
				A_RollQuake(1,6,1);
			}
			G1F6 NOP 1 Bright;
			TNT1 A 0 A_Light(0);
			G1F6 QR 1 Bright
			{
				A_SetZoom(1.0, 2);
			}
			G1F6 STUVWXYZ 1;
			G1F7 ABCDEFGHIJK 1;
			G1F7 L 1; // Pump Start
			TNT1 A 0 A_SetRecoil(-1.0, 0, 4);
			G1F7 MNOPQRST 1;
			TNT1 A 0 A_SetRecoil(1.0, 0, 4);
			G1F7 UVWXYZ 1; // Pump End
			G1F8 ABCDEFGHIJKL 1;
			G1F8 MNOPQRSTUVWXYZ 1;
			G1F9 ABCD 1;
		goto Ready.Active;
		
		Reload:
			TNT1 A 0 A_ValidateReload("Ready.Dryfire");
			TNT1 A 0 A_ReloadSound();
			TNT1 A 0 A_JumpIf(!CountReloadAmmo(), "Reload.Empty");
			G1R5 TUVWXYZ 1 A_SetRecoil(1.0, 0, 2);
			G1R6 ABCDE 1;
			G1R6 F 1 A_SetRecoil(1.0, 0.25, 2);
			G1R6 GHIJKLMNOPQRSTUVWXYZ 1;
			G1R7 ABCDEFHIJK 1;
			G1R7 L 1 A_ReloadClip();
			G1R7 MNOPQRSTUV 1;
			G1R7 W 1 A_SetRecoil(-1.0, -0.25, 2);
			G1R7 XYZ 1;
			G1R8 ABCDEFGHIJKLMNOPQRSTUVWXYZ 1;
			G1R9 ABCDEFGHI 1;
			TNT1 A 0 A_GotoState("Ready.Active");

		Reload.Empty:
			G1R1 ABCDEFGHIJKL 1;
			G1R1 M 1
			{
				A_SetRecoil(-2.0, 0, 2);
				// A_SetSFXPos(10,-5,-20);
				// A_SpawnSFX("Debris_BulldogMagazine", 0, 60);
			}
			G1R1 NOPRQRSTUVWZYZ 1;
			G1R2 ABCDEFGHIJKLMNOPQ 1;
			G1R2 R 1 A_SetRecoil(2.0, 0, 2); 
			TNT1 A 0 A_ReloadClip();
			G1R2 STUVWXYZ 1;
			G1R3 ABC 1;
			G1R3 D 1 A_SetRecoil(-1.0, -0.25, 2);
			G1R3 EFGHIJKLMNOPQRSTUVWXY 1;
			G1R3 Z 1 A_SetRecoil(-1.0, 0, 4);
			G1R4 ABCDEFG 1;
			G1R4 H 1 A_SetRecoil(1.0, 0, 4);
			G1R4 IJKLMNOPQRSTUVWXYZ 1;
			G1R5 ABCDEFGHIJKLMNOPQRS 1;
		goto Ready.Active;
		
		Spawn:
			WAG1 A -1;
		stop;
	}
}


/*
Fire4:
	G1F9 E 1 Bright
	{
		A_SetZoom(0.98, 2);
		A_SetRecoil(7.50, 0, 2);
		A_FireGrenade();
		A_RQuakeEx(3,1,0,4,0,20,"",QF_RELATIVE|QF_WAVE);
		A_RollQuake(1,6,1);
	}
	G1F9 FGH 1 Bright;
	TNT1 A 0 A_Light(0);
	G1F9 IJ 1 Bright
	{
		A_SetZoom(1.0, 2);
	}
	G1F9 KLMNOPQRSTUVWXYZ  1;
	G1FA AB 1; // Pump Start
	TNT1 A 0 A_SetRecoil(-1.0, 0, 4);
	G1FA CDEFGHIJ 1;
	TNT1 A 0 A_SetRecoil(1.0, 0, 4);
	G1FA KLMO 1; // Pump End
	G1FA PQRSTUVWXYZ 1;
	G1FB ABCDEFGHIJKLMNOPQRSTU 1;
goto Ready.Active;
*/