
class Halo_LightRifleMag : Ammo 
{
	Default 
	{
		Inventory.MaxAmount 42;
	}
}
class Halo_LightRifle_Reserves : Ammo
{
	mixin WorldAmmoBehavior;
	Default 
	{
		Radius 0;
		Height 0;
		Scale 0.65;

		Inventory.Amount 255;
		Inventory.MaxAmount 255;
		Inventory.Icon "";
		Inventory.PickupSound "";
		Inventory.PickupMessage "";
		Ammo.BackpackMaxAmount 300;
	}
	
	States
	{
		Spawn:
			TNT1 A -1;
		stop;
	}
}

class LSR_LightRifleDMR : LSR_BinaryRifle 
{
	Default
	{
		LaserBeam.LaserColor "#0061FF"; 
		Translation "0:255=@64[0,97,255]";
		LSR_UnmakerBeam.LaserPuff "LightRifleDMRPuff";
		LSR_BinaryRifle.LaserDamage (LIGHTRIFLE_DMG * 6.0);
	}

	override void OnImpact(vector3 hitPos, Actor hitActor)
	{
		super.OnImpact(hitPos, hitActor);
		if(!hitActor) return;
		
		if(hitActor.bCORPSE || hitActor.health <= 0)
		{
			for(int i = 0; i < 3; i++)
			{
				let expl = Coil_Hardlight_Explosion(Spawn("Coil_Hardlight_Explosion", hitPos));
				expl.translation = translation;
				expl.target = source;
				expl.plrSource = source;
			}
		}
	}
}

class LSR_LightRifle : LSR_BinaryRifle
{
	Default
	{
		Alpha 2.0;
		Scale 3.0;
		LaserBeam.LaserColor "#0061FF"; 
		LaserBeam.TrackWeapon true, PSP_WEAPON;
		LaserBeam.AimFromWeapon false;
		LSR_BinaryRifle.LaserDamage (LIGHTRIFLE_DMG);
		
		Translation "0:255=@64[0,97,255]";
		LaserBeam.LaserDecal "UnmakerDecal";
		LSR_UnmakerBeam.LaserPuff "LightRiflePuff";
		+BRIGHT;
	}
	
	override void BeamTick()
	{	
		alpha -= 0.20;
		A_SetScale(Scale.X * 0.87, Scale.Y);
	
		if(alpha <= 0.1 || Scale.X <= 0.05) Destroy();
	}
}
class LSR_LightRifleCore : LSR_LightRifle
{
	Default
	{
		Alpha 2.0;
		Scale 1.5;
		LaserBeam.LaserColor "White"; 
		LaserBeam.TrackWeapon true, PSP_WEAPON;
		LaserBeam.AimFromWeapon false;
		+BRIGHT;
	}
	
	override void OnImpact(vector3 hitPos, Actor hitActor) {}
}
class LightRiflePuff : UnmakerLaserPuff
{
	Default
	{
		Scale 0.5;
		UnmakerLaserPuff.laserPuffs 2, 75, 0.25;
		UnmakerLaserPuff.FadeTics 10;
		Translation "0:255=@64[0,97,255]";
		UnmakerLaserPuff.LightningType "LightRifle_Lightning";
	}
}
class LightRifleDMRPuff : UnmakerLaserPuff
{
	Default
	{
		Scale 1.0;
		UnmakerLaserPuff.laserPuffs 6, 100, 0.25;
		UnmakerLaserPuff.FadeTics 35;
		Translation "0:255=@64[0,97,255]";
		UnmakerLaserPuff.LightningType "LightRifle_Lightning";
	}
}

class LightRifle_Lightning : LightningBiri
{
	Default
	{
		Translation "0:255=@64[0,97,255]";	
	}
}

class Halo_LightRifle : HaloGun
{
	const LIGHTRIFLE_ORBOVERLAY = -60;
	const CHAN_LRCHARGE = 105;
	int chargeFireTics;

	Default
	{
		//$Category "HaloDoom/Weapons"
		Weapon.SlotNumber 5;
		Obituary "%o was blinded by %k's Light Rifle.";
		Inventory.PickupMessage	"Picked up the Light Rifle.";
		Tag "Light Rifle";
		Weapon.BobSpeed 2.45;
		Weapon.BobRangeX 0.63;
		Weapon.AmmoType1 "Halo_LightRifle_Reserves";
		Weapon.AmmoType2 "Halo_LightRifleMag";
		Weapon.AmmoGive 255;
		HaloGun.Faction "Forerunner";
		
		HaloGun.PowerTier P_MID;
		HaloGun.Rarity 10;
				
		// Recoil
		HaloGun.Bloom 1.25;
		HaloGun.BloomSpeed 0.35;
		HaloGun.BaseRecoil 1;
		HaloGun.Inaccuracy 1;
		HaloGun.Crosshair "LrRet", 1.0;
		HaloGun.UIGraphic "MISSNG", 0.8, 0.7;
		HaloGun.SetupScope 2.0, 0.5;

		HaloGun.ZoomSounds "Halo/Weapons/LightRifle/Zoom/IN", "Halo/Weapons/LightRifle/Zoom/OUT";
		RecoilWeapon.YOffsetRange 0, 40;
		
		Scale 0.5;
	}
	
	override int GetPowerTier()
	{	
		if(HaloPlayer.IsGameType("SpartanOverkill")) return P_MID;
		return super.GetPowerTier();
	}	
		
	action void A_FireLightRifleBurst(int ammouse = 2)
	{
		A_Light(4);
		A_WeapSound("Halo/Weapons/LightRifle/Fire", CHANF_OVERLAP, false);
		A_WeapSound("Halo/Weapons/LightRifle/Fire/Bass", CHANF_OVERLAP, false);
		
		let beam = LaserBeam.Create(self, 7, 2, -2, type:"LSR_LightRifle");
		let beamCore = LaserBeam.Create(self, 7, 2, -2, type:"LSR_LightRifleCore");
		
		let it = ThinkerIterator.Create();
		Actor act;
		LookExParams look;
		look.FOV = 30;
		
		double closeDist;
		Actor closestActor;
		closeDist = double.infinity;
		
		while(act = Actor(it.Next()))
		{
			if(act == self) continue;
			if(!act.bSHOOTABLE || act.bFRIENDLY || !act.bISMONSTER) continue;
			if(!isVisible(act, false, look)) continue;
			
			double curDist = Distance3DSquared(act);
			if(closeDist < curDist) continue;
			closestActor = act;
			closeDist = curDist;
		}		
		
		let aimActor = closestActor;
		if(aimActor)
		{
			vector3 aimAtPos = (aimActor.pos.xy, aimActor.pos.z + (aimActor.height*0.5));
			beam.StartTracking(aimAtPos);
			beamCore.StartTracking(aimAtPos);
		}
		
		beam.setEnabled(true);
		beamCore.setEnabled(true);
		
		SetupPlasmaLightning(16, -3, 8, scale:1.0, density:3.0, shading:"#0061FF");
		A_TakeAmmo(ammouse);
		A_UpdateSpread();
	}

	action void A_FireLightRifleSniper()
	{
		A_Light(4);
		A_WeapSound("Halo/Weapons/LightRifle/Fire/DMR", CHANF_OVERLAP, false);
		A_WeapSound("Halo/Weapons/LightRifle/Fire/DMR/Bass", CHANF_OVERLAP, false);
	
		let beam = LaserBeam.Create(self, 7, 0, -2, type:"LSR_LightRifleDMR");
		let beamCore = LaserBeam.Create(self, 7, 0, -2, type:"LSR_BinaryRifleCore");
		
		beam.setEnabled(true);
		beamCore.setEnabled(true);
					
		SetupPlasmaLightning(16, 0, 12, scale:0.2, density:3.0, shading:"#0061FF", replace:true);
		A_TakeAmmo(6);
		A_UpdateSpread();
	}

	bool sightsHold;
	States
	{
		
		Ready:
			TNT1 A 0 
			{
				A_WeapSound("Halo/Weapons/LightRifle/Draw");
				return A_JumpIf(A_DoFullSelectAnimation(), "Ready.Chamber");
			}
			WPS1 ABCD 1 A_DoSelectAnim();
		goto Ready.Active;
		
		Ready.Chamber:
			WPD1 ABCDEFGHIJKLMNOPQRSTUVWX 1 A_DoSelectAnim(0, true);
		Ready.Active:
			WPI1 A 1 
			{
				if(invoker.chargeFireTics > 0) invoker.chargeFireTics = 0;
				A_HaloWeaponReady(WRF_ALLOWRELOAD, usescope:false);
				A_StopPlasmaLightning();
				
				return A_JumpIf(A_ShouldEnableScope(), "Scope.Enable");
			}
		loop;
		
		Ready.ADS:
			WPA1 D 1 
			{
				if(invoker.chargeFireTics > 0) invoker.chargeFireTics--;
				A_StopSound(CHAN_LRCHARGE);
				A_HaloWeaponReady(WRF_ALLOWRELOAD, usescope:false);
				A_RecoilOffset(0,0, 8);
				return A_JumpIf(A_ShouldDisableScope(invoker.sightsHold), "Scope.Disable");
			}
		loop;
		
		Orb:
			"####" "#" 1 Bright
			{
				invoker.chargeFireTics = invoker.chargeFireTics % 52;
				int chargeTics = invoker.chargeFireTics;
				
				string curSprite = "TNT1A0";
				int curFrame = 0;
				
				if(chargeTics > 0 && A_CheckInScope())
				{
					int spr = chargeTics > 26 ? 2 : 1; 
					curSprite = String.Format("WPO%dA0", spr);
					curFrame = chargeTics % 26;
				}
				
				A_SetSprite(curSprite, OverlayID());
				A_SetFrame(curFrame, OverlayID());
			}
		loop;
		
		Orb.Cache:
			WPO1 "#" 0;
			WPO2 "#" 0;
		stop;
		
		Ready.Dryfire:
			"####" "#" 4 A_WeapSound("Halo/Weapons/DryFire", CHANF_OVERLAP);
			"####" "#" 0 A_JumpIf(A_CheckInScope(), "Ready.ADS");
		goto Ready.Active;

		Select:
			TNT1 A 1 A_GunRaise();
		wait;

		Deselect:
			WPS1 DCBA 1
			{
				A_StopSound(CHAN_LRCHARGE);
				A_SetZoom(0, 3, true);
				
				if(A_CheckInScope()) 
					A_SetCustomScope(0);
			}
			WPS1 F 1 A_GunLower();
		wait;
		
		Fire:
			TNT1 A 0 A_JumpIf(!CountLoadedAmmo(), "Reload");
			TNT1 A 0 A_JumpIf(A_CheckInScope(), "Fire.Charge");
			
			WPF1 A 1 Bright A_SetZoom(0.98, 2);
			WPF1 B 1 Bright
			{	
				A_FireLightRifleBurst(1);
				A_SetRecoil(0.3, 0, 4);
				A_RollQuake(2,4,1);
				A_RecoilOffset(8,10,2);
			}
			WPF1 C 1
			{
				A_RecoilOffset(0,8,2);
				A_Light(0);
				A_SetZoom(1.0, 2);
			}
			
			WPF1 A 1 Bright A_SetZoom(0.96, 2);
			WPF1 B 1 Bright
			{
				A_RollQuake(-2,4,2);
				A_SetRecoil(0.3, 0, 4);
				A_RecoilOffset(0,8,1);
				A_FireLightRifleBurst(1);
				A_SetZoom(1.0, 2);
			}
			WPF1 C 1 
			{
				A_SetZoom(1.0, 2);
				A_Light(0);
				A_RecoilOffset(8,10,2);
			}
			
			WPF1 A 1 Bright A_SetZoom(0.96, 2);
			WPF1 B 1 Bright
			{
				A_SetRecoil(0.3, 0, 4);
				A_RollQuake(-2,4,2);
				A_RecoilOffset(0,8,1);
				A_FireLightRifleBurst(1);
			}
			WPF1 C 1 
			{
				A_SetZoom(1.0, 4);
				A_Light(0);
				A_RecoilOffset(0,0,4);
			}
			WPF1 DEFGHIJK 1;
		goto Ready.Active;
		
		Fire.Charge:
			WPA1 D 1 A_JumpIf(CountLoadedAmmo() < 6, "Ready.DryFire");
			TNT1 A 0 A_StartSound("Halo/Weapons/LightRifle/Charge", CHAN_LRCHARGE, CHANF_OVERLAP);
		Fire.ChargeLoop:
			WPA1 D 1;
			TNT1 A 0 
			{
				A_RecoilOffset(frandom[LightRifleCharge](-1,1), frandom[LightRifleCharge](-3,3), 2, add:true);
				State st = A_ButtonStatus(BT_ATTACK, BTS_UP) ? ResolveState("Ready.ADS") : ResolveState("Fire.ChargeLoop");
				if(invoker.chargeFireTics++ >= 51)
					st = ResolveState("Fire.ChargeShot");
					
				return st; 
			}
		Fire.ChargeShot:
			WPA1 E 1 
			{	
				A_FireLightRifleSniper();
				A_SetZoom(0.85, 1);
				A_RollQuake(1,10,2);
			}
			WPA1 FG 1 A_SetRecoil(2.25, 0, 2);
			WPA1 H 1 
			{
				A_SetZoom(1.0, 8);
				A_Light(0);
				A_SetRecoil(-0.18, 0, 4);
			}
			WPA1 IJK 1;
			WPA1 D 10;
		goto Ready.ADS;
		
		Scope.Enable:
			WPA1 ABCD 1 A_SetZoom(invoker.scopezoom, 3, true);
			TNT1 A 0 
			{
				A_Overlay(LIGHTRIFLE_ORBOVERLAY, "Orb"); 
				A_OverlayPivot(LIGHTRIFLE_ORBOVERLAY, 0.5, 0.5);
				A_OverlayScale(LIGHTRIFLE_ORBOVERLAY, 0.5);
			
				invoker.sightsHold = invoker.ADS_Held;
				A_SetCustomScope(1);	
			}
		goto Ready.ADS;
		
		Reload.FromScope:
			WPA1 DCBA 1 A_SetZoom(0, 3, true);
			WPI1 A 1 A_SetCustomScope(0);
		Reload:
			"####" "#" 1 
			{
				A_StopSound(CHAN_LRCHARGE);
				return A_JumpIf(A_CheckInScope(), "Reload.FromScope");
			}
			"####" "#" 0 A_ValidateReload("Ready.Dryfire");
			TNT1 A 0 
			{
				A_StartSound("Halo/Weapons/LightRifle/Reload/Start", CHAN_RELOADING);
				A_StartSound("Halo/Weapons/ScatterShot/Reload/Background", CHAN_RELOADING, CHANF_OVERLAP);
			}
			WPR1 ABCDEFG 2;
		Reload.Loop:
			TNT1 A 0 A_StartSound("Halo/Weapons/LightRifle/Reload/Single", CHAN_RELOADING, CHANF_OVERLAP);
			WPR1 HIJKKJIH 2 
			{
				A_RecoilOffset(frandom[ScShake](-3,3), frandom[ScShake](-3,3), 2, add:true);
				
				bool doAbortReload = (CountLoadedAmmo() && A_ButtonStatus(BT_ATTACK, BTS_DOWN));
				if(doAbortReload) A_StopSound(CHAN_RELOADING);
				return A_JumpIf(doAbortReload, "Ready.Active");
			}
			TNT1 A 0 A_ReloadAmount(6);
			TNT1 A 0 A_ValidateReload("Reload.Finish");
			TNT1 A 0 A_GotoState("Reload.Loop");
		Reload.Finish:
			TNT1 A 0 
			{
				A_StopSound(CHAN_RELOADING);
				A_StartSound("Halo/Weapons/LightRifle/Reload/End", CHAN_RELOADING);
			}
			WPR1 GFEDCBA 2 A_RecoilOffset(0,0,12);
		goto Ready.Active;

		Scope.Disable:
			WPA1 DCBA 1 A_SetZoom(0, 3, true);
			WPI1 A 1 A_SetCustomScope(0);
		goto Ready.Active;
		
		Spawn:
			WPP1 A -1;
		stop;
	}
}
