class Halo_PlasmaRifle_Clip : Ammo 
{
	Default 
	{
		Inventory.MaxAmount 100;
	}
}

class HaloPlasmaRifle_Proj : HaloPlasma_Proj
{
	Default
	{
		HaloProjectile.SetRanges PLASMARIFLE_RANGE1, PLASMARIFLE_RANGE2; 
		HaloProjectile.MinRangeDamage PLASMARIFLE_MINDMG; 
		HaloProjectile.BaseDamage PLASMARIFLE_DMG; 
		HaloProjectile.Speed_MPS  PLASMARIFLE_BMPS;
		HaloProjectile.HeadshotDMGFactor PLASMARIFLE_HEDMOD;
		HaloProjectile.SplashSpawner "PlasmaSplashSpawner";
		
		//RenderStyle "Add";
		// Translation "0:255=@65[10,8,240]";
		// Scale 0.12;
		
		HaloPlasma_Proj.PlasmaColor "#13afed";
		HaloPlasma_Proj.SmokeType "PlasmaSmoke_Blue";
		HaloPlasma_Proj.CoreColor1 "#1358ed";
		HaloPlasma_Proj.CoreColor2 "#FFFFFF";
		HaloPlasma_Proj.LightningEffect "PlasmaProjBiri_Blue";
	
		Alpha 0.60;
		Scale 0.65;
		
		DamageType "Plasma";
	}
	
	States
	{
		Death:
		XDeath:
		Crash:
			TNT1 A 1 
			{	
				HaloMath.ParticlesFX(self, "#13afed", 30, 3, 10);
				A_DoLightning(lightningType, 4);
			}
		stop;
	}
}
class PlasmaProjBiri_Blue : LightningBiri
{
	Default
	{
		-LightningActor.DOFLASH;
		Scale 0.02;
		Translation "0:255=@80[4,8,76]";
	}
	
	States
	{
		Spawn:
			BEAM A 1 Bright A_FadeOut(0.3);
		wait;
	}
}
class PlasmaSmoke_Blue : PlasmaSmoke
{
	Default
	{
		Translation "0:255=#[81, 77, 250]";
	}
}

class Halo_PlasmaRifle : HaloGun
{
	const LCD = 22;
	int shotcounter;
	double firespeed;
	double lcd_offspd;
	vector2 lcd_offs, lcd_offs_real;
	
	Default
	{
		//$Category "HaloDoom/Weapons"
		Weapon.SlotNumber 4;
		Obituary "%o got the boomer shooter treatment by %k's Plasma Rifle.";
		Inventory.PickupMessage	"Picked up the Type-25 Plasma Rifle.";
		Tag "Plasma Rifle";
		Weapon.BobSpeed 2.45;
		Weapon.BobRangeX 0.30;
		Weapon.AmmoType1 "Halo_PlasmaRifle_Clip";
		Weapon.AmmoType2 "Halo_PlasmaRifle_Clip";
		Weapon.AmmoGive 100;
		HaloGun.HasBattery true, 1;
		HaloGun.Faction "Covenant";
		
		HaloGun.PowerTier P_ENERGY | P_NORM;
		HaloGun.Rarity 60;
				
		// Recoil
		HaloGun.Bloom 0.16;
		HaloGun.BloomSpeed 0.30;
		HaloGun.BaseRecoil PLASMARIFLE_RECOIL;
		HaloGun.Inaccuracy PLASMARIFLE_ACCMOD;
		HaloGun.Crosshair "PlsRRet", 0.75;
		HaloGun.UIGraphic "WI_PRFLE", 0.4, 0.4;
		
		RecoilWeapon.YOffsetRange 0, 40;
	}
		
	action void A_FireHaloPlasma(bool useammo = true, bool bottom = false)
	{
		A_Light(2);
		A_WeapSound("Halo/Weapons/PlasmaRifle/Fire", 0, true);
		A_WeapSound("Halo/Weapons/PlasmaRifle/Fire/Bass", CHANF_OVERLAP, true);
		A_ShootProjectile("HaloPlasmaRifle_Proj", 7, bottom ? -10 : -2);
		invoker.heat += 0.03;
		invoker.firespeed += 0.10;
		if(useammo && ++invoker.shotcounter > 1)
		{
			A_TakeAmmo(1, false);
			invoker.shotcounter = 0;
		}
		
		let pl = SetupPlasmaLightning(16, -6, 8, scale:0.7, density:3.0, shading:"#13afed");
		if(pl) pl.particleOffs.z = (bottom ? 4 : 6) - 12;
		
		A_UpdateSpread();
	}
	
	action State A_DoTaserMelee(StateLabel taserState, int taserAmmoUse = 5)
	{
		bool hasAmmo = (CountLoadedAmmo() >= taserAmmoUse);
		string taserSound = hasAmmo ? "Halo/Weapons/PlasmaRifle/Melee/Hit" : "Halo/Melee/Punch";

		let victim = A_HaloMelee(50, 48, hitsnd:taserSound, "", "Taser", doHitThrust:false);
		if(victim && victim.health > 0 && hasAmmo) 
		{
			let victimState = victim.FindState("Pain");
			if(victimState) victim.SetState(victimState);
			victim.freezeTics = TICRATE*2;
			TESLightningEffect.AttachToActor(
				victim, 4, 0, 0, 
				scale:3.0, density:0.65, 
				shading:"#13afed", spawnFreq:2, 
				lifetime:victim.freezeTics
			);
			victim.A_GiveInventory("EMP_DeBuff", 1); // Taser effect 
			A_TakeAmmo(taserAmmoUse);
			return ResolveState(taserState);
		}
		return ResolveState(null);
	}
	
	override void DoEffect()
	{
		super.DoEffect();
		
		heat = clamp(heat, 0, 1.5);
		
		firespeed = clamp(firespeed, 0, 2);
		lcd_offspd = clamp(lcd_offspd, 0.01, 1.0);
		lcd_offs_real.x = HaloMath.Lerp(lcd_offs_real.x, lcd_offs.x, lcd_offspd); 
		lcd_offs_real.y = HaloMath.Lerp(lcd_offs_real.y, lcd_offs.y, lcd_offspd);
		
	}
	
	/*
	action void A_DisableLCD()
	{
		A_Overlay(LCD, "LCD_Off");
		A_Overlay(LCD+1, "LCD_Off");
	}
	
	action void A_LCDOffset(double x, double y, double spd = 1.0)
	{
		invoker.lcd_offs = (x,y);
		invoker.lcd_offspd = spd;
	}
	*/
		
	States
	{
		Ready:
			TNT1 A 0 A_WeapSound("Halo/Weapons/PlasmaRifle/Select");
			W4S1 ABCDEFG 1 A_DoSelectAnim();
		Ready.Active:
			W4G1 ABCDCB 1 
			{
				invoker.heat *= 0.96;
				invoker.firespeed *= 0.75;
				A_HaloWeaponReady(0);
				A_StopPlasmaLightning();
				
				/*
				if(A_CheckInScope()) 
					A_LCDOffset(-15,0);
				else
					A_LCDOffset(0,0);
					
				A_Overlay(LCD, "LCD_HeatLow");
				A_Overlay(LCD+1, "LCD_HeatHigh");
				
				uint flags = PSPF_FORCEALPHA|PSPF_ALPHA|PSPF_ADDWEAPON|PSPF_ADDBOB;
				A_OverlayFlags(LCD,  flags, true);
				A_OverlayFlags(LCD+1, flags, true);
				*/
			}
		loop;
		
		Ready.Dryfire:
			W4G1 "#" 12 A_WeapSound("Halo/Weapons/DryFire", CHANF_OVERLAP);
		goto Ready.Active;

		Select:
			TNT1 A 0 A_GunRaise();
		wait;

		Deselect:
			// TNT1 A 0 A_DisableLCD();
			W4S1 GFEDCB 1;
			W4S1 A 1 A_GunLower();
		wait;
		
		Fire:
			TNT1 "#" 0 A_JumpIf(invoker.heat >= 1.0, "Overheat");
			TNT1 "#" 0 A_JumpIf(!CountLoadedAmmo(), "Ready.Dryfire");
			W4F1 A 1 Bright
			{
				A_SetZoom(!player.refire ? 0.98 : 0.99, 1);
				A_FireHaloPlasma();
				A_SetRecoil(0.40, 0, 2);
				A_RecoilOffset(frandom[WeapFX](-2,2),frandom[WeapFX](1,3),2);
				if(!player.refire) A_RQuakeEx(2,2,2,6,0,20,"",QF_RELATIVE|QF_SCALEDOWN);
			}
			W4F1 B 1 A_Light(0);
			W4F1 C 1 Bright
			{	
				A_SetFrameTics(3 - invoker.firespeed);
				
				A_SetRecoil(-0.15, 0, 2);
				A_SetZoom(1.0, 2);
				A_RecoilOffset(0,0,2);
			}
			W4F1 D 1 
			{
				A_SetFrameTics(2 - invoker.firespeed);
				A_Light(0);
			}
		Hold:
			W4F1 D 1 A_ReFire("Fire");
			// TNT1 A 0 A_DisableLCD();
			W4F1 EF 2;
		goto Ready.Active;
		
		Overheat:
			W4R1 A 1;
			TNT1 A 0 
			{
				// A_DisableLCD();
				A_StopPlasmaLightning();
				invoker.handsbusy = true; // Disable hand actions while overheating.
				A_WeapSound("Halo/Weapons/PlasmaRifle/Overheat", CHANF_OVERLAP);
			}
			W4R1 BCD 1; 
			TNT1 A 0 A_RQuakeEx(2,2,0,12,0,20,"");
			W4R1 DEFDEFDEFDEFDEFDEFDEFDE 2 // 23 * 2 = 46 
			{
				if( random[plasmarifleRNG](0,100) <= 20 )
				{
					let pl = SetupPlasmaLightning(8, -7+random[BRifleRNG](-3,3), 10+random[BRifleRNG](-2,2), scale:0.4, density:1.5, shading:"#f52c1d", onlySpawn:true);
					if(pl) pl.lifetime = 25;
				}
					
				for(int i = 0; i < floor(4 * halodoom_effectintensity); i++) 
				{
					A_SetSFXPos(25, -20 + frandom[WeapFX](-8,8), -10 + frandom[WeapFX](-10,10));
					A_SpawnSFX("MuzzleSmoke", 0,0);
				}
				
				A_RecoilOffset(frandom[WeapFX](-2,2),frandom[WeapFX](-2,2),2, add:true);
				invoker.heat -= 0.07;
			}
			W4R1 FGHIJKL 1;
			TNT1 A 0 
			{
				invoker.heat = 0;
				invoker.firespeed = 0;
				invoker.handsbusy = false; // Enable hand actions.
			}
		goto Ready.Active;
		
		DoKick:
			TNT1 A 1 A_JumpIf(!invoker.handsbusy, "DoMelee");
		goto super::DoKick;
		
		DoMelee:
			TNT1 A 1 
			{
				let psp = player.FindPSprite(PSP_WEAPON);
				if(psp) psp.SetState(ResolveState("PlasmaRifle.BeginMelee"));
			}
		stop;

		PlasmaRifle.BeginMelee:
			"####" "#" 1; // This is needed to ensure this state is actually completely set.
			TNT1 A 0 
			{
				A_BeginMelee(false);
				A_StartSound("Halo/Weapons/PlasmaRifle/Melee", CHAN_AUTO, CHANF_OVERLAP);
			}
			W4M1 ABCDEFGHI 1;
			TNT1 A 0 A_JumpIf(random[PRMeleeRNG](0,100) >= 50, "PlasmaRifle.Uppercut");
			
		PlasmaRifle.Punch:
			W4M1 JJKLMM 1
			{
				A_SetRecoil(1.0, 0, 2);
				HaloGun.CallTryMelee(self); // Makes Parrying attacks more responsive.
			}
			W4M1 MMMMN 1 A_DoTaserMelee("PlasmaRifle.PunchTased");
		PlasmaRifle.Punch.Finish:
			W4M1 NPQ 1 A_SetRecoil(-1.5, 0, 3);
			W4M1 Q 8 A_RecoilOffset(0,60,8);
		goto PlasmaRifle.FinishMelee;
		PlasmaRifle.PunchTased:
			W4M1 MMMMMMM 1 
			{	
				A_RecoilOffset(frandom[WeapFX](-2,2),frandom[WeapFX](1,3),2);
				A_RQuakeEx(2,2,0,12,0,20,"");
			}
		goto PlasmaRifle.Punch.Finish;
		
		PlasmaRifle.Uppercut:
			W4M1 RST 1
			{
				A_SetRecoil(1.0, 0, 2);
				HaloGun.CallTryMelee(self); // Makes Parrying attacks more responsive.
			}
			W4M1 UUUUV 1 A_DoTaserMelee("PlasmaRifle.UppercutTased");
		PlasmaRifle.Uppercut.Finish:
			W4M1 VWX 1 A_SetRecoil(-1.5, 0, 3);
			W4M1 Y 8 A_RecoilOffset(0,60,8);
		goto PlasmaRifle.FinishMelee;
		PlasmaRifle.UppercutTased:
			W4M1 UUUUUUU 1 
			{	
				A_RecoilOffset(frandom[WeapFX](-2,2),frandom[WeapFX](1,3),2);
				A_RQuakeEx(2,2,0,12,0,20,"");
			}
		goto PlasmaRifle.Uppercut.Finish;
		
		PlasmaRifle.FinishMelee:
			W4S1 ABCDEFG 1 
			{
				A_FinishMelee(false);
				A_RecoilOffset(0,0,12);
			}
		goto Ready.Active;		
		
		// Weapon Status - TODO, needs new sprites.
		/*
		LCD_HeatLow:
			PSRL A 1 Bright
			{
				A_FollowRotation(OverlayID(), PSP_WEAPON, -0.05);
				A_OverlayAlpha(OverlayID(), 1.0 - invoker.heat);
				A_FollowRotatedPos(OverlayID(), PSP_WEAPON, (50,50));
				A_OverlayOffset(OverlayID(), invoker.lcd_offs_real.x, invoker.lcd_offs_real.y, WOF_ADD);
			}
		loop;
		LCD_HeatHigh:
			PSRL B 1 Bright
			{
				A_FollowRotation(OverlayID(), PSP_WEAPON, -0.05);
				A_OverlayAlpha(OverlayID(), invoker.heat);
				A_FollowRotatedPos(OverlayID(), PSP_WEAPON, (50,50));
				A_OverlayOffset(OverlayID(), invoker.lcd_offs_real.x, invoker.lcd_offs_real.y, WOF_ADD);
			}
		loop;
		
		LCD_Off:
			TNT1 A 1;
		stop;
		*/
		
		Spawn:
			PRSF A -1;
		stop;
	}
}
