class Halo_ScatterShotClip : Ammo 
{
	Default 
	{
		Inventory.MaxAmount 6;
	}
}
class Halo_ScatterShot_Reserves : Ammo
{
	mixin WorldAmmoBehavior;
	Default 
	{
		Radius 0;
		Height 0;
		Scale 0.65;

		Inventory.Amount 36;
		Inventory.MaxAmount 36;
		Inventory.Icon "";
		Inventory.PickupSound "";
		Inventory.PickupMessage "";
		Ammo.BackpackMaxAmount 36;
	}
	
	States
	{
		Spawn:
			TNT1 A -1;
		stop;
	}
}

class HaloScatterShot_Proj : HaloSlowProjectile 
{
	Color particleColor;
	
	class<LightningBiri> lightningType;
	Property LightningType : lightningType;
	Property ParticleColor : particleColor;

	Default
	{
		HaloSlowProjectile.SetRanges 0, 0; 
		HaloSlowProjectile.MinRangeDamage 100; 
		HaloSlowProjectile.BaseDamage SCATTERSHOT_DMG; 
		HaloSlowProjectile.Speed_MPS  SCATTERSHOT_BMPS;
		HaloSlowProjectile.HeadshotDMGFactor SCATTERSHOT_HEDMOD;
		HaloScatterShot_Proj.LightningType "UnmakerLightning";
		HaloScatterShot_Proj.ParticleColor "Orange";
		
		RenderStyle "Add";
		Alpha 1.0;
		Scale 0.02;
		DamageType "Plasma";
		+ROLLSPRITE;
		+INTERPOLATEANGLES;
		
		// boin boin
		BounceType "Doom";
		BounceCount 4;
		+BOUNCEONWALLS;
		+BOUNCEONFLOORS;
		+BOUNCEONCEILINGS;
		+USEBOUNCESTATE;
		-BOUNCEONACTORS;
	}
	
	virtual void A_DoLightning(double amt = 4)
	{
		vector2 view;
		for(int i = 0; i < amt; i++)
		{
			view.x = angle + frandom[ScatterRNG](-60,60) + 180;
			view.y = pitch + frandom[ScatterRNG](-35,35);
			BiriBiri.DoLightning(pos, view, type:lightningType, dist:25, 0.5, 20.0, 10.0, 30, 0);
		}
	}
	
	override void Tick()
	{
		super.Tick();
		if(level.isFrozen()) return;
		
		A_SetRoll(roll+5, SPF_INTERPOLATE);

		let trail = Spawn("HaloScatterShot_Trail", pos);
		trail.translation = translation;
	}
	
	States
	{
		Spawn:
			ELBL AB 2 Bright A_JumpIf(!bMISSILE, "Death"); // WTAF GZDoom?!?!
		loop;
		
		Bounce:
			"####" "#" 1
			{
				isHoming = true;
				homingStrength = 0.30;
				homingFOV = 30;
			}
		goto Spawn;
		
		Death:
		XDeath:
		Crash:
			TNT1 A 1 
			{	
				HaloMath.ParticlesFX(self, particleColor, 30, 3, 10);
				A_DoLightning();
			}
		stop;
	}
}

class HaloScatterShot_Trail : CheapActor
{
	Default
	{
		RenderStyle "Add";
		Alpha 1.0;
		Scale 0.02;
		+ROLLSPRITE;
		+INTERPOLATEANGLES;
		+NOGRAVITY;
	}
	
	override void Tick()
	{
		super.Tick();
		A_SetRoll(roll+5, SPF_INTERPOLATE);
		A_SetScale(Scale.X * 0.93);
		alpha *= 0.93;
		if(alpha <= 0.05) Destroy(); 
	}
	
	States
	{
		Spawn:
			ELBL AB 2 Bright;
		loop;
	}
}

class LSR_ScatterShot : LSR_BinaryRifle
{
	Default
	{
		Alpha 2.0;
		Scale 4.0;
		LaserBeam.LaserColor "Yellow"; 
		LSR_BinaryRifle.LaserDamage (SCATTERSHOT_DMG * 7.5);
		LSR_BinaryRifle.LaserFade 0.25;
		LSR_UnmakerBeam.LaserPuff "ScatterShot_OrangePuff";
		+BRIGHT;
	}
}

class ScatterShot_OrangePuff : UnmakerLaserPuff
{
	Default
	{
		UnmakerLaserPuff.laserPuffs 2, 100, 0.25;
		Translation "0:255=@64[255,145,0]";
		UnmakerLaserPuff.LightningType "ScatterShot_OrangeLightning";
	}
}
class ScatterShot_PurplePuff : UnmakerLaserPuff
{
	Default
	{
		UnmakerLaserPuff.laserPuffs 2, 100, 0.25;
		Translation "0:255=@64[195,0,255]";
		UnmakerLaserPuff.LightningType "ScatterShot_PurpleLightning";
	}
}
class ScatterShot_OrangeLightning : LightningBiri
{
	Default
	{
		Translation "0:255=@64[255,145,0]";	
	}
}
class ScatterShot_PurpleLightning : LightningBiri
{
	Default
	{
		Translation "0:255=@64[195,0,255]";
	}
}
class HaloScatterShot_ProjOrange : HaloScatterShot_Proj
{
	Default
	{
		Translation "0:255=@64[255,145,0]";
		HaloScatterShot_Proj.LightningType "ScatterShot_OrangeLightning";
		HaloScatterShot_Proj.ParticleColor "Orange";
	}
}
class HaloScatterShot_ProjPurple : HaloScatterShot_Proj
{
	Default
	{
		Translation "0:255=@64[195,0,255]";
		HaloScatterShot_Proj.LightningType "ScatterShot_PurpleLightning";
		HaloScatterShot_Proj.ParticleColor "Purple";
	}
}

class Halo_ScatterShot : HaloGun
{
	Default
	{
		//$Category "HaloDoom/Weapons"
		Weapon.SlotNumber 5;
		Obituary "%o's atoms were scattered by %k's Scatter Shot.";
		Inventory.PickupMessage	"Picked up the Scatter Shot.";
		Tag "Scatter Shot";
		Weapon.BobSpeed 2.45;
		Weapon.BobRangeX 0.63;
		Weapon.AmmoType1 "Halo_ScatterShot_Reserves";
		Weapon.AmmoType2 "Halo_ScatterShotClip";
		Weapon.AmmoGive 36;
		HaloGun.Faction "Forerunner";
		
		HaloGun.PowerTier P_MID;
		HaloGun.Rarity 10;
				
		// Recoil
		RecoilWeapon.RecoilSpeed 20;
		HaloGun.Bloom 1.25;
		HaloGun.BloomSpeed 0.08;
		HaloGun.BaseRecoil 1;
		HaloGun.Inaccuracy 1;
		HaloGun.Crosshair "SSRet", 1.0;
		HaloGun.UIGraphic "MISSNG", 0.8, 0.7;
		
		/*
			HaloGun.UISight "SCSGADS", 1.5, 1.0;
			HaloGun.SetupScope 1.25, 0.5;
			+HaloGun.SI_Fullscreen;
			+HaloGun.SI_Rotate;
			+HaloGun.SI_AlwaysHide;
			HaloGun.ZoomSounds "Halo/Weapons/ScatterShot/Zoom/IN", "Halo/Weapons/ScatterShot/Zoom/OUT";
		*/
	
		RecoilWeapon.YOffsetRange -10, 20;
	}
		
	override int GetPowerTier()
	{	
		if(HaloPlayer.IsGameType("SpartanOverkill")) return P_NORM | P_MID;
		return super.GetPowerTier();
	}
	
	action void A_FireSpreadShots(class<HaloScatterShot_Proj> projType = "HaloScatterShot_Proj", vector2 offs = (8, -4), double fireAngle = 0, double spacing = 5, double projAmt = 5)
	{
		double soffs = -spacing;
		vector3 aimpos = HaloMath.getPlayerAim(PlayerPawn(self));
		for(int i = 0; i < projAmt; i++)
		{
			vector2 spread = (soffs, 0);
			spread = RotateVector(spread, fireAngle);
			spread.y += 1.2;
			
			vector3 firepos; Actor proj;
			[firepos, proj] = A_ShootProjectile(projType, offs.x, offs.y);
			if(proj) HaloSlowProjectile(proj).DoConverge(aimpos, spread);
			
			soffs += (spacing*0.5);
		}
	}
	
	action void A_FireScatterShot()
	{
		A_Light(4);
		A_WeapSound("Halo/Weapons/ScatterShot/Fire", CHANF_OVERLAP);
		A_WeapSound("Halo/Weapons/ScatterShot/Fire/Bass", CHANF_OVERLAP);
		
		class<HaloScatterShot_Proj> projTypes[2] = 
		{
			"HaloScatterShot_ProjOrange",
			"HaloScatterShot_ProjPurple"
		};
		
		double spread = 3;
		double xoffs = 14;
		double amt = 6;
		
		for(int ang = 0; ang < 360; ang += ceil(360/amt))
			A_FireSpreadShots(projTypes[random[ScShProj](0,1)], (xoffs, 0), ang, spread, 1);
		
		Color plasCol = random[ScLGC](0,1) ? "#FF9100" : "#C300FF";
		let pl = SetupPlasmaLightning(16, -6, 8, scale:0.45, density:1.5, shading:plasCol);
		if(pl) pl.lifetime = 16;
		
		A_TakeAmmo(1);
		A_UpdateSpread();
	}
	
	action void A_FireChargeShot(double spacing = 1)
	{
		A_Light(4);
		A_WeapSound("Halo/Weapons/ScatterShot/Charge/Fire", CHANF_OVERLAP);
		A_WeapSound("Halo/Weapons/ScatterShot/Charge/Fire/Bass", CHANF_OVERLAP);
		
		Color laserColor[2] =
		{
			"Orange",
			"Purple"
		};
		class<UnmakerLaserPuff> puffs[2] = 
		{
			"ScatterShot_OrangePuff",
			"ScatterShot_PurplePuff"
		};
		
		vector3 loffs = (7, 2, -2);
		int curAmmo = CountLoadedAmmo();
		for(int i = 0; i < min(2, curAmmo); i++)
		{
			let beam = LSR_ScatterShot(LaserBeam.Create(self, loffs.x,loffs.y,loffs.z, type:"LSR_ScatterShot"));
			let beamCore = LSR_BinaryRifleCore(LaserBeam.Create(self, loffs.x,loffs.y,loffs.z, type:"LSR_BinaryRifleCore"));
			
			beam.shade = laserColor[i];
			beam.puffType = puffs[i];
			
			beamCore.puffType = puffs[i];
			beamCore.fadeAmt = beam.fadeAmt;
			beamCore.A_SetScale(beam.default.Scale.x * 0.5);
			
			beam.setEnabled(true);
			beamCore.setEnabled(true);
			loffs.y += spacing;
			A_TakeAmmo(1);
		}
		
		Color plasCol = random[ScLGC](0,1) ? "#FF9100" : "#C300FF";
		let pl = SetupPlasmaLightning(16, -6, 8, scale:0.45, density:1.5, shading:plasCol);
		if(pl) pl.lifetime = 16;
	}

	States
	{
		
		Ready:
			TNT1 A 0 A_WeapSound("Halo/Weapons/ScatterShot/Draw");
			WQD1 HGFEDCBA 1 A_DoSelectAnim();
		Ready.Active:
			WQI1 A 1 
			{
				A_HaloWeaponReady(WRF_ALLOWRELOAD, usescope:false);
				if(A_CheckInScope()) A_ResetSightGraphic();
				A_StopPlasmaLightning();
			}
		loop;
		
		Ready.Dryfire:
			WQI1 A 4 A_WeapSound("Halo/Weapons/DryFire", CHANF_OVERLAP);
		goto Ready.Active;

		Select:
			TNT1 A 1 A_GunRaise();
		wait;

		Deselect:
			WQS1 ABCDEFGH 1;
			WQS1 H 1 A_GunLower();
		wait;
		
		Fire:
			TNT1 A 0 A_GunCheckReload();
			WQF1 A 1 Bright;
			WQF1 B 1 Bright
			{
				A_SetZoom(0.92, 2);
				A_SetRecoil(3.00, 0, 2);
				A_FireScatterShot();
				A_RollQuake(2,10,2);
				A_RecoilOffset(4, -15, 2, add:true);
			}
			WQF1 C 2 Bright A_SetZoom(1.0, 6);
			WQF1 D 1 Bright
			{	
				A_WeapSound("Halo/Weapons/ScatterShot/Fire/Mech", CHANF_OVERLAP);
				A_RecoilOffset(1, 30, 2, add:true);
				A_Light(0);
			}
			WQF1 EEEEE 1 A_RecoilOffset(1, 25, 2, add:true);
			WQF1 EFGHIJ 2 A_RecoilOffset(0,0,8);
		goto Ready.Active;
		
		AltFire:
			TNT1 A 0 A_GunCheckReload();
			TNT1 A 0 A_WeapSound("Halo/Weapons/ScatterShot/Charge/Begin");
			WQC1 ABCDEFGH 2 
			{
				bool doAbortCharge = A_ButtonStatus(BT_ALTATTACK, BTS_UP);
				if(doAbortCharge) A_WeapSound("Halo/Weapons/ScatterShot/Charge/End");
				return A_JumpIf(doAbortCharge, "AltFire.AbortCharge");
			}
		AltFire.ChargeFire:
			WQC1 I 1 Bright
			{
				A_SetZoom(0.88, 2);
				A_RollQuake(4,10,2);
				A_FireChargeShot();
			}
			WQC1 J 1 Bright 
			{
				A_SetRecoil(5.0, 0, 2);
				A_WeapSound("Halo/Weapons/ScatterShot/Charge/End");
			}
			WQC1 KLMN 1
			{
				A_SetZoom(1.0, 8);
				A_Light(0);
				A_RecoilOffset(5, 25, 2, add:true);
			}
			WQC1 OOOOOOOOOOPPQQRR 1 A_RecoilOffset(0,0,8);
			TNT1 A 0 A_GotoState("Ready.Active");
		AltFire.AbortCharge:
			WQC1 "#" 2;
			TNT1 "#" 0
			{
				int curFrame = A_GetFrame();
				A_SetFrame(curFrame - 1);
				
				if(curFrame > 0)
					return ResolveState("AltFire.AbortCharge");
				else
					return ResolveState("Ready.Active");
			}
		goto Ready.Active;
		
		Reload:
			TNT1 A 0 A_ValidateReload("Ready.Dryfire");
			TNT1 A 0 
			{
				A_StartSound("Halo/Weapons/ScatterShot/Reload/Background", CHAN_RELOADING, CHANF_OVERLAP);
				A_StartSound("Halo/Weapons/ScatterShot/Reload/Start", CHAN_RELOADING, CHANF_OVERLAP);
			}
			WQR1 ABCDEF 2;
		Reload.Loop:
			TNT1 A 0 A_StartSound("Halo/Weapons/ScatterShot/Reload/Single", CHAN_RELOADING, CHANF_OVERLAP);
			WQR1 GGGGGGGGGGGGGG 1 A_RecoilOffset(frandom[ScShake](-3,3), frandom[ScShake](-3,3), 2, add:true);
			TNT1 A 0 A_ReloadAmount(1);
			TNT1 A 0 A_ValidateReload("Reload.Finish");
			TNT1 A 0 
			{
				bool doAbortReload = A_ButtonStatus(BT_ATTACK, BTS_DOWN);
				if(doAbortReload) A_StopSound(CHAN_RELOADING);
				return A_JumpIf(doAbortReload, "Ready.Active");
			}
			TNT1 A 0 A_GotoState("Reload.Loop");
		Reload.Finish:
			TNT1 A 0 
			{
				A_StopSound(CHAN_RELOADING);
				A_StartSound("Halo/Weapons/ScatterShot/Reload/End", CHAN_RELOADING);
			}
			WQR1 FEDCBA 2 A_RecoilOffset(0,0,12);
		goto Ready.Active;
		
		Spawn:
			WQP1 A -1;
		stop;
	}
}
