class Halo_SentinelBeam_Battery : Ammo 
{
	Default 
	{
		Inventory.MaxAmount 50;
	}
}

class Halo_SentinelBeam_Reserves : Ammo 
{
	Default 
	{
		Inventory.MaxAmount 300;
	}
}


class SentinelBeamDecal : LaserBeamDecal
{
	Default
	{
		Translation "0:255=@64[233, 240, 48]";
	}
}

class Halo_SentinelBeam : HaloGun
{
	const SND_BEAM = 21;
	const SND_BEAMHIT = 22;
	double beamTics; // used for ammo consumption.
	MBeamSpawner beam;

	Default
	{
		//$Category "HaloDoom/Weapons"
		Weapon.SlotNumber 6;
		Obituary "%o was disintigrated by %k's Sentinel Beam.";
		Inventory.PickupMessage	"Picked up the Sentinel Beam.";
		Tag "Sentinel Beam";
		Weapon.BobSpeed 2.0;
		Weapon.BobRangeX 0.55;
		Weapon.AmmoType1 "Halo_SentinelBeam_Reserves";
		Weapon.AmmoType2 "Halo_SentinelBeam_Battery";
		Weapon.AmmoGive 100;
		HaloGun.HasBattery true, 1;
		HaloGun.Faction "Forerunner";
		
		HaloGun.PowerTier P_POWER | P_ENERGY;
				
		// Recoil
		HaloGun.Bloom 0.16;
		HaloGun.BloomSpeed 0.30;
		HaloGun.BaseRecoil 1;
		HaloGun.Inaccuracy 1;
		HaloGun.Crosshair "BeamRet", 0.75;
		HaloGun.UIGraphic "WI_BEAM", 0.6, 0.6;
			
		RecoilWeapon.YOffsetRange 0, 40;
	}
	
	override int GetPowerTier()
	{	
		if(HaloPlayer.IsGameType("SpartanOverkill")) return P_STRONG | P_ENERGY;
		return super.GetPowerTier();
	}

	action bool A_CheckTarget(Actor act, double range = 800)
	{
		// Ensure the target isn't too far away.
		return !act ? false : Distance3D(act) <= range;
	}
	
	action Actor A_FindTarget()
	{
		let haloplr = HaloPlayer(self);
		if(!haloplr) return NULL;
		
		let targ = haloplr.aimActor_nearest;
		return A_CheckTarget(targ) ? targ : NULL;
	}
	
	action void A_StopBeam()
	{
		A_StopSound(SND_BEAM);
		A_StopSound(SND_BEAMHIT);
		if(!invoker.beam || !invoker.beam.isActive()) return;
		invoker.beam.Disable();
		
		A_WeapSound("Halo/Weapons/SentinelBeam/Fire/End", CHANF_OVERLAP);
	}
	
	action void A_FireBeam(double fw = 8, double lr = -2.5, double ud = -4.25)
	{
		invoker.beamTics = 0;
		if(!invoker.beam)
			invoker.beam = MBeamSpawner.Create(self, fw, lr, ud, cooktime:20, size:3.5);
		else
			invoker.beam.srcOffs = (fw, lr, ud);
			
		invoker.beam.BobWithWeapon = true;
		invoker.beam.Enable(A_FindTarget());
	}
	
	action void A_BeamVFX(Color outerColor, Color innerColor, double outerScale, double innerScale)
	{
		if(!invoker.beam) return;
		invoker.beam.SetupVisuals(outerColor, innerColor, outerScale, innerScale);
	}
	
	override void DrawCrosshairUI(double dT)
	{
		uint flags = HLSBS.SS_NOASPECTCORRECTION;

		double scale = 1.0;
		vector2 drawPos = (0,32);
		vector2 midPos = (1920/2., 1080/2.);
		double maxWidth = (64 * scale) - 15;
		double hue = HaloMath.Lerp(60, 0, min(1.0,heat));
		Color barTint = HLStatusColor.HSLtoRGB(max(1,hue) / 360.0, 0.9, 0.5);
		
		HLSBS.DrawImage("Graphics/UI/Weapons/SentinelBeam_HeatGauge.png", drawPos, flags | HLSBS.SS_SCREEN_CENTER, scale:(scale,scale));
		
		HLSBS.SetClipRect( 
			(midPos.x+drawPos.x - (maxWidth / 2.0)) + 2, 
			midPos.y+drawPos.y - 8, 
		    (maxWidth * heat), 
			20, flags, 
			visual:false
		);
		HLSBS.DrawImage(
			"Graphics/UI/Weapons/SentinelBeam_HeatBar.png", 
			drawPos, flags | HLSBS.SS_SCREEN_CENTER, 
			scale:(scale,scale), 
			tint:barTint
		);
		HLSBS.ClearClipRect();
	}
	
	override void DoEffect()
	{
		super.DoEffect();
		heat = clamp(heat, 0, 1.0);
	}
	
	override void OnDropSwap()
	{
		super.OnDropSwap();
		A_StopSound(SND_BEAM);
	}
	
	States
	{
		DoSmoke:	
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 3 
			{
				let psp = player.FindPSprite(OverlayID());
				if(psp) psp.frame = random[WeapFX](3,8);
				A_SetSFXPos(25,-8,-10);
				double amt = (invoker.heat * 5) * halodoom_effectintensity;
				
				for(int i = 0; i < floor(amt); i++)
					A_SpawnSFX("MuzzleSmoke", 0,0);
			}
		stop;
	
		Ready:
			TNT1 A 0 A_WeapSound("Halo/Weapons/SentinelBeam/Draw");
			WYD1 ABCD 1 A_DoSelectAnim(0, true);
		goto Ready.Active;
		
		Ready.Active:
			WYG1 A 1 
			{
				invoker.heat *= 0.96;
				A_HaloWeaponReady(WRF_ALLOWRELOAD, usescope:false);
				A_Overlay(69, "DoSmoke");
			}
		loop;
		
		Ready.Dryfire:
			WYG1 A 12 A_WeapSound("Halo/Weapons/DryFire", CHANF_OVERLAP);
		goto Ready.Active;

		Select:
			TNT1 A 0 A_GunRaise();
		wait;

		Deselect:
			TNT1 A 0 A_StopBeam();
			WYD1 DCBA 1;
			WLS1 G 1 A_GunLower();
		wait;
		
		Fire:
			TNT1 A 0 A_JumpIf(invoker.heat >= 1.0, "Overheat");
			TNT1 A 0 A_JumpIf(!CountLoadedAmmo(), "Ready.Dryfire");
			WYF1 A 1 
			{
				A_WeapSound("Halo/Weapons/SentinelBeam/Fire/Begin", CHANF_OVERLAP);
				A_SetZoom(0.92, 2);
				A_FireBeam();
			}
			TNT1 A 0 A_BeamVFX("fcf630", "fffb87", 0.8, 0.30);
			WYF1 BCDE 1;
		Beam.Hold:
			WYF1 E 1 A_RecoilOffset(frandom[SenBeamFX](-4,4), frandom[SenBeamFX](-4,4), 3, add:false);
			TNT1 A 0 
			{
				// Recoil
				A_SetZoom(1.0, 6);
				A_RollQuake(1,12,2);
				
				// Fire sound loop
				A_StartSound("Halo/Weapons/SentinelBeam/Fire/Loop", SND_BEAM, CHANF_LOOPING);
				
				if(!invoker.beam || !invoker.beam.isActive() || !CountLoadedAmmo()) 
					return ResolveState("Beam.Halt");
					
				bool hitWall = invoker.beam.DoMBeamDecal("SentinelBeamDecal");
				if(hitWall) 
					A_StartSound("Halo/Weapons/SentinelBeam/Fire/SurfaceHit", SND_BEAMHIT, CHANF_LOOPING);
				else
					A_StopSound(SND_BEAMHIT);
					
				// Consume ammo and generate heat.
				invoker.beamTics++;
				if(invoker.beamTics >= 8)
				{
					A_TakeAmmo(1);
					invoker.beamTics = 0;
				}
				invoker.heat += 1.0 / (35 * 3.0); // 3 seconds of fire time.
				
				// Overheat if needed
				if(invoker.heat >= 1.0)
				{
					A_StopBeam();
					return ResolveState("Overheat");
				}
					
				let availableTarget = A_FindTarget();
				if(!invoker.beam.getTarget() && availableTarget)
					invoker.beam.SetTarget(availableTarget);
					
				return A_RefireState("Beam.Hold");
			}
		Beam.Halt:
			WYF1 D 1 A_StopBeam();
			WYF1 CBA 1;
		goto Ready.Active;
		
		Reload:
			TNT1 A 0 A_ValidateReload("Ready.Dryfire");
			TNT1 A 0 A_StopBeam();
			TNT1 A 0 A_WeapSound("Halo/Weapons/SentinelBeam/Reload/Begin", CHANF_OVERLAP);
			WYH1 ABCD 2;
			TNT1 A 0 A_StartSound("Halo/Weapons/SentinelBeam/Reload/Loop", CHAN_VOICE, CHANF_LOOPING);
			WYH1 DDDDDDDDDDDDDDDDD 4
			{	
				A_RecoilOffset(frandom[SenBeamFX](-6,6), frandom[SenBeamFX](-6,6), 6);
				A_ReloadAmount(3);
				return A_ValidateReload("Reload.Finish");
			}
		Reload.Finish:
			TNT1 A 0 
			{
				A_WeapSound("Halo/Weapons/SentinelBeam/Reload/End", CHANF_OVERLAP);
				A_StopSound(CHAN_VOICE);
			}
			WYH1 DEFGG 2;
		goto Ready.Active;
		
		Overheat:
			TNT1 A 0 
			{
				invoker.handsbusy = true; // Disable hand actions while overheating
				return A_JumpIf(invoker.heat < 0.5, "Ready.Dryfire");
			}
			TNT1 A 0 A_WeapSound("Halo/Weapons/SentinelBeam/Overheat/Start", CHANF_OVERLAP);
			WYH1 ABCD 1 Bright;
			TNT1 A 0 A_RollQuake(2,35,1);
			TNT1 A 0 A_StartSound("Halo/Weapons/SentinelBeam/Overheat/Loop", CHAN_VOICE, CHANF_LOOPING);
			WYH1 DDDDDDDDDDDDDDDDDDDDDDDDDDDDD 2 Bright
			{
				A_RecoilOffset(frandom[SenBeamFX](-8,8), frandom[SenBeamFX](-8,8), 3);
				for(int i = 0; i < floor(4 * halodoom_effectintensity); i++) 
				{
					A_SetSFXPos(25, -20 + frandom[WeapFX](-8,8), -10 + frandom[WeapFX](-10,10));
					A_SpawnSFX("MuzzleSmoke", 0,0);
				}
				invoker.heat -= 0.04;
			}
			TNT1 A 0 
			{
				A_WeapSound("Halo/Weapons/SentinelBeam/Overheat/End", CHANF_OVERLAP);
				A_StopSound(CHAN_VOICE);
			}
			WYH1 D 8;
			WYH1 EFG 2;
			TNT1 A 0 
			{
				invoker.heat = 0;
				invoker.handsbusy = false; // Enable hand actions.
			}
		goto Ready.Active;
					
		Spawn:
			WYS1 A -1;
		stop;
	}
}
