class Halo_SentinelBeam_Battery : Ammo 
{
	Default 
	{
		Inventory.MaxAmount 100;
	}
}

class Halo_SentinelBeam_Reserves : Ammo 
{
	Default 
	{
		Inventory.MaxAmount 400;
	}
}

class SentinelBeamDecal : LaserBeamDecal
{
	Default
	{
		Translation "0:255=@64[233, 240, 48]";
	}
}

class SentinelBeamSpawner : MBeamSpawner
{
	override void OnCooked(Actor victim)
	{
		let spawnPos = getOffsetPos(victim, destOffs);
		let expl = Actor.Spawn("SentinelBeamExplosion", spawnPos);
		if(expl) expl.target = src;				
	}
}

class Halo_SentinelBeam : HaloGun
{
	const SND_BEAM = 21;
	const SND_BEAMHIT = 22;
	ui double curCook; // Current cooking status of the targetted enemy, interpolated to the actual value.
	double beamTics; // used for ammo consumption.
	double beamColorTics; // used to colorize the beam over time.
	MBeamSpawner beam;

	Default
	{
		//$Category "HaloDoom/Weapons"
		Weapon.SlotNumber 6;
		Obituary "%o was disintigrated by %k's Sentinel Beam.";
		Inventory.PickupMessage	"Picked up the Sentinel Beam.";
		Tag "Sentinel Beam";
		Weapon.BobSpeed 2.45;
		Weapon.BobRangeX 0.55;
		Weapon.AmmoType1 "Halo_SentinelBeam_Reserves";
		Weapon.AmmoType2 "Halo_SentinelBeam_Battery";
		Weapon.AmmoGive 200;
		HaloGun.HasBattery true, 1;
		HaloGun.Faction "Forerunner";
		
		HaloGun.PowerTier P_POWER | P_ENERGY;
				
		// Recoil
		HaloGun.Bloom 0.16;
		HaloGun.BloomSpeed 0.30;
		HaloGun.BaseRecoil 1;
		HaloGun.Inaccuracy 1;
		HaloGun.Crosshair "SBRet", 0.6;
		HaloGun.UIGraphic "MISSNG", 0.6, 0.6;
			
		RecoilWeapon.YOffsetRange 0, 40;
	}
	
	override int GetPowerTier()
	{	
		if(HaloPlayer.IsGameType("SpartanOverkill")) return P_STRONG | P_ENERGY;
		return super.GetPowerTier();
	}

	action bool A_CheckTarget(Actor act, double range = 800)
	{
		// Ensure the target isn't too far away, or behind geometry, or even a fuckin inventory item apparently...
		if(!act || !act.bSHOOTABLE || act.bNOBLOCKMAP || (act is "Inventory")) return false;
		if(!isVisible(act, true) || !CheckSight(act, SF_SEEPASTSHOOTABLELINES | SF_SEEPASTBLOCKEVERYTHING)) return false;
		return !act ? false : Distance3D(act) <= range;
	}
	
	action Actor A_FindTarget()
	{
		let haloplr = HaloPlayer(self);
		if(!haloplr) return NULL;
		
		let targ = haloplr.aimActor_nearest;
		return A_CheckTarget(targ) ? targ : NULL;
	}
	
	action void A_StopBeam()
	{
		A_StopSound(SND_BEAM);
		A_StopSound(SND_BEAMHIT);
		if(!invoker.beam || !invoker.beam.isActive()) return;
		invoker.beam.Disable();
		invoker.beamColorTics = 0;
	
		A_WeapSound("Halo/Weapons/SentinelBeam/Fire/End", CHANF_OVERLAP);
	}
	
	action void A_FireBeam(double fw = 4, double lr = -2.5, double ud = -4.25)
	{
		invoker.beamTics = 0;
		if(!invoker.beam)
			invoker.beam = MBeamSpawner.Create(self, fw, lr, ud, cooktime:12, size:3.5, "SentinelBeamSpawner");
		else
			invoker.beam.srcOffs = (fw, lr, ud);
			
		invoker.beam.BobWithWeapon = true;
		invoker.beam.Enable(A_FindTarget());
	}
	
	action void A_BeamVFX(Color outerColor, Color innerColor, double outerScale, double innerScale)
	{
		if(!invoker.beam) return;
		invoker.beam.SetupVisuals(outerColor, innerColor, outerScale, innerScale);
	}
	
	override void DrawCrosshairUI(double dT)
	{
		uint flags = HLSBS.SS_NOASPECTCORRECTION;

		if(!beam || !beam.getTarget() || !beam.getCurrentCookStatus())
		{
			curCook = HaloMath.Lerp(curCook, 0, 0.5 * dT);
			return;
		}
		
		let cookStatus = beam.getCurrentCookStatus();
		double desiredCook = (2 * sqrt(cookStatus.cookedPerc * 0.8)) / 1.73205;
		curCook = HaloMath.Lerp(curCook, desiredCook, 0.5 * dT);
		
		double scale = 1.0;
		vector2 drawPos = (0,32);
		vector2 midPos = (1920/2., 1080/2.);
		double maxWidth = (64 * scale) - 15;
		double hue = HaloMath.Lerp(60, 0, min(1.0,curCook));
		Color barTint = HLStatusColor.HSLtoRGB(max(1,hue) / 360.0, 0.9, 0.5);
		
		HLSBS.DrawImage("Graphics/UI/Weapons/SentinelBeam_HeatGauge.png", drawPos, flags | HLSBS.SS_SCREEN_CENTER, scale:(scale,scale));
		
		HLSBS.SetClipRect( 
			(midPos.x+drawPos.x - (maxWidth / 2.0)) + 2, 
			midPos.y+drawPos.y - 8, 
		    (maxWidth * curCook), 
			20, flags, 
			visual:false
		);
		HLSBS.DrawImage(
			"Graphics/UI/Weapons/SentinelBeam_HeatBar.png", 
			drawPos, flags | HLSBS.SS_SCREEN_CENTER, 
			scale:(scale,scale), 
			tint:barTint
		);
		HLSBS.ClearClipRect();
	}
	
	override void DoEffect()
	{
		super.DoEffect();
		heat = clamp(heat, 0, 1.0);
	}
	
	override void OnDropSwap()
	{
		super.OnDropSwap();
		A_StopSound(SND_BEAM);
	}
	
	States
	{
		DoSmoke:	
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 3 
			{
				let psp = player.FindPSprite(OverlayID());
				if(psp) psp.frame = random[WeapFX](3,8);
				A_SetSFXPos(25,-8,-10);
				double amt = (invoker.heat * 5) * halodoom_effectintensity;
				
				for(int i = 0; i < floor(amt); i++)
					A_SpawnSFX("MuzzleSmoke", 0,0);
			}
		stop;
	
		Ready:
			TNT1 A 0 A_WeapSound("Halo/Weapons/SentinelBeam/Draw");
			WYD1 ABCD 1 A_DoSelectAnim(0, true);
		goto Ready.Active;
		
		Ready.Active:
			WYG1 A 1 
			{
				invoker.heat *= 0.98;
				A_HaloWeaponReady(WRF_ALLOWRELOAD, usescope:false);
				A_Overlay(69, "DoSmoke");
			}
		loop;
		
		Ready.Dryfire:
			WYG1 A 12 A_WeapSound("Halo/Weapons/DryFire", CHANF_OVERLAP);
		goto Ready.Active;

		Select:
			TNT1 A 0 A_GunRaise();
		wait;

		Deselect:
			TNT1 A 0 A_StopBeam();
			WYD1 DCBA 1;
			WLS1 G 1 A_GunLower();
		wait;
		
		Fire:
			TNT1 A 0 A_JumpIf(invoker.heat >= 1.0, "Overheat");
			TNT1 A 0 A_JumpIf(!CountLoadedAmmo(), "Ready.Dryfire");
			WYF1 A 1 
			{
				A_WeapSound("Halo/Weapons/SentinelBeam/Fire/Begin", CHANF_OVERLAP);
				A_SetZoom(0.92, 2);
				A_FireBeam();
				A_BeamVFX("fff830", "fcf886", 1.0, 1.0);
				A_TakeAmmo(1);
			}
			WYF1 BCDE 1;
		Beam.Hold:
			WYF1 E 1 A_RecoilOffset(frandom[SenBeamFX](-4,4), frandom[SenBeamFX](-4,4), 3, add:false);
			TNT1 A 0 
			{
				// Recoil
				A_SetZoom(1.0, 6);
				A_RollQuake(1,12,2);
				invoker.beamColorTics++;
				
				/*
				double fromHue = 60 / 360.0;
				double toHue = 280 / 360.0;
				double outerSat = 0.81;
				double innerSat = 0.47;
				double osc = (invoker.beamColorTics * 5.0) + 270;
				double curHue = HaloMath.fmap(sin(osc), -1.0, 1.0, fromHue, toHue);
				Color outerColor = HLStatusColor.HSLtoRGB(curHue, outerSat, 0.5);
				Color innerColor = HLStatusColor.HSLtoRGB(curHue, innerSat, 0.5);
				A_BeamVFX(outerColor, innerColor, 1.0, 1.0);
				*/
						
				// Fire sound loop
				A_StartSound("Halo/Weapons/SentinelBeam/Fire/Loop", SND_BEAM, CHANF_LOOPING);
				
				if(!invoker.beam || !invoker.beam.isActive() || !CountLoadedAmmo()) 
					return ResolveState("Beam.Halt");
					
				bool hitWall = invoker.beam.DoMBeamDecal("SentinelBeamDecal");
				if(hitWall) 
					A_StartSound("Halo/Weapons/SentinelBeam/Fire/SurfaceHit", SND_BEAMHIT, CHANF_LOOPING);
				else
					A_StopSound(SND_BEAMHIT);
					
				// Lightning effect on target
				let curTarget = invoker.beam.getTarget();
				if( curTarget && !(invoker.beamTics%2) ) 
				{
					let cookStatus = invoker.beam.getCurrentCookStatus();
					if(cookStatus)
					{
						TESLightningEffect.AttachToActor(
							curTarget, 
							invoker.beam.destOffs.x, invoker.beam.destOffs.y, invoker.beam.destOffs.z,
							3.0, (1.0 - cookStatus.cookedPerc), "fcf630", 6, 75, lifetime:2
						);
					}
				}
					
				// Consume ammo and generate heat.
				invoker.beamTics++;
				if(invoker.beamTics >= 4)
				{
					A_TakeAmmo(1);
					invoker.beamTics = 0;
				}
				invoker.heat += 1.0 / (35 * 5.0); // 5 seconds of fire time.
				
				// Overheat if needed
				if(invoker.heat >= 1.0)
				{
					A_StopBeam();
					return ResolveState("Overheat");
				}
					
				let availableTarget = A_FindTarget();
				if(!curTarget && availableTarget)
					invoker.beam.SetTarget(availableTarget);
					
				return A_RefireState("Beam.Hold");
			}
		Beam.Halt:
			WYF1 D 1 A_StopBeam();
			WYF1 CBA 1;
		goto Ready.Active;
		
		Reload:
			TNT1 A 0 A_ValidateReload("Ready.Dryfire");
			TNT1 A 0 A_StopBeam();
			TNT1 A 0 A_WeapSound("Halo/Weapons/SentinelBeam/Reload/Begin", CHANF_OVERLAP);
			WYH1 ABCD 2;
			TNT1 A 0 A_StartSound("Halo/Weapons/SentinelBeam/Reload/Loop", CHAN_VOICE, CHANF_LOOPING);
			WYH1 DDDDDDDDDDDDDDDDD 4
			{	
				A_RecoilOffset(frandom[SenBeamFX](-6,6), frandom[SenBeamFX](-6,6), 6);
				A_ReloadAmount(6);
				return A_ValidateReload("Reload.Finish");
			}
		Reload.Finish:
			TNT1 A 0 
			{
				A_WeapSound("Halo/Weapons/SentinelBeam/Reload/End", CHANF_OVERLAP);
				A_StopSound(CHAN_VOICE);
			}
			WYH1 DEFGG 2;
		goto Ready.Active;
		
		Overheat:
			TNT1 A 0 
			{
				invoker.handsbusy = true; // Disable hand actions while overheating
				return A_JumpIf(invoker.heat < 0.5, "Ready.Dryfire");
			}
			TNT1 A 0 A_WeapSound("Halo/Weapons/SentinelBeam/Overheat/Start", CHANF_OVERLAP);
			WYH1 ABCD 1 Bright;
			TNT1 A 0 A_RollQuake(2,35,1);
			TNT1 A 0 A_StartSound("Halo/Weapons/SentinelBeam/Overheat/Loop", CHAN_VOICE, CHANF_LOOPING);
			WYH1 DDDDDDDDDDDDDDDDDDDDDDDDDDDDD 2 Bright
			{
				A_RecoilOffset(frandom[SenBeamFX](-8,8), frandom[SenBeamFX](-8,8), 3);
				for(int i = 0; i < floor(4 * halodoom_effectintensity); i++) 
				{
					A_SetSFXPos(25, -20 + frandom[WeapFX](-8,8), -10 + frandom[WeapFX](-10,10));
					A_SpawnSFX("MuzzleSmoke", 0,0);
				}
				invoker.heat -= 0.04;
			}
			TNT1 A 0 
			{
				A_WeapSound("Halo/Weapons/SentinelBeam/Overheat/End", CHANF_OVERLAP);
				A_StopSound(CHAN_VOICE);
			}
			WYH1 D 8;
			WYH1 EFG 2;
			TNT1 A 0 
			{
				invoker.heat = 0;
				invoker.handsbusy = false; // Enable hand actions.
			}
		goto Ready.Active;
					
		Spawn:
			WYS1 A -1;
		stop;
	}
}

class SentinelBeamExplosion : CheapActor
{	
	double freezeWait;
	Default
	{
		Scale 1.0;
	}
	
	override void Tick()
	{
		super.Tick();
		if(target && freezeWait > 0)
		{
			freezeWait--;
			target.player.cheats |= CF_INTERPVIEW;
			if(!multiplayer) Level.SetFrozen(true);
			
			// Freeze PSprites
			let pspr = target.player.psprites;
			while (pspr)
			{
				pspr.Tics = -1;
				pspr = pspr.Next;
			}
			
			if(freezeWait <= 0)
			{
				// Resume PSprites
				let pspr = target.player.psprites;
				while (pspr)
				{
					pspr.Tics = 1;
					pspr = pspr.Next;
				}
				if(!multiplayer) Level.SetFrozen(false);
			}
		}
	}
	
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 35
			{
				let expl = Spawn("UnmakerBallExplosion", pos);
				expl.A_SetScale(scale.x * 0.25);
				let shock = Spawn("FX_Shockwave", pos);
				shock.A_SetScale(scale.x);
				let flare = Spawn("UnmakerBallFlare", pos);
				flare.A_SetScale(scale.x);

				A_StartSound("Halo/Weapons/Unmaker/BFG/Explode", CHAN_VOICE, flags:CHANF_OVERLAP);
				A_StartSound("Halo/Weapons/BeamRifle/Laser/Fire", CHAN_VOICE, flags:CHANF_OVERLAP);
				
				vector3 randPos = (frandom[CoilLightRNG](-1,1),frandom[CoilLightRNG](-1,1),frandom[CoilLightRNG](-1,1)) * 30;  
				HaloMath.SpawnFX("UnmakerLaserPuff", pos+randPos, frandom[CoilLightRNG](0,360), 5, 45, 20);
					
				for(int i = 0; i < 5 * halodoom_effectintensity; i++)
				{
					randPos = (frandom[CoilLightRNG](-1,1),frandom[CoilLightRNG](-1,1),frandom[CoilLightRNG](-1,1)) * 20;  
					let puff = UnmakerLaserPuff(Spawn("UnmakerLaserPuff", pos+randPos));
					if(puff) 
					{
						puff.angle = frandom[CoilLightRNG](0,360);
						puff.pitch = -90;
						puff.laserAmt = 0.25;
						puff.laserDist = 25;
					}
				}
				
				// Lasers
				for(int i = 0; i < (5 * halodoom_effectintensity); i++)
				{
					vector2 view = (
						frandom[CoilLightRNG](0,360), 
						frandom[CoilLightRNG](-30,30)
					);
					
					let beam = LaserBeam.Create(self, 10, 0, 0, view.x,view.y, type:"LSR_LightRifle");
					beam.setEnabled(true);
					let beamCore = LaserBeam.Create(self, 10, 0, 0, view.x,view.y, type:"LSR_LightRifleCore");
					beamCore.setEnabled(true);
				}
				
				HaloMath.SpawnFX("UnmakerBallSmoke", pos+randPos, frandom[CoilLightRNG](0,360), random[CoilLightRNG](5,10), 64, 10, 0, 0, 8);			
				A_Explode(200, 100, damagetype:"Plasma");
				A_Quake(3, 10, 0, 1024, "");
				// freezeWait = 8;
				
				// Stun enemies within a given area
				double range = 512;
				let it = BlockThingsIterator.Create(self, range);
				while(it.Next())
				{
					let act = it.Thing;
					if(!act.bSHOOTABLE || (act is "Inventory")) continue;
					if(act != target) act.GiveInventoryType("EMP_DeBuff");
				}
				
			}
		stop;
	}
}