class Halo_Sidekick_Clip : Ammo 
{
	Default 
	{
		Inventory.MaxAmount 12;
	}
}

class HaloSidekick_Bullet : HaloBullet 
{
	Default
	{
		HaloProjectile.SetRanges SIDEKICK_RANGE1, SIDEKICK_RANGE2;
		HaloProjectile.MinRangeDamage SIDEKICK_MINDMG; 
		HaloProjectile.BaseDamage SIDEKICK_DMG;
		HaloProjectile.Speed_MPS SIDEKICK_BMPS;
		HaloProjectile.HeadshotDMGFactor SIDEKICK_HEDMOD;
	}
}

class Halo_Sidekick_Reserves : Ammo
{
	mixin WorldAmmoBehavior;
	Default 
	{
		Radius 8;
		Height 6;
		Scale 0.65;

		Inventory.Amount 12;
		Inventory.MaxAmount 60;
		Inventory.Icon "HLAMN0";
		Inventory.PickupSound "Halo/Pickup/Ammo";
		Inventory.PickupMessage "Picked up 12 Rounds for the Sidekick";
		
		Ammo.BackpackMaxAmount 128;
	}
	
	States
	{
		Spawn:
			HLAM N -1 Bright;
		stop;
	}
}

class Halo_Sidekick : HaloGun
{
	Default
	{
		//$Category "HaloDoom/Weapons"
		Weapon.SlotNumber 2;
		Obituary "%o was flicked by %k's Sidekick.";
		Inventory.PickupMessage	"Picked up the MK50 Sidekick.";
		Tag "Sidekick";
		Weapon.BobSpeed 2.45;
		Weapon.BobRangeX 0.30;
		Weapon.AmmoType1 "Halo_Sidekick_Reserves";
		Weapon.AmmoType2 "Halo_Sidekick_Clip";
		Weapon.AmmoGive 36;
		HaloGun.Faction "Human";
				
		// Recoil
		HaloGun.Bloom 0.8;
		HaloGun.BloomSpeed 0.35;
		HaloGun.BaseRecoil SIDEKICK_RECOIL;
		HaloGun.Inaccuracy SIDEKICK_ACCMOD;
		HaloGun.Crosshair "SdkRet", 1.0;
		HaloGun.UIGraphic "WI_SDK", 0.35, 0.35;
		HaloGun.SetupUIAmmo "WI_AMM7", 12, 14, 0, 6;
		
		HaloGun.PowerTier P_NORM;
		
		RecoilWeapon.YOffsetRange 0, 40;
	}
	
	override void MarkPrecacheSounds()
	{
		// Prevent stutters by precaching weapon sounds.
		MarkSound("Halo/Weapons/Sidekick/Fire");
		MarkSound("Halo/Weapons/Sidekick/Fire/Bass");
		MarkSound("Halo/Weapons/Sidekick/Mech");
		MarkSound("Halo/Weapons/Sidekick/Reload");
		MarkSound("Halo/Weapons/Sidekick/Reload/Empty");
		MarkSound("Halo/Weapons/Sidekick/Draw");
	}
	
	action void A_FireSidekick(bool middle = false)
	{
		A_Light(2);
		A_WeapSound("Halo/Weapons/Sidekick/Fire", 0);
		A_WeapSound("Halo/Weapons/Sidekick/Fire/Bass", CHANF_OVERLAP);
		A_ShootProjectile("HaloSidekick_Bullet", middle ? 0 : 12);
		A_SetSFXPos(25, middle ? 0 : -9,-7);
		A_SpawnSFX("MuzzleSmoke", 0,0);
		A_SetSFXPos(25,-20,-5);
		A_SpawnSFX("PistolCasing", -90,20);
		A_TakeAmmo();
		A_UpdateSpread();
	}
	
	bool sightsHold;
	States
	{
		Ready:
			TNT1 A 0 A_JumpIf(!A_DoFullSelectAnimation(), "Ready.Chambered");
			TNT1 A 4 A_WeapSound("Halo/Weapons/Sidekick/Draw");
			WED1 ABCDEFGHIJKLMNOPQRSTUVWXYZ 1 A_DoSelectAnim(-5, true);
			WED2 ABCDEF 1 A_DoSelectAnim(-5, true);
		goto Ready.Active;
		Ready.Chambered:
			TNT1 A 0 A_WeapSound("Halo/Weapons/Sidekick/Draw");
			WES1 ABCD 1 A_DoSelectAnim(-5);
		Ready.Active:
			WEG1 A 1 
			{
				A_HaloWeaponReady(WRF_ALLOWRELOAD, usescope:false);
				return A_JumpIf(A_ShouldEnableScope(), "Sights.Enable");
			}
		loop;
		
		Ready.ADS:
			WEA1 S 1 
			{
				A_HaloWeaponReady(WRF_ALLOWRELOAD, usescope:false);
				return A_JumpIf(A_ShouldDisableScope(invoker.sightsHold), "Sights.Disable");
			}
		loop;
		
		Ready.Dryfire:
			WEG1 A 12 A_WeapSound("Halo/Weapons/DryFire", CHANF_OVERLAP);
		goto Ready.Active;

		Select:
			TNT1 A 0 A_GunRaise();
		wait;

		Deselect:
			TNT1 A 0 A_SetCustomScope(0);
			WES1 DCBA 1;
			WES1 A 1 A_GunLower();
		wait;
		
		Fire:
			TNT1 A 0 A_JumpIf(A_CheckInScope(), "Fire.FromSights");
			TNT1 A 0 A_JumpIf(CountLoadedAmmo() == 1, "Fire.Empty");
			WEF1 A 1
			{
				A_RecoilOffset(0,8,1);
				return A_GunCheckReload();
			}
			TNT1 A 0 
			{
				A_FireSidekick();
				A_SetRecoil(1.20, 0, 2);
				A_RQuakeEx(2,2,2,2,0,20,"",QF_RELATIVE|QF_WAVE);
			}
			WEF1 B 1 bright A_RecoilOffset(25,-10,4);
			WEF1 C 1 
			{
				A_Light(0);
				A_SetRecoil(-0.18, 0, 8);
			}
			TNT1 A 0 A_WeapSound("Halo/Weapons/Sidekick/Mech", CHANF_OVERLAP);
			WEF1 DEF 1;
			WEF1 GHI 1 
			{
				A_RecoilOffset(0,0,4);
				return A_CheckRapidFire();
			}
			WEF1 JKLMNOPQRSTUV 1 A_CheckRapidFire();
		Hold:
			WEG1 A 1 A_CheckRapidFire();
			TNT1 A 0 A_ReFire("Hold");
		goto Ready.Active;
		
		Fire.Empty:
			WEF2 B 1
			{
				A_RecoilOffset(0,8,1);
				return A_GunCheckReload();
			}
			TNT1 A 0 
			{
				A_FireSidekick();
				A_SetRecoil(1.70, 0, 2);
				A_RQuakeEx(2,3,2,3,0,20,"",QF_RELATIVE|QF_WAVE);
			}
			WEF2 C 1 bright A_RecoilOffset(10,-5,4);
			WEF2 D 1 
			{
				A_Light(0);
				A_SetRecoil(-0.18, 0, 8);
			}
			TNT1 A 0 A_WeapSound("Halo/Weapons/Sidekick/Mech", CHANF_OVERLAP);
			WEF2 EF 1;
			WEF2 GHIJKLMNOPQRSTUVWXYZ 1 A_RecoilOffset(0,0,4);
		goto Reload.Empty;
		
		Fire.FromSights:
			TNT1 A 0 A_GunCheckReload();
			TNT1 A 0 A_Jump(CountLoadedAmmo() == 1, "Fire.FromSights.Empty");
			WEA1 A 1
			{
				A_FireSidekick(true);
				A_SetRecoil(0.5, 0, 2);
				A_RQuakeEx(2,3,2,3,0,20,"",QF_RELATIVE|QF_WAVE);
			}
			WEA1 B 1 bright A_RecoilOffset(0,-10,4);
			WEA1 C 1 
			{
				A_Light(0);
				A_SetRecoil(-0.18, 0, 8);
			}
			TNT1 A 0 A_WeapSound("Halo/Weapons/Sidekick/Mech", CHANF_OVERLAP);
			WEA1 DEF 1;
			WEA1 GHI 1 
			{
				A_RecoilOffset(0,0,4);
				return A_CheckRapidFire();
			}
			WEA1 JKLMNOPQR 1 A_CheckRapidFire();
		Hold.FromSights:
			WEA1 S 1 A_CheckRapidFire();
			TNT1 A 0 A_ReFire("Hold.FromSights");
		goto Ready.ADS;
			
		Fire.FromSights.Empty:
			WEA1 T 1 
			{
				A_FireSidekick(true);
				A_SetRecoil(1.0, 0, 2);
				A_RQuakeEx(2,3,2,3,0,20,"",QF_RELATIVE|QF_WAVE);
			}
			WEA1 U 1 bright A_RecoilOffset(0,-10,4);
			WEA1 V 1 
			{
				A_Light(0);
				A_SetRecoil(-0.18, 0, 8);
			}
			TNT1 A 0 A_WeapSound("Halo/Weapons/Sidekick/Mech", CHANF_OVERLAP);
			WEA1 WXYZ 1;
			WEA2 ABCDEFGHIJKL 1 A_RecoilOffset(0,0,4);
		goto Reload.FromSights;
		
		Reload.FromSights:
			WEG1 A 1;
			TNT1 A 0 A_SetCustomScope(0);
		Reload:
			TNT1 A 0 A_JumpIf(A_CheckInScope(), "Reload.FromSights");
			TNT1 A 0 A_ValidateReload("Ready.Dryfire");
			TNT1 A 0 A_JumpIf(!CountLoadedAmmo(), "Reload.Empty");
			TNT1 A 0 A_StartSound("Halo/Weapons/Sidekick/Reload", CHAN_RELOADING, CHANF_OVERLAP);
			WET1 ABCDEFGHIJKLMNOPQRSTUVWXYZ 1;
			WET2 ABCDEFGHI 1;
			WET2 J 1 A_ReloadClip();
			WET2 KLMNOPQRSTUVWXYZ 1;
			WET3 ABCDEFGHIJKLMNOPQRS 1;
			TNT1 A 0 A_GotoState("Ready.Active"); 
		
		Reload.Empty:
			TNT1 A 0 A_WeapSound("Halo/Weapons/Sidekick/Reload/Empty", CHANF_OVERLAP);
			WEE1 ABCDEFGHIJKLM 1;
			TNT1 A 0 
			{
				A_SetSFXPos(10,-5,-15);
				A_SpawnSFX("Debris_SidekickClip", 0, 60);
			}
			WEE1 NOPQRSTUVWXYZ 1;
			WEE2 ABCDEFGHIJ 1;
			WEE2 K 1 A_ReloadClip();
			WEE2 LMNOPQRSTUVWXYZ 1;
			WEE3 ABCDEFGHIJKLMNOPQRSTUVWXYZ 1;
		goto Ready.Active;
		
		Sights.Enable:
			WEA1 S 2;
			TNT1 A 0 
			{
				invoker.sightsHold = invoker.ADS_Held;
				A_SetCustomScope(1);	
			}
		goto Ready.ADS;
		
		Sights.Disable:
			TNT1 A 0 A_SetCustomScope(0);
			WEG1 A 1;
		goto Ready.Active;	
		
		Spawn:
			WEP1 A -1;
		stop;
	}
}
