
class Halo_StanchionClip : Ammo 
{
	Default
	{
		Inventory.MaxAmount 100;
	}
}
class Halo_StanchionReserves : Ammo
{
	mixin WorldAmmoBehavior;
	Default 
	{
		Radius 8;
		Height 6;
		Scale 0.65;
		
		Inventory.Amount 50;
		Inventory.MaxAmount 300;
		Inventory.Icon "HLAMM0";
		Inventory.PickupSound "Halo/Pickup/Ammo";
		Inventory.PickupMessage "Picked up 1 Battery for Stanchion (50%)";
		
		Ammo.BackpackMaxAmount 600;
	}
	
	States
	{
		Spawn:
			HLAM M -1 Bright;
		stop;
	}
}

class StanchionBeamDeco : MBeamSpawner
{
	double scale;
	override void Setup()
	{
		jitterAngle = 20;
		jitterPitch = 4;
		beamAlpha = 1.0;
		useStaticAim = true;
		src.LineTrace(src.angle, 8192, src.pitch, 0, (src.player.viewz-src.pos.z), src.radius, data:staticAimData);
		if(staticAimData.HitLocation ~== (0,0,0)) staticAimData.HitLocation = getOffsetPos(src, (8192, 0, 0));
		SetupVisuals("2970ff", "3faafc", 2.0 * scale, 1.5 * scale);	
	}
	
	override void BeamTick()
	{
		freeze = true;
		beamAlpha *= 0.93;
	
		if(beamAlpha <= 0.01)
		{
			Disable();
			Destroy();
		}
	}
}

class Halo_Stanchion : HaloGun
{
	int fxCounter; // Used for charge lightning.
	bool justFiredCharged; // Used to prevent quickswap abuse.
	const CHAN_CHARGING = 12;
	const CHAN_CHARGED = 13;
	bool fullyCharged;
	int chargeTimer;
	bool forceChargedFire;
	
	Default
	{
		//$Category "HaloDoom/Weapons"
		Weapon.SlotNumber 5;
		Obituary "%o got the Quake 2 Treatment from %k's Stanchion.";
		Inventory.PickupMessage	"Picked up the M99 SAR Stanchion.";
		Tag "Stanchion";
		Weapon.BobSpeed 1.87;
		Weapon.BobRangeX 0.63;
		Weapon.AmmoType1 "Halo_StanchionReserves";
		Weapon.AmmoGive 200;
		Weapon.AmmoType2 "Halo_StanchionClip";
		HaloGun.Faction "Human";
		
		HaloGun.PowerTier P_UBER;
				
		// Recoil
		RecoilWeapon.RecoilSpeed 20;
		HaloGun.HasBattery true, 10;
		HaloGun.Bloom 1.25;
		HaloGun.BloomSpeed 0.08;
		HaloGun.BaseRecoil STANCHION_RECOIL;
		HaloGun.Inaccuracy STANCHION_ACCMOD;
		HaloGun.Crosshair "StanRet", 1.0;
		HaloGun.UIGraphic "WI_STAN", 0.8, 1.0;
		HaloGun.UISight "SI_SNPR", 1.0, 0.8;
		HaloGun.SetupScope 4.0, 0.25;
		HaloGun.ZoomSounds "Halo/Weapons/Sniper/Zoom/IN", "Halo/Weapons/Sniper/Zoom/OUT";
		
		RecoilWeapon.YOffsetRange 0, 100;
		-HaloGun.SI_Vignette;
	}
	
	override int GetPowerTier()
	{	
		if(HaloPlayer.IsGameType("SpartanOverkill")) return P_POWER | P_UBER;
		return super.GetPowerTier();
	}
	
	override void OnQuickswap()
	{
		if(justFiredCharged) heat = 0;
	}
	
	override void DoEffect()
	{
		super.DoEffect();
				
		// Stop charge sounds if this weapon isn't currently selected.
		if(Owner.player && Owner.player.ReadyWeapon != self)
		{
			Owner.A_StopSound(CHAN_CHARGED);
			Owner.A_StopSound(CHAN_CHARGING);
		}
	}
	
	action void MuzzleLightning()
	{
		vector3 muzzlepos = HaloMath.RelativeV3Offset(self, 0,0,0, 25,10,-8, 1.);
		vector2 view = (angle, pitch);
		int adjustedAmt = max(5 * halodoom_effectintensity, 0);
		for(int i = 0; i < adjustedAmt; i++)
		{
			view.x = angle + frandom[WeapFX](-20,20);
			BiriBiri.DoLightning(muzzlepos, view, dist:50, 0.5, 8.0, 10.0, 30, 0);
		}
	}
	
	action void A_SpriteLightning(int amt = 10, vector2 posoffs = (0,0))
	{
		uint boltlen = 60;
		vector2 muzzlePos = (280,20) + posoffs;
		DoSpriteLightning(
			amt,
			frandom[WeapFX](-180,180), muzzlePos, boltlen:boltlen, 
			stepsize:2.5, roughness:14
		);
	}
		
	override void MarkPrecacheSounds()
	{
		// Prevent stutters by precaching weapon sounds.
		MarkSound("Halo/Weapons/Stanchion/Fire");
		MarkSound("Halo/Weapons/Stanchion/Fire/Bass");
		// MarkSound("Halo/Weapons/Stanchion/Reload");
		// MarkSound("Halo/Weapons/Stanchion/Ready");
	}
	
	action void A_MuzzlePlasma(double amt, Color col, double density = 3.0, int lifetime = 8)
	{
		for(int i = 0; i < max(1, amt * halodoom_effectintensity); i++)
		{
			let pl = SetupPlasmaLightning(16, -4, 9, scale:1.6, density:density, shading:col, onlySpawn:true);			
			if(pl) pl.lifeTime = lifetime;
		}
	}
	
	action void A_SpawnDecoBeam(double fw, double lr, double ud, bool charged = false)
	{
		let decobeam = StanchionBeamDeco(MBeamSpawner.Create(self, fw, lr, ud, 0, spawnerType:"StanchionBeamDeco"));
		decobeam.scale = charged ? 8.0 : 4.0;
		decobeam.Enable(NULL);
	}
	
	action state A_DoChargeLoop()
	{
		A_RecoilOffset(frandom[WeapFX](-2,2),frandom[WeapFX](-2,2),2);
		if(invoker.fxCounter++ > 2)
		{
			A_SpriteLightning(amt:10, posoffs:(-90,60));
			invoker.fxCounter = 0;
		}
		
		if(!invoker.fullyCharged)
		{
			// if( !(int(invoker.heat*100)%5) ) A_TakeAmmo(4);
			if(!(level.maptime%20)) A_HUDMessage(String.Format("Charge Status: %d%%", min(100,invoker.heat * 100)));
			invoker.heat += 0.01;
		}
		
		if(invoker.heat >= 1.2 && !invoker.fullyCharged) 
		{
			// A_StartSound("Halo/Weapons/Stanchion/Charge/Complete", CHAN_AUTO, CHANF_OVERLAP);
			invoker.fullyCharged = true;
		}
		
		if(A_ButtonStatus(BT_ATTACK, BTS_UP) || invoker.forceChargedFire)
		{
			invoker.forceChargedFire = false;
			return ResolveState("Rail.ChargeEnd");
		}
			
		return ResolveState(null);
	}
	
	action state A_ChargeBegin()
	{
		bool stopCharge = A_ButtonStatus(BT_ATTACK, BTS_UP);
		if(stopCharge)
		{
			return ResolveState("Rail.ChargeEnd");
		}
		if(invoker.fxCounter++ >= 2)
		{
			A_SpriteLightning(amt:10, posoffs:(-90,60));
			A_RecoilOffset(frandom[WeapFX](-3,3),frandom[WeapFX](-3,3),2);
			invoker.fxCounter = 0;
		}
		return ResolveState(null);
	}
	
	action void A_FireStanchion(bool charged = false)
	{
		// Lowered crosshair shenanigans.
		vector2 aimoffs = (0,0);
		if(A_GetWeapYOffs() > 0 && !A_CheckInScope()) aimoffs.y = 5;
		A_SpawnDecoBeam(50, -3, -5, charged);
		A_SpawnDecoBeam(50, -3, -9, charged);
		A_SpawnDecoBeam(50,  3, -9, charged);
		A_SpawnDecoBeam(50,  3, -5, charged);
		A_SpawnDecoBeam(50, -3, 5, charged);
		A_SpawnDecoBeam(50, -3, 9, charged);
		A_SpawnDecoBeam(50,  3, 9, charged);
		A_SpawnDecoBeam(50,  3, 5, charged);
		if(charged)
		{
			A_SpawnDecoBeam(50, -6, -10, charged);
			A_SpawnDecoBeam(50, -6, -18, charged);
			A_SpawnDecoBeam(50,  6, -18, charged);
			A_SpawnDecoBeam(50,  6, -10, charged);
			A_SpawnDecoBeam(50, -6, 10, charged);
			A_SpawnDecoBeam(50, -6, 18, charged);
			A_SpawnDecoBeam(50,  6, 18, charged);
			A_SpawnDecoBeam(50,  6, 10, charged);
		}
		
		if(charged)
		{
			A_Light(4);
			A_WeapSound("Halo/Weapons/Stanchion/Fire", CHANF_OVERLAP, true);
			A_WeapSound("Halo/Weapons/Stanchion/Fire/Bass", CHANF_OVERLAP, true);
			
			RailgunProjectile.FireRailgun(self, STANCHION_DMG, STANCHION_DMG*0.25, (50, 8, -6), size:3.0, viewoffs:aimoffs, disableTrail:true);	
			invoker.justFiredCharged = true;
			
			A_SetSFXPos(25,-5,-7);
			for(int i = 0; i < 15; i++)
				A_SpawnSFX("MuzzleSmoke", 0,0);
				
			A_MuzzlePlasma(5, "#ffffff",lifetime:16);
			A_MuzzlePlasma(3, "#0fd4f2",lifetime:16);
			A_TakeAmmo(100);
			invoker.chargeTimer = 0;
		}
		else
		{
			A_Light(2);
			A_WeapSound("Halo/Weapons/Stanchion/Uncharged/Fire", CHANF_OVERLAP, true);
			A_WeapSound("Halo/Weapons/Stanchion/Uncharged/Fire/Bass", CHANF_OVERLAP, true);
			
			double spread = A_RecoilSpread();
			aimoffs.x += spread * 0.2;
			aimoffs.y += spread * 0.2;
			
			RailgunProjectile.FireRailgun(self, SNIPER_DMG*2.0, 64, (50, 8, -6), size:0.6, viewoffs:aimoffs, doShockwave: false, colors:(0xFF0228e6, 0xFF5100ff, 0xFFFFFFFF), disableTrail:true);	
			A_SetSFXPos(25,-5,-7);
			for(int i = 0; i < 5; i++)
				A_SpawnSFX("MuzzleSmoke", 0,0);
				
			A_MuzzlePlasma(2, "#74b8fc", 8, 4);
			A_TakeAmmo(10);
		}
		A_UpdateSpread();
	}

	States
	{
		
		DoSmoke:	
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 3 
			{
				invoker.heat *= 0.9;
				let psp = player.GetPSprite(OverlayID());
				if(psp) psp.frame = random[WeapFX](3,8);
				A_SetSFXPos(25,-5,-7);
				for(int i = 0; i < random[WeapFX](1,5); i++)
					A_SpawnSFX("MuzzleSmoke", 0,0);
				if(!(psp.frame%5)) MuzzleLightning();
			}
			TNT1 A 0 
			{ 
				invoker.justFiredCharged = false;
				invoker.heat = 0; 
			}
 		stop;
		
		ChargeThink:
			TNT1 ABCDEF 1
			{
				if(invoker.heat >= 1.2 && !invoker.forceChargedFire)
				{
					A_StartSound("Halo/Weapons/Stanchion/Charge/Loop", CHAN_CHARGED, CHANF_LOOPING);
					if(A_GetFrame(OverlayID()) == 4)
					{
						A_SpriteLightning(amt:10, posoffs:(-90,60));
						A_RecoilOffset(frandom[WeapFX](-4,4),frandom[WeapFX](-4,4),2);
					}
					
					int maxChargeTime = (TICRATE*10);
					if(invoker.chargeTimer > maxChargeTime * 0.4) 
						A_StartSound("Halo/Weapons/Stanchion/Charge/Warn", CHAN_CHARGED, CHANF_OVERLAP|CHANF_LOOPING);
						
					if(++invoker.chargeTimer >= maxChargeTime)
					{
						invoker.forceChargedFire = true;
						invoker.chargeTimer = 0;
						A_StopSound(CHAN_CHARGED);
					}
					else
					{
						double timeSecs = round((maxChargeTime - invoker.chargeTimer) / double(TICRATE));
						if(!(invoker.chargeTimer%35)) A_HUDMessage(String.Format("WARNING OVERHEAT IN %ds", timeSecs));
					}
				}
				else
				{
					A_StopSound(CHAN_CHARGED);
				}
			}
		loop;
		
		Ready:
			TNT1 A 1 A_WeapSound("Halo/Weapons/Stanchion/Draw");
			TNT1 A 0 A_JumpIf(!A_DoFullSelectAnimation(), "Ready.Chambered");
			W9D1 ABCDEFGHIJKLMNOPQRSTUVWXYZ 1 A_DoSelectAnim(0, true); 
			W9D2 ABCDEFGHIJKLMNOPQRSTUVWXY 1 A_DoSelectAnim();
		goto Ready.Active;
		Ready.Chambered:
			W9S1 LKJIHGFEDCBA 1 A_DoSelectAnim(); 
		Ready.Active:
			W9G1 A 1 
			{
				A_Overlay(69, "ChargeThink", true);
				A_HaloWeaponReady(WRF_ALLOWRELOAD, true);
				A_StopSound(CHAN_CHARGING);
			}
		loop;
		
		Ready.Dryfire:
			W9G1 A 4 A_WeapSound("Halo/Weapons/DryFire", CHANF_OVERLAP);
		goto Ready.Active;

		Select:
			TNT1 A 1 A_GunRaise();
		wait;

		Deselect:
			W9S1 ABCDEFGHIJKL 1;
			TNT1 A 1 
			{
				A_GunLower();
				A_StopSound(CHAN_CHARGED);
				A_StopSound(CHAN_CHARGING);
				invoker.justFiredCharged = false;
			}
		wait;
		
		Fire:
		Hold:
			W9F1 A 4 A_StartSound("Halo/Weapons/Stanchion/Charge/PreCharge", CHAN_CHARGING, CHANF_NOSTOP);
			TNT1 A 0 A_RefireState("Rail.ChargeStart");
		Fire.Normal:
			TNT1 A 0 A_GunCheckReload();
			TNT1 A 0 A_SetZoom(0.8, 1);
			W9F1 B 1 Bright
			{
				A_RecoilOffset(40,10,2);
				A_SetRecoil(2.78, 0, 2);
				A_FireStanchion(false);
				A_RQuakeEx(4,2,1,3,0,20,"",QF_RELATIVE|QF_WAVE|QF_SCALEDOWN);
				A_RollQuake(2,10,1);
				A_SetZoom(0.8, 2);
				if(invoker.heat < 1.0) invoker.heat += 0.07;
			}
			TNT1 A 0 A_Light(0);
			W9F1 CDE 1 Bright 
			{
				A_RecoilOffset(20,5,4);
				A_SetZoom(1.0, 6);
				A_RQuakeEx(2,2,2,4,0,20,"",QF_RELATIVE|QF_SCALEDOWN);
			}
			W9F1 EEE 2 
			{
				A_SetZoom(1.0, 6);
				A_RecoilOffset(0,0,6);
			}
			W9F1 FGHIJKLM 1;
			W9F1 NOPQRSTUVWXYZ 1 A_ReFireState("Fire");
			W9F2 ABCDEFGHIJ 1 A_ReFireState("Fire");
		goto Ready.Active;
		
		Fire.Charged:
			TNT1 A 0 A_SetZoom(0.7, 1);
			W9CH H 1 Bright
			{
				A_RecoilOffset(60,60,6);
				A_FireStanchion(true);
				A_RQuakeEx(2,10,2,10,0,20,"",QF_RELATIVE|QF_WAVE|QF_SCALEDOWN);
				A_Pushback(30);
				A_SetZoom(0.7, 1);
				invoker.fullyCharged = false;
			}
			W9CH IJK 1 Bright A_RecoilOffset(60,60,6);
			TNT1 A 0 
			{
				A_RecoilOffset(60,60,6);
				A_SetRecoil(4.42, 0, 2);
				A_FireStanchion(true);
				A_RollQuake(8, 30, 1);
				A_RQuakeEx(2,10,2,10,0,20,"",QF_RELATIVE|QF_WAVE|QF_SCALEDOWN);
				A_Pushback(30);
			}
			W9CH LMNOPQRSTUVWXYZ 1
			{
				A_SetZoom(1.0, 8);
				A_Light(0);
			}
			TNT1 A 0 A_Overlay(60, "DoSmoke");
			W9CI ABCDEFGHIJ 1 A_RecoilOffset(0,0,10);
			W9CI KLMNOPQRSTUVWXYZ 1;
			W9CJ ABCDE 1;
			W9G1 A 3;
		goto Ready.Active;
					
		/*
			Reload:
				W9R1 A - Reload Begin
				W9R1 X - Mag Out
				W9F2 G - Mag Drop
				W9R3 H - Mag In
				W9R4 P - Reload End

			Empty Reload:
				W9R4 Q - Reload Begin
				W9R5 J - Mag Out
				W9R6 A - Mag Drop
				W9R6 P - Mag In
				W9R7 U - Bolt Pull
				W9R8 J - Bolt Release
				W9R8 X - Reload End 
		*/
					
		Reload:
			W9G1 A 4;
			TNT1 A 0 A_ValidateReload("Ready.Dryfire");
			TNT1 A 0 A_ScopeDisable();
			TNT1 A 0 A_JumpIf(!CountLoadedAmmo(), "Reload.Empty");
			TNT1 A 0 A_StartSound("Halo/Weapons/Stanchion/Reload", CHAN_RELOADING, CHANF_OVERLAP);
			W9R1 ABCDE 1 A_SetRecoil(0.45, 0, 4); 
			W9R1 FGHIJKLMNOPQRSTUVW 1;
			W9R1 X 1 A_SetRecoil(-1.45, 0, 1);
			W9R1 YZ 1;
			W9R2 ABCDEF 1;
			W9R2 G 1 
			{
				A_SetSFXPos(10,-20,-25);
				A_SpawnSFX("Debris_StanchionMagazine", 0, 60);
			}
			W9R2 HIJKLMNOPQRSTUVWXYZ 1;
			W9R3 ABCDEFG 1;
			W9R3 H 1
			{
				A_SetRecoil(1.45, 0, 1);
				A_ReloadClip();
			}
			W9R3 IJKLMNOPQRSTUVWXYZ 1;
			W9R4 ABCDEFGHIJ 1;
			W9R4 KLMNOP 1 A_SetRecoil(-0.45, 0, 4);
			TNT1 A 0 A_GotoState("Ready.Active"); 
			
		Reload.Empty:
			TNT1 A 0 A_StartSound("Halo/Weapons/Stanchion/Reload/Empty", CHAN_RELOADING, CHANF_OVERLAP);
			W9R4 QRSTU 1 A_SetRecoil(0.45, 0, 4); 
			W9R4 VWXYZ 1;
			W9R5 ABCDEFGHI 1;
			W9R5 J 1 A_SetRecoil(-1.45, 0, 1);
			W9R5 KLMNOPQRSTUVWXYZ 1;
			W9R6 A 1 
			{
				A_SetSFXPos(10,-20,-25);
				A_SpawnSFX("Debris_StanchionMagazine", 0, 60);
			}
			W9R6 BCDEFGHIJKLMNO 1;
			W9R6 P 1 
			{
				A_SetRecoil(1.45, 0, 1);
				A_ReloadClip();
			}
			W9R6 QRSTUVWXYZ 1;
			W9R7 ABCDEGHIJKLMNOPQRST 1;
			W9R7 U 1 A_SetRecoil(0, -1.25, 4);
			W9R7 VWXYZ 1;
			W9R8 ABCDEFGHI 1;
			W9R8 J 1 A_SetRecoil(0, 1.25, 4);
			W9R8 KLMNOPQRS 1;
			W9R8 TUVWX 1 A_SetRecoil(-0.45, 0, 4);
			TNT1 A 0 A_GotoState("Ready.Active"); 
			
		Rail.ChargeStart:
			W9C1 A 1 
			{
				bool lowBattery = CountLoadedAmmo() < 100; 
				bool tooHot = invoker.heat >= 1.2;
				bool cooldown = invoker.justFiredCharged;
				if(tooHot || lowBattery || cooldown) 
				{
					A_WeapSound("Halo/Weapons/DryFire", CHANF_OVERLAP);
					if(lowBattery) A_HUDMessage("Cannot begin charge: LOW BATTERY");
					if(tooHot) A_HUDMessage("Charge Status: 100%");
					if(cooldown) A_HUDMessage("Cannot begin charge: OVERHEATED");
					return ResolveState("Rail.ChargeEnd");
				}
				
				if(invoker.heat >= 1.0) // Skip right to charge loop, if we've built up a lot of heat.
					return ResolveState("Rail.ChargeLoop");
				
				A_StartSound("Halo/Weapons/Stanchion/Charge", CHAN_CHARGING, CHANF_OVERLAP|CHANF_NOSTOP);
				return ResolveState(null);
			}
			
			W9C1 ACEGIKMOQSUWY 1 A_ChargeBegin();
			W9C2 ACEGIKMOQSUWY 1 A_ChargeBegin();
			W9C3 BDFHJLNPRTVXZ 1 A_ChargeBegin();
			W9C4 BDFHJLNPRTVXZ 1 A_ChargeBegin();
			W9C5 ACEGIKMOQSUWY 1 A_ChargeBegin();
			W9C6 ACEGIKMOQSUWY 1 A_ChargeBegin();
			W9C7 BDFHJLNPRTVXZ 1 A_ChargeBegin();
			W9C8 ABC 1 A_ChargeBegin();
		Rail.ChargeLoop:
			W9C8 DEFGHIJKLMNOPQRSTUVWXYZ 1 A_DoChargeLoop();
			W9C9 ADEFGHIJKLMNOPQRSTUVWXYZ 1 A_DoChargeLoop();
			W9CA ADEFGHIJKLMNOPQRSTUVWXYZ 1 A_DoChargeLoop();
			W9CB ADEFGHIJKLMNOPQRSTUVWXYZ 1 A_DoChargeLoop();
			W9CC ADEFGHIJKLMNOPQRSTUVWXYZ 1 A_DoChargeLoop();
			W9CD ADEFGHIJKLMNOPQRSTUVWXYZ 1 A_DoChargeLoop();
			W9CE ADEFGHIJKLMNOPQRSTUVWXYZ 1 A_DoChargeLoop();
			W9CF ADEFGHIJKLMNOPQRSTUVWXYZ 1 A_DoChargeLoop();
			W9CG ADEFGHIJKLMNOPQRSTUVWXYZ 1 A_DoChargeLoop();
		loop;
		Rail.ChargeEnd:
			W9CH ABCDEFGHIJKLMNO 1;
			W9G1 A 6 
			{
				invoker.handsbusy = false; // Ensure handsbusy is properly cleared.
				A_WeapSound("Halo/Weapons/Stanchion/Charge/PreFire", CHANF_OVERLAP);
				A_RecoilOffset(0,0,6);
				A_StopSound(CHAN_CHARGING);
				
				if(invoker.fullyCharged) 
					return ResolveState("Fire.Charged");
					
				return ResolveState(null);
			}
		goto Ready.Active;

		Scope.ON:
			TNT1 A 1 A_ScopeON();
			TNT1 A 5 A_SetZoom(invoker.scopezoom * 0.5, 3, true);
			TNT1 A 0 
			{
				bool holding = A_ButtonStatus(BT_ALTATTACK, BTS_HELD) && !A_ButtonStatus(BT_ALTATTACK, BTS_PRESSED);
				invoker.zoom_btnstate = holding ? 0 : BTS_PRESSED;
				if(holding) return ResolveState("Scope.Ready");
				return ResolveState("Scope.Wait");
			}
		goto Scope.Wait;
		
		Scope.Two:
			TNT1 A 1 A_ScopeON();
			TNT1 A 5 A_SetZoom(invoker.scopezoom * 2.0, 3, true);
		goto Scope.Ready;
		
		Scope.Wait:
			TNT1 A 1 
			{
				State ret = ResolveState(null);
				if(!invoker.enablezoom) ret = ResolveState("Scope.OFF");
				if(A_ButtonStatus(BT_ALTATTACK, BTS_PRESSED)) ret = ResolveState("Scope.Two");
				return ret;
			}
		loop;
		
		SetupGunLightning:
			BIRI D 0;
		goto GunLightning;

		Spawn:
			STNF A -1;
		stop;
	}
}
